"""Python SDK for authoring, validating, expanding, and serializing FrameGraph.

The SDK is a hand-written Python binding over the repository's authoritative
Pydantic model in :mod:`models.framegraph`. It deliberately does not duplicate
core schema types; builders and helpers lower into the model and validate there.
"""
from __future__ import annotations

from framegraph.sdk.author import DocumentBuilder, Handle, PageBuilder, StackBuilder
from framegraph.sdk.chart import Chart
from framegraph.sdk.clip import (
    clip_circle,
    clip_ellipse,
    clip_inset,
    clip_path,
    clip_polygon,
    clip_rect,
    normalize_clip,
)
from framegraph.sdk.conform import (
    assert_golden,
    page_hashes,
    render_page_svgs,
    render_pages_with_stats,
    write_golden,
)
from framegraph.sdk.draw import (
    Frame, Material, Scene3D, function_plot, multiview, parametric_curve, polar_plot,
)
from framegraph.sdk.expand import ExpandOptions, ExpandedDocument, expand
from framegraph.sdk.geometry import (
    Camera,
    CubicBezier,
    Mat3,
    Mat4,
    Path,
    Vec2,
    Vec3,
    quarter_circle_kappa,
)
from framegraph.sdk.figure import (
    FigureAsset,
    FigureContent,
    FigurePlacement,
    FigureProvenance,
    FigureRef,
    ImportedFigurePlacement,
    load_figure,
    merge_figure_defs,
    place_figure,
    place_imported_figure,
)
from framegraph.sdk.io import parse, serialize
from framegraph.sdk.layout import Box, BoxLike, column, grid, inset, row
from framegraph.sdk.macros import (
    cite,
    greeble,
    grid_lines,
    hatch_fill,
    lorem,
    lorem_paragraphs,
    md,
    paragraph,
    ref,
    sparkline,
    theme,
)
from framegraph.sdk.metrics import measure_text, text_height, wrap_text
from framegraph.sdk.model import (
    HEAD_VERSION,
    Document,
    ValidationError,
    model_module,
    to_plain_dict,
    validate_document,
)
from framegraph.sdk.topology import Edge, Graph, Node
from framegraph.sdk.fields import ScalarField, VectorField
from framegraph.sdk.lattices import Lattice, lattice
from framegraph.sdk import manifold
from framegraph.sdk.manifold import (
    klein_bottle,
    mobius,
    parametric,
    saddle,
    sphere,
    torus,
    wave,
)
from framegraph.sdk.region import (
    extract_objects,
    gradient_map,
    object_bbox,
    place_region,
    region_grade,
    select_in,
)
from framegraph.sdk.paint import (
    dots,
    effects,
    fill_stroke,
    grid_pattern,
    glow,
    hatch,
    linear_gradient,
    neon,
    pattern,
    radial_gradient,
    rgba,
    shadow,
    soft_shadow,
    stroke,
    text_style,
)
from framegraph.sdk.validate import Issue, ValidationReport, validate_static_rules
from framegraph.sdk.widgets import (
    Panel,
    Theme,
    avatar,
    badge,
    badge_width,
    button,
    card,
    default_theme,
    divider,
    field,
    kpi,
    pill,
    progress,
    register_theme,
    table,
    tabs,
    toggle,
)

__all__ = [
    "Chart",
    "Panel",
    "Theme",
    "assert_golden",
    "avatar",
    "badge",
    "badge_width",
    "button",
    "card",
    "clip_circle",
    "clip_ellipse",
    "clip_inset",
    "clip_path",
    "clip_polygon",
    "clip_rect",
    "default_theme",
    "divider",
    "field",
    "kpi",
    "pill",
    "progress",
    "register_theme",
    "table",
    "tabs",
    "toggle",
    "Camera",
    "CubicBezier",
    "Document",
    "DocumentBuilder",
    "Edge",
    "ExpandOptions",
    "ExpandedDocument",
    "Frame",
    "FigureAsset",
    "FigureContent",
    "FigurePlacement",
    "FigureProvenance",
    "FigureRef",
    "ImportedFigurePlacement",
    "greeble",
    "grid_lines",
    "grid_pattern",
    "Graph",
    "Handle",
    "hatch",
    "hatch_fill",
    "Lattice",
    "Material",
    "Node",
    "ScalarField",
    "VectorField",
    "lattice",
    "load_figure",
    "manifold",
    "merge_figure_defs",
    "HEAD_VERSION",
    "Issue",
    "Mat3",
    "Mat4",
    "PageBuilder",
    "Path",
    "Scene3D",
    "StackBuilder",
    "ValidationReport",
    "Vec2",
    "Vec3",
    "Box",
    "BoxLike",
    "column",
    "dots",
    "effects",
    "expand",
    "extract_objects",
    "fill_stroke",
    "function_plot",
    "glow",
    "gradient_map",
    "grid",
    "inset",
    "linear_gradient",
    "lorem",
    "lorem_paragraphs",
    "cite",
    "ref",
    "md",
    "measure_text",
    "model_module",
    "klein_bottle",
    "mobius",
    "multiview",
    "neon",
    "normalize_clip",
    "object_bbox",
    "page_hashes",
    "paragraph",
    "parametric",
    "parametric_curve",
    "pattern",
    "place_figure",
    "place_region",
    "polar_plot",
    "place_imported_figure",
    "parse",
    "region_grade",
    "select_in",
    "quarter_circle_kappa",
    "radial_gradient",
    "render_page_svgs",
    "render_pages_with_stats",
    "rgba",
    "row",
    "serialize",
    "shadow",
    "soft_shadow",
    "saddle",
    "sparkline",
    "sphere",
    "stroke",
    "text_height",
    "text_style",
    "theme",
    "to_plain_dict",
    "torus",
    "validate_document",
    "validate_static_rules",
    "ValidationError",
    "wrap_text",
    "wave",
    "write_golden",
]
