"""Agentic AI: A Complete Framework — corrected rebuild of a garbled AI-image infographic.

Generated by Claude Opus 4.8 via the FrameForge SDK.
Reference: _tmp/3hnxtkvmyqeh1.jpeg (AI-generated original with corrupted labels).
Improvements: corrected all garbled text, deduplicated the taxonomy (each concept
lives in exactly one ring), computed crescent-ring geometry, consistent type scale.
"""
import math

from frameforge.sdk import DocumentBuilder
from frameforge.sdk.paint import stroke

W, H = 1160, 1500
CY = 855
PAPER = "#F6F4EE"
INK = "#22303F"
SUB = "#5A6675"
ITEM = "#2A3542"
ARROW = "#37414F"

# layer palette: (cx, r, rim, fill, dark)
LAYERS = {
    "aiml":    (411, 144, "#2B6CB0", "#DFEBF7", "#1F5B9E"),
    "deep":    (457, 238, "#2F855A", "#E2F0E7", "#256B47"),
    "genai":   (503, 332, "#D97706", "#FBF0DB", "#B05E08"),
    "agents":  (549, 426, "#C53030", "#FAE5E0", "#A32626"),
    "agentic": (595, 520, "#4A5568", "#EBEEF2", "#37414F"),
}

doc = DocumentBuilder(title="Agentic AI: A Complete Framework", profile="diagram")
page = doc.page("poster", canvas={"size": [W, H]}, coordinate_mode="absolute")
bg = page.layer("bg")
L = page.layer("content")

bg.rect([0, 0, W, H], fill=PAPER)


def T(box, s, size=10.5, color=ITEM, weight=500, align="center", f="Inter",
      lh=None, ls=None):
    st = {"font_family": f, "size": size, "color": color, "align": align,
          "weight": weight}
    if lh is not None:
        st["line_height"] = lh
    if ls is not None:
        st["letter_spacing"] = ls
    if "\n" in s:
        st["white_space"] = "pre-line"
    L.text(box, s, style=st)


# ---------------------------------------------------------------- nested circles
for key in ("agentic", "agents", "genai", "deep", "aiml"):
    cx, r, rim, fill, _dark = LAYERS[key]
    L.circle([cx, CY], r, fill=fill, **stroke(4.5, color=rim))


# ------------------------------------------------- ring geometry helpers
def ray_hit(cxo, ro, cxi, ri, deg):
    """Along the ray from the OUTER circle's centre at `deg`, return (ux, uy,
    t_inner) where t_inner is the distance to the inner circle's boundary."""
    th = math.radians(deg)
    ux, uy = math.cos(th), math.sin(th)
    dx = cxi - cxo
    b = ux * dx
    disc = b * b - (dx * dx - ri * ri)
    t_in = b + math.sqrt(max(disc, 0.0))
    return ux, uy, t_in


def ring_mid(outer, inner, deg):
    cxo, ro = LAYERS[outer][0], LAYERS[outer][1]
    cxi, ri = LAYERS[inner][0], LAYERS[inner][1]
    ux, uy, t_in = ray_hit(cxo, ro, cxi, ri, deg)
    t = (t_in + ro) / 2.0
    return cxo + ux * t, CY + uy * t


def divider(outer, inner, deg, color):
    cxo, ro = LAYERS[outer][0], LAYERS[outer][1]
    cxi, ri = LAYERS[inner][0], LAYERS[inner][1]
    ux, uy, t_in = ray_hit(cxo, ro, cxi, ri, deg)
    L.polyline([[cxo + ux * t_in, CY + uy * t_in],
                [cxo + ux * ro, CY + uy * ro]],
               **stroke(1.1, color=color), opacity=0.38)


# ------------------------------------------------- ring content
# items stay off the thin left seam (|deg| <= ~150) and off the axis label band
RING_ITEMS = {
    ("deep", "aiml"): [
        (-135, "Attention\nMechanisms", 110),
        (-90, "Transfer Learning", 130),
        (-46, "Large Language\nModels (LLMs)", 120),
        (46, "Deep Belief\nNetworks", 115),
        (90, "Recurrent Networks\n& LSTMs", 150),
        (135, "Convolutional Neural\nNetworks (CNNs)", 135),
    ],
    ("genai", "deep"): [
        (-140, "Summarization", 84, 4.5),
        (-113, "Personalization", 120),
        (-82, "Multimodal Generation\n(text · image · audio)", 180),
        (-46, "Prompt\nEngineering", 110),
        (46, "Retrieval-Augmented\nGeneration (RAG)", 150),
        (82, "Speech Interfaces\n(ASR & TTS)", 140),
        (113, "Video\nGeneration", 100),
        (140, "Code\nGeneration", 84, 4.5),
    ],
    ("agents", "genai"): [
        (-136, "Multi-Agent\nCollaboration", 88, 5),
        (-119, "State\nPersistence", 105),
        (-90, "Planning\n(ReAct · CoT · ToT)", 150),
        (-61, "Task Scheduling\n& Prioritization", 140),
        (-32, "Goal\nDecomposition", 112),
        (32, "Tool Use\n(function calling)", 130),
        (60, "Human-in-the-Loop", 140),
        (88, "Self-Reflection &\nError Recovery", 145),
        (118, "Agent Coordination\n& Communication", 150, 5),
        (136, "Memory\n& Context", 88, 5),
    ],
    ("agentic", "agents"): [
        (-128, "Self-Improving\nAgents", 110, 7),
        (-106, "Intent\nRecognition", 105),
        (-84, "Rollback\nMechanisms", 120),
        (-62, "Feedback Loops\n& Evaluations", 130),
        (-40, "Cost & Resource\nManagement", 130),
        (40, "Long-Term Autonomy\n& Goal Chaining", 155),
        (62, "Governance, Safety\n& Guardrails", 140),
        (84, "Memory Governance\n& Retention", 150),
        (106, "Observability\n& Tracing", 120),
        (128, "Delegation &\nHandoff Protocols", 118, 7),
    ],
}

for (outer, inner), items in RING_ITEMS.items():
    rim = LAYERS[outer][2]
    degs = [tup[0] for tup in items]
    # cell dividers: midpoints between neighbours + closures at the label band
    # edges (±20°) and the thin left seam (180°)
    div_degs = [180.0, -20.0, 20.0]
    for a, b in zip(degs, degs[1:]):
        if a < 0 <= b:      # this gap is the axis label band — already closed at ±20
            continue
        div_degs.append((a + b) / 2.0)
    for d in div_degs:
        divider(outer, inner, d, rim)
    for tup in items:
        deg, s, w = tup[0], tup[1], tup[2]
        xoff = tup[3] if len(tup) > 3 else 0.0
        px, py = ring_mid(outer, inner, deg)
        px += xoff
        n_lines = s.count("\n") + 1
        h = 15 * n_lines + 8
        T([px - w / 2, py - h / 2, w, h], s, size=10.5, lh=1.22)


# the thin left seam of the outer ring carries its two labels as arc text
# (a horizontal box cannot sit inside that crescent without crossing a rim)
def arc_label(outer, inner, center_deg, s, size=10.5):
    from frameforge.sdk import measure_text
    from frameforge.sdk.pathtext import text_on_path
    cxo, ro = LAYERS[outer][0], LAYERS[outer][1]
    cxi, ri = LAYERS[inner][0], LAYERS[inner][1]
    _ux, _uy, t_in = ray_hit(cxo, ro, cxi, ri, center_deg)
    R = (t_in + ro) / 2.0
    length = measure_text(s, font_family="Inter", font_size=size) + 2.5 * len(s)
    half = math.degrees((length / 2.0 + 6.0) / R)
    if center_deg < 0:      # upper seam: walk anticlockwise so glyphs read L→R
        degs = [center_deg - half + k * (2 * half) / 24.0 for k in range(25)]
    else:                   # lower seam: walk clockwise for the same reason
        degs = [center_deg + half - k * (2 * half) / 24.0 for k in range(25)]
    pts = [[cxo + R * math.cos(math.radians(a)), CY + R * math.sin(math.radians(a))]
           for a in degs]
    L.extend(text_on_path(pts, s, size=size, family="Inter", weight=500,
                          color=ITEM))


arc_label("agentic", "agents", -149, "Agent Protocols (MCP · A2A)")
arc_label("agentic", "agents", 149, "Risk Management & Constraints")

# inner-circle items
T([336, 733, 150, 34], "Natural Language\nProcessing", size=10.5, lh=1.22)
T([336, 903, 150, 34], "Reasoning &\nProblem Solving", size=10.5, lh=1.22)

# ------------------------------------------------- axis labels + taglines
BANDS = [
    ("aiml", 411, "AI & ML", 20, "Turn data into decisions", None),
    ("deep", 625, "Deep Learning", 17, "Learn representations\nfrom data", "FOUNDATION"),
    ("genai", 765, "Gen AI", 20, "Create new content", "CREATION"),
    ("agents", 905, "AI Agents", 20, "Take action\nwith tools", "ACTION"),
    ("agentic", 1045, "Agentic AI", 20, "Pursue goals\nautonomously", "FULL AUTONOMY"),
]
for key, bx, name, nsize, tag, stage in BANDS:
    dark = LAYERS[key][4]
    T([bx - 72, 798, 144, 28], name, size=nsize, color=dark, weight=800,
      f="Space Grotesk")
    T([bx - 62, 850, 124, 36], tag, size=10.5, color=INK, weight=600, lh=1.25)
    if stage:
        T([bx - 62, 892, 124, 14], stage, size=9, color=dark, weight=700,
          ls="0.14em")

# progression arrows across the ring boundaries (between name and tagline rows)
for bxr in (555, 695, 835, 975):
    L.line([bxr - 30, 838], [bxr + 20, 838], **stroke(2.4, color=ARROW))
    L.polygon([[bxr + 32, 838], [bxr + 18, 832], [bxr + 18, 844]], fill=ARROW)

# ------------------------------------------------- title
SPAN_STYLE = {"font_family": "Space Grotesk", "font_size": 42, "font_weight": 700}
L.text([0, 50, W, 64],
       [{"text": "Agentic AI", "style": {**SPAN_STYLE, "color": "#B23324"}},
        {"text": " · A Complete Framework",
         "style": {**SPAN_STYLE, "color": "#22304A"}}],
       style={"font_family": "Space Grotesk", "size": 42, "weight": 700,
              "color": "#22304A", "align": "center"})
T([0, 112, W, 20],
  "Five nested capability layers — each ring builds on everything inside it",
  size=13.5, color=SUB, weight=500)

# ------------------------------------------------- callout boxes
def callout(x, y, w, title, lines, tint, edge):
    L.rect([x, y, w, 32], fill=tint, radius=8, **stroke(1.3, color=edge))
    T([x, y + 8, w, 18], title, size=13.5, color=INK, weight=700)
    bh = len(lines) * 22 + 14
    L.rect([x, y + 38, w, bh], fill="#FFFFFF", radius=8,
           **stroke(1, color="#D8D4C8"))
    L.bullet_list([x + 16, y + 48, w - 30, bh - 18], lines,
                  marker="•", marker_color=edge, gap=8,
                  style={"font_family": "Inter", "size": 10.5, "color": ITEM,
                         "weight": 500, "align": "left"})


callout(42, 252, 260, "Key Technologies",
        ["Attention Mechanisms", "Transfer Learning",
         "Large Language Models", "Transformers", "CNNs · RNNs & LSTMs"],
        "#F8E9C4", "#B7791F")
callout(858, 252, 260, "Agent Management",
        ["Task Scheduling", "Rollback Mechanisms",
         "Self-Improvement", "Feedback Loops & Evals"],
        "#DDEBD9", "#2F855A")
callout(42, 1252, 260, "Outputs & Interfaces",
        ["Code Generation", "Speech (ASR & TTS)",
         "Image & Video Generation", "Tool Calls & Structured Output"],
        "#EFE7D2", "#8C7B4F")
callout(858, 1252, 260, "Governance & Future",
        ["Safety Measures & Guardrails", "Regulatory Compliance",
         "Evaluations & Observability", "Human Oversight"],
        "#E4E8ED", "#4A5568")

# top-centre header pointing into the diagram
L.rect([445, 248, 270, 34], fill="#DCE7F5", radius=8, **stroke(1.3, color="#2B6CB0"))
T([445, 257, 270, 18], "Agent Capabilities", size=13.5, color=INK, weight=700)
L.line([580, 284], [592, 326], **stroke(2, color="#2B6CB0"))
L.polygon([[594, 333], [586, 323], [597, 321]], fill="#2B6CB0")

# ------------------------------------------------- footer
T([0, 1456, W, 16],
  "Each layer contains and extends the capabilities of every layer within it",
  size=10.5, color="#8A93A0", weight=500)
# author sign — @pedroanisio on X, as a live hyperlink (SVG/PDF <a>)
L.text([W - 322, 1454, 280, 18],
       [{"kind": "link", "href": "https://x.com/pedroanisio",
         "title": "@pedroanisio on X", "content": ["@pedroanisio"]}],
       style={"font_family": "Inter", "size": 10.5, "weight": 600,
              "color": "#4A5568", "align": "right"})


def build():
    return doc.build()
