"""Aura — a polished DESKTOP web app, authored with the FrameForge SDK.

Design brief: a calm desktop hub for your music, photos, and the people who
share them — recomposed for a 1512×964 desktop surface from a set of iOS
reference screens (Focus modes, "Shared with You", Listen Now, Photos search,
Messages). Every reference element reappears here as a native desktop control:

    · a persistent left navigation rail (deep-indigo glass)
    · a global AI search + focus/presence controls in the top bar
    · "Shared with You" media cards, a Photos-from-apps strip, Recently Played
    · a right rail: the Focus module (dark glass, like the reference), Messages,
      and the People sharing with you
    · a full-width Now-Playing bar

Eight surfaces ship — the same product flow the FrameForge Studio wireframe
(static/examples/build_wireframe_annotated.py) maps out, recomposed for Aura:

    1. Home        — the shared feed (primary surface)
    2. Photos      — search results across your apps
    3. Sign in     — split brand / auth panel        (≈ wireframe "Sign in")
    4. Sync run    — connect → scan → match pipeline  (≈ wireframe "Render run")
    5. Activity    — timeline + detail                (≈ wireframe "History")
    6. Viewer      — a public, read-only shared album (≈ wireframe "Viewer")
    7. Settings    — profile · connected apps · privacy (≈ wireframe "Settings")
    8. Sitemap     — the information architecture + journeys (≈ wireframe "Sitemap")

This is a pure FrameForge composition — vectors only, no external assets — so it
renders identically in the raster feedback loop and to SVG/PDF.

Provenance: generated by Claude Opus 4.8 via Claude Code (FrameForge SDK 2.4.1),
2026-07-03. UI concept and layout are original; the reference screens are an
Apple-ecosystem UX vocabulary (Focus, Shared with You, Listen Now, Photos).
"""
import os
from dataclasses import replace
from frameforge.sdk import DocumentBuilder, default_theme, avatar, pill, button, badge, field
from frameforge.sdk.validate import validate_static_rules

# --------------------------------------------------------------------------- #
#  Canvas geometry
# --------------------------------------------------------------------------- #
W, H = 1512, 964
SBW = 248                 # sidebar width
NAV_H = 88                # top-bar height (over the content area)
PLAYER_H = 84             # bottom now-playing bar
GUT = 28                  # outer gutter
RAILW = 340               # right rail width
CX0 = SBW + 40            # main content column x  (= 288)
RAILX = W - GUT - RAILW   # right rail x           (= 1144)
MAINW = (RAILX - GUT) - CX0   # main column width  (= 828)
TOP = NAV_H + 24          # content top            (= 112)
BOT = H - PLAYER_H - 24   # content bottom         (= 856)

# --------------------------------------------------------------------------- #
#  Palette — a calm, warm-cool light app with deep-glass accents
# --------------------------------------------------------------------------- #
BG      = "#F4F4F7"       # content canvas
CARD    = "#FFFFFF"
INK     = "#16171D"
SUB     = "#535A69"
MUTE    = "#8A909E"
FAINT   = "#B4B9C4"
LINE    = "#EDEEF2"
LINE2   = "#E3E5EB"
ACC     = "#6B5CFF"       # aura violet
ACCSOFT = "#EDEBFF"
GOOD    = "#25A56A"
WARN    = "#E8992E"
RED     = "#F0506E"
# sidebar / dark glass
SBMUTE  = "#A19DBE"
SBTXT   = "#E7E5F2"
FPILL   = "#2B2937"       # dark focus pill
FPILL2  = "#232130"
FTXT    = "#F3F2F8"
FMUTE   = "#9E9AB6"

def lin(angle, *stops):
    return {"kind": "linear", "angle": angle,
            "stops": [{"color": c, "position": p} for c, p in stops]}

AURA   = lin(125, ("#FF6FA3", "0%"), ("#B45CFF", "52%"), ("#4F8BFF", "100%"))
SB_G   = lin(155, ("#241D42", "0%"), ("#17122A", "100%"))
FOC_G  = lin(150, ("#252235", "0%"), ("#15131F", "100%"))
OCEAN  = lin(135, ("#4FA0FF", "0%"), ("#6B5CFF", "100%"))
SUNSET = lin(135, ("#FF9A5A", "0%"), ("#FF5E8A", "100%"))
DUSK   = lin(135, ("#9B6BFF", "0%"), ("#FF6FA3", "100%"))
MINT   = lin(135, ("#31D6AE", "0%"), ("#4F9BFF", "100%"))
CORAL  = lin(135, ("#FF7A6B", "0%"), ("#FF4FA0", "100%"))
SKY    = lin(160, ("#7EC8FF", "0%"), ("#4F8BFF", "55%"), ("#6B5CFF", "100%"))
CITY   = lin(160, ("#5B6BFF", "0%"), ("#8B5CFF", "100%"))
FOREST = lin(160, ("#3FD6A0", "0%"), ("#2FA6C9", "100%"))
GOLD   = lin(160, ("#FFC24F", "0%"), ("#FF7A5A", "100%"))

TH = replace(default_theme(), accent=ACC, accent_soft=ACCSOFT, ink=INK, sub=SUB,
             muted=MUTE, line=LINE2, fill="#F0F0F4", fill_alt="#E6E7ED",
             surface=CARD, surface_alt=BG, good=GOOD, warn=WARN, bad=RED, radius=12)

D = None   # current draw layer, set per page in build()

# --------------------------------------------------------------------------- #
#  Text + primitive helpers
# --------------------------------------------------------------------------- #
def T(x, y, w, s, *, size=13, color=INK, weight=None, align=None, spacing=None,
      caps=False, mono=False, valign="top", italic=False, h=None, lay=None):
    L = lay or D
    st = {"font_family": list(TH.mono if mono else TH.font), "font_size": size,
          "color": color, "vertical_align": valign}
    if weight is not None: st["font_weight"] = weight
    if align: st["text_align"] = align
    if spacing is not None: st["letter_spacing"] = spacing
    if caps: st["text_transform"] = "uppercase"
    if italic: st["font_style"] = "italic"
    L.text([x, y, w, h if h is not None else size * 1.4], s, style=st)

def soft(box, *, fill=CARD, radius=16, stroke=None, sw=1.0, blur=22, dy=6,
         sh="#141A2610", lay=None):
    L = lay or D
    f = {"fill": fill, "radius": radius}
    if stroke: f["stroke"] = stroke; f["stroke_style"] = {"stroke_width": sw}
    if blur: f["shadow"] = {"dx": 0, "dy": dy, "blur": blur, "color": sh}
    L.rect(box, **f)

# --------------------------------------------------------------------------- #
#  Icon set — small vector glyphs, drawn centred at (cx, cy)
# --------------------------------------------------------------------------- #
def ic(name, cx, cy, col=INK, *, s=8.0, sw=1.7, fillcol=None, lay=None):
    L = lay or D
    ss = {"stroke_width": sw, "stroke_linecap": "round", "stroke_linejoin": "round"}
    def ln(a, b): L.line(a, b, stroke=col, stroke_style=ss)
    def pth(pts, fill="none", stc=None): L.path(pts, stroke=stc or col, fill=fill,
                                                stroke_style=ss)
    def cir(px, py, r, f="none", stc=None, w=sw):
        L.circle([px, py], r, fill=f, stroke=(stc or col) if f == "none" else "none",
                 stroke_style={"stroke_width": w})
    if name == "home":
        pth([("M", cx - s, cy + s * 0.15), ("L", cx, cy - s), ("L", cx + s, cy + s * 0.15)])
        pth([("M", cx - s * 0.66, cy - s * 0.15), ("L", cx - s * 0.66, cy + s),
             ("L", cx + s * 0.66, cy + s), ("L", cx + s * 0.66, cy - s * 0.15)])
    elif name == "music":
        L.circle([cx - s * 0.35, cy + s * 0.62], s * 0.4, fill=col)
        L.circle([cx + s * 0.7, cy + s * 0.32], s * 0.4, fill=col)
        ln([cx - s * 0.35 + s * 0.4, cy + s * 0.62], [cx - s * 0.35 + s * 0.4, cy - s * 0.85])
        ln([cx + s * 0.7 + s * 0.4, cy + s * 0.32], [cx + s * 0.7 + s * 0.4, cy - s * 1.05])
        ln([cx - s * 0.35 + s * 0.4, cy - s * 0.85], [cx + s * 0.7 + s * 0.4, cy - s * 1.05])
    elif name == "photo":
        L.rect([cx - s, cy - s * 0.78, 2 * s, 1.56 * s], fill="none", stroke=col,
               stroke_style=ss, radius=2.5)
        cir(cx - s * 0.34, cy - s * 0.16, s * 0.24, f=col)
        pth([("M", cx - s * 0.85, cy + s * 0.62), ("L", cx - s * 0.1, cy - s * 0.05),
             ("L", cx + s * 0.35, cy + s * 0.32), ("L", cx + s * 0.85, cy - s * 0.12)])
    elif name == "share":
        cir(cx - s * 0.6, cy, s * 0.34, f=col)
        cir(cx + s * 0.55, cy - s * 0.6, s * 0.34, f=col)
        cir(cx + s * 0.55, cy + s * 0.6, s * 0.34, f=col)
        ln([cx - s * 0.34, cy - s * 0.16], [cx + s * 0.28, cy - s * 0.5])
        ln([cx - s * 0.34, cy + s * 0.16], [cx + s * 0.28, cy + s * 0.5])
    elif name == "people":
        cir(cx - s * 0.5, cy - s * 0.35, s * 0.42, f=col)
        cir(cx + s * 0.55, cy - s * 0.35, s * 0.42, f=col)
        pth([("M", cx - s * 1.15, cy + s), ("Q", cx - s * 0.5, cy + s * 0.15, cx + s * 0.05, cy + s * 0.55)], stc=col)
        pth([("M", cx - s * 0.15, cy + s * 0.55), ("Q", cx + s * 0.55, cy + s * 0.15, cx + s * 1.2, cy + s)], stc=col)
    elif name == "search":
        cir(cx - s * 0.2, cy - s * 0.2, s * 0.62, w=sw)
        ln([cx + s * 0.28, cy + s * 0.28], [cx + s * 0.9, cy + s * 0.9])
    elif name == "sparkle":
        pth([("M", cx, cy - s), ("Q", cx + s * 0.18, cy - s * 0.18, cx + s, cy),
             ("Q", cx + s * 0.18, cy + s * 0.18, cx, cy + s),
             ("Q", cx - s * 0.18, cy + s * 0.18, cx - s, cy),
             ("Q", cx - s * 0.18, cy - s * 0.18, cx, cy - s), ("Z",)], fill=col, stc="none")
        L.circle([cx + s * 0.95, cy - s * 0.85], s * 0.2, fill=col)
    elif name == "bell":
        pth([("M", cx - s * 0.75, cy + s * 0.45), ("Q", cx - s * 0.75, cy - s * 0.7, cx, cy - s * 0.85),
             ("Q", cx + s * 0.75, cy - s * 0.7, cx + s * 0.75, cy + s * 0.45), ("Z",)])
        ln([cx - s, cy + s * 0.45], [cx + s, cy + s * 0.45])
        L.circle([cx, cy + s * 0.85], s * 0.2, fill=col)
    elif name == "heart":
        pth([("M", cx, cy + s * 0.78), ("C", cx - s * 1.25, cy - s * 0.1, cx - s * 0.55, cy - s * 0.95, cx, cy - s * 0.2),
             ("C", cx + s * 0.55, cy - s * 0.95, cx + s * 1.25, cy - s * 0.1, cx, cy + s * 0.78), ("Z",)],
            fill=(fillcol or "none"), stc=col)
    elif name == "play":
        L.path([("M", cx - s * 0.55, cy - s * 0.8), ("L", cx + s * 0.85, cy), ("L", cx - s * 0.55, cy + s * 0.8), ("Z",)],
               fill=col, stroke="none")
    elif name == "pause":
        L.rect([cx - s * 0.6, cy - s * 0.8, s * 0.42, s * 1.6], fill=col, radius=1.5)
        L.rect([cx + s * 0.18, cy - s * 0.8, s * 0.42, s * 1.6], fill=col, radius=1.5)
    elif name == "prev":
        L.rect([cx - s, cy - s * 0.75, s * 0.28, s * 1.5], fill=col, radius=1)
        L.path([("M", cx + s * 0.9, cy - s * 0.75), ("L", cx - s * 0.35, cy), ("L", cx + s * 0.9, cy + s * 0.75), ("Z",)], fill=col, stroke="none")
    elif name == "next":
        L.rect([cx + s * 0.72, cy - s * 0.75, s * 0.28, s * 1.5], fill=col, radius=1)
        L.path([("M", cx - s * 0.9, cy - s * 0.75), ("L", cx + s * 0.35, cy), ("L", cx - s * 0.9, cy + s * 0.75), ("Z",)], fill=col, stroke="none")
    elif name == "shuffle":
        ln([cx - s, cy - s * 0.6], [cx - s * 0.2, cy - s * 0.6]); pth([("M", cx - s * 0.2, cy - s * 0.6), ("L", cx + s, cy + s * 0.6)])
        pth([("M", cx + s * 0.55, cy + s * 0.2), ("L", cx + s, cy + s * 0.6), ("L", cx + s * 0.6, cy + s)])
        ln([cx - s, cy + s * 0.6], [cx - s * 0.2, cy + s * 0.6]); pth([("M", cx - s * 0.2, cy + s * 0.6), ("L", cx + s * 0.35, cy - s * 0.1)])
    elif name == "repeat":
        pth([("M", cx - s * 0.7, cy + s * 0.55), ("Q", cx - s, cy + s * 0.55, cx - s, cy),
             ("Q", cx - s, cy - s * 0.7, cx - s * 0.2, cy - s * 0.7), ("L", cx + s * 0.7, cy - s * 0.7)])
        pth([("M", cx + s * 0.3, cy - s * 1.1), ("L", cx + s * 0.8, cy - s * 0.7), ("L", cx + s * 0.3, cy - s * 0.3)])
        pth([("M", cx + s * 0.7, cy - s * 0.55), ("Q", cx + s, cy - s * 0.55, cx + s, cy),
             ("Q", cx + s, cy + s * 0.7, cx + s * 0.2, cy + s * 0.7), ("L", cx - s * 0.7, cy + s * 0.7)])
        pth([("M", cx - s * 0.3, cy + s * 1.1), ("L", cx - s * 0.8, cy + s * 0.7), ("L", cx - s * 0.3, cy + s * 0.3)])
    elif name == "moon":
        L.circle([cx, cy], s, fill=col)
        L.circle([cx + s * 0.5, cy - s * 0.42], s * 0.92, fill=(fillcol or FPILL))
    elif name == "user":
        L.circle([cx, cy - s * 0.4], s * 0.46, fill=col)
        L.path([("M", cx - s * 0.85, cy + s), ("Q", cx - s * 0.85, cy + s * 0.15, cx, cy + s * 0.15),
                ("Q", cx + s * 0.85, cy + s * 0.15, cx + s * 0.85, cy + s), ("Z",)], fill=col, stroke="none")
    elif name == "briefcase":
        L.rect([cx - s, cy - s * 0.25, 2 * s, 1.25 * s], fill=col, radius=2.5)
        L.rect([cx - s * 0.42, cy - s * 0.72, s * 0.84, s * 0.5], fill="none", stroke=col,
               stroke_style={"stroke_width": sw}, radius=1.5)
        L.rect([cx - s, cy + s * 0.05, 2 * s, s * 0.2], fill=(fillcol or FPILL))
    elif name == "bed":
        ln([cx - s, cy - s * 0.4], [cx - s, cy + s * 0.7])
        pth([("M", cx - s, cy + s * 0.15), ("L", cx - s, cy - s * 0.2), ("Q", cx - s, cy - s * 0.45, cx - s * 0.6, cy - s * 0.45),
             ("L", cx + s, cy - s * 0.45), ("Q", cx + s * 0.6, cy - s * 0.45, cx + s * 0.6, cy - s * 0.05)])
        L.rect([cx - s, cy + s * 0.05, 2 * s, s * 0.42], fill=col, radius=2)
        ln([cx + s, cy + s * 0.05], [cx + s, cy + s * 0.7])
        L.circle([cx - s * 0.5, cy - s * 0.16], s * 0.22, fill=col)
    elif name == "run":
        L.circle([cx + s * 0.35, cy - s * 0.72], s * 0.3, fill=col)
        pth([("M", cx - s * 0.9, cy + s * 0.1), ("L", cx - s * 0.1, cy - s * 0.15), ("L", cx + s * 0.5, cy + s * 0.2)])
        pth([("M", cx - s * 0.1, cy - s * 0.15), ("L", cx + s * 0.05, cy + s), ("L", cx + s * 0.7, cy + s)])
        pth([("M", cx + s * 0.5, cy + s * 0.2), ("L", cx + s * 0.95, cy - s * 0.15)])
    elif name == "plus":
        ln([cx - s * 0.8, cy], [cx + s * 0.8, cy]); ln([cx, cy - s * 0.8], [cx, cy + s * 0.8])
    elif name == "more":
        for dx in (-s * 0.7, 0, s * 0.7): L.circle([cx + dx, cy], s * 0.2, fill=col)
    elif name == "grid":
        for gx in (-1, 1):
            for gy in (-1, 1):
                L.rect([cx + gx * s * 0.62 - s * 0.42, cy + gy * s * 0.62 - s * 0.42, s * 0.84, s * 0.84],
                       fill="none", stroke=col, stroke_style={"stroke_width": sw}, radius=1.5)
    elif name == "chev":
        pth([("M", cx - s * 0.35, cy - s * 0.6), ("L", cx + s * 0.35, cy), ("L", cx - s * 0.35, cy + s * 0.6)])
    elif name == "chevd":
        pth([("M", cx - s * 0.6, cy - s * 0.3), ("L", cx, cy + s * 0.35), ("L", cx + s * 0.6, cy - s * 0.3)])
    elif name == "queue":
        for i, wl in enumerate((1.0, 0.72, 1.0)):
            ln([cx - s, cy - s * 0.6 + i * s * 0.6], [cx - s + 2 * s * wl, cy - s * 0.6 + i * s * 0.6])
    elif name == "volume":
        L.path([("M", cx - s, cy - s * 0.35), ("L", cx - s * 0.4, cy - s * 0.35), ("L", cx + s * 0.15, cy - s * 0.85),
                ("L", cx + s * 0.15, cy + s * 0.85), ("L", cx - s * 0.4, cy + s * 0.35), ("L", cx - s, cy + s * 0.35), ("Z",)],
               fill=col, stroke="none")
        pth([("M", cx + s * 0.5, cy - s * 0.45), ("Q", cx + s * 0.9, cy, cx + s * 0.5, cy + s * 0.45)])
    elif name == "device":
        L.rect([cx - s * 0.9, cy - s * 0.7, 1.8 * s, 1.2 * s], fill="none", stroke=col,
               stroke_style={"stroke_width": sw}, radius=2)
        ln([cx - s * 0.35, cy + s * 0.85], [cx + s * 0.35, cy + s * 0.85])
    elif name == "expand":
        pth([("M", cx - s * 0.3, cy - s), ("L", cx - s, cy - s), ("L", cx - s, cy - s * 0.3)])
        pth([("M", cx + s * 0.3, cy + s), ("L", cx + s, cy + s), ("L", cx + s, cy + s * 0.3)])
    elif name == "pin":
        pth([("M", cx, cy + s), ("Q", cx - s * 0.85, cy - s * 0.1, cx, cy - s), ("Q", cx + s * 0.85, cy - s * 0.1, cx, cy + s), ("Z",)],
            fill=col, stc="none")
        L.circle([cx, cy - s * 0.25], s * 0.3, fill=(fillcol or CARD))
    elif name == "clock":
        cir(cx, cy, s * 0.92)
        ln([cx, cy], [cx, cy - s * 0.5]); ln([cx, cy], [cx + s * 0.42, cy + s * 0.12])

def grad_avatar(cx, cy, r, grad, initial, tsize=None, lay=None):
    L = lay or D
    L.circle([cx, cy], r, fill=grad)
    if initial:
        T(cx - r, cy - (tsize or r * 0.62) * 0.62, 2 * r, initial, size=tsize or r * 0.85,
          color="#FFFFFF", weight=800, align="center", valign="middle", h=2 * r * 0.62, lay=L)

def section_header(x, y, w, title, action=None, lay=None):
    T(x, y, w - 120, title, size=16.5, weight=800, color=INK, lay=lay)
    if action:
        T(x + w - 150, y + 2, 150, action, size=12, weight=700, color=ACC, align="right", lay=lay)

def scene(x, y, w, h, grad, kind, radius=14, lay=None):
    """A photo-like tile: gradient ground + a tiny vector scene, clipped feel."""
    L = lay or D
    L.rect([x, y, w, h], fill=grad, radius=radius)
    cxm = x + w / 2
    if kind == "sky":
        L.circle([x + w * 0.74, y + h * 0.3], min(w, h) * 0.14, fill="#FFFFFF", fill_opacity=0.85)
        L.path([("M", x, y + h), ("L", x + w * 0.34, y + h * 0.52), ("L", x + w * 0.58, y + h * 0.74),
                ("L", x + w * 0.8, y + h * 0.5), ("L", x + w, y + h * 0.72), ("L", x + w, y + h), ("Z",)],
               fill="#FFFFFF", fill_opacity=0.22, stroke="none")
    elif kind == "city":
        for i, (bx, bh) in enumerate([(0.1, 0.4), (0.26, 0.62), (0.44, 0.32), (0.6, 0.55), (0.78, 0.44)]):
            L.rect([x + w * bx, y + h * (1 - bh), w * 0.13, h * bh], fill="#FFFFFF", fill_opacity=0.2, radius=1)
    elif kind == "forest":
        for bx in (0.22, 0.44, 0.66):
            L.path([("M", x + w * bx, y + h * 0.85), ("L", x + w * (bx + 0.09), y + h * 0.4),
                    ("L", x + w * (bx + 0.18), y + h * 0.85), ("Z",)], fill="#FFFFFF", fill_opacity=0.24, stroke="none")
    elif kind == "gold":
        L.circle([cxm, y + h * 0.42], min(w, h) * 0.2, fill="#FFFFFF", fill_opacity=0.32)
        L.rect([x, y + h * 0.66, w, h * 0.34], fill="#000000", fill_opacity=0.08)
    elif kind == "vinyl":
        L.circle([cxm, y + h / 2], min(w, h) * 0.34, fill="#FFFFFF", fill_opacity=0.18)
        L.circle([cxm, y + h / 2], min(w, h) * 0.1, fill="#FFFFFF", fill_opacity=0.5)

def photo_tag(x0, y0, tw, thh, label, lay=None):
    """A readable location chip (dark scrim) at the bottom-left of a photo tile."""
    L = lay or D
    chw = 26 + 7.0 * len(label)
    L.rect([x0 + 10, y0 + thh - 30, chw, 22], fill="#000000", fill_opacity=0.36, radius=11)
    ic("pin", x0 + 23, y0 + thh - 19, "#FFFFFF", s=5, sw=1.4, lay=L)
    T(x0 + 34, y0 + thh - 30, chw - 26, label, size=11, color="#FFFFFF", weight=700,
      valign="middle", h=22, lay=L)

# --------------------------------------------------------------------------- #
#  Chrome: sidebar, top bar, player — shared across surfaces
# --------------------------------------------------------------------------- #
NAV = [("home", "Home"), ("music", "Listen"), ("photo", "Photos"),
       ("share", "Shared with You"), ("people", "People")]

def sidebar(active="home"):
    D.rect([0, 0, SBW, H], fill=SB_G)
    # brand
    D.rect([28, 32, 36, 36], fill=AURA, radius=11)
    D.circle([28 + 18, 32 + 18], 9.5, fill="none", stroke="#FFFFFF", stroke_style={"stroke_width": 2.2})
    D.circle([28 + 18, 32 + 18], 3.2, fill="#FFFFFF")
    T(76, 40, 150, "Aura", size=20, color="#FFFFFF", weight=800)
    # nav
    ny = 116
    for name, label in NAV:
        on = name == active
        if on:
            D.rect([16, ny - 6, SBW - 32, 44], fill="#FFFFFF", fill_opacity=0.10, radius=13)
            D.rect([16, ny + 2, 3, 24], fill=AURA, radius=2)
        col = "#FFFFFF" if on else SBMUTE
        ic(name, 42, ny + 16, col, s=9, sw=1.9)
        T(66, ny + 8, 170, label, size=13.5, color=col, weight=700 if on else 500,
          valign="middle", h=20)
        ny += 52
    # library
    D.rect([28, ny + 6, SBW - 56, 1], fill="#FFFFFF", fill_opacity=0.09)
    T(28, ny + 22, 180, "Your library", size=10, color=SBMUTE, weight=700, spacing=1.4, caps=True)
    libs = [("Liked Songs", SUNSET), ("San Francisco '24", OCEAN),
            ("Focus Flow", MINT), ("Shared albums", DUSK)]
    ly = ny + 46
    for nm, g in libs:
        D.rect([28, ly + 1, 11, 11], fill=g, radius=3)
        T(50, ly - 1, 180, nm, size=12.5, color=SBTXT, weight=500, valign="middle", h=14)
        ly += 32
    # user chip
    uy = H - 74
    D.rect([16, uy, SBW - 32, 54], fill="#FFFFFF", fill_opacity=0.07, radius=15)
    grad_avatar(28 + 17, uy + 27, 17, OCEAN, "P", tsize=14)
    T(60, uy + 12, 140, "Pedro Silva", size=12.5, color="#FFFFFF", weight=700, h=14)
    T(60, uy + 29, 140, "Premium", size=10.5, color=SBMUTE, weight=600, h=12)
    ic("more", SBW - 34, uy + 27, SBMUTE, s=6.5)

def topbar(*, mode="search", search_value=None, crumb=None):
    if mode == "search":
        # search field
        sx, sw = CX0, 496
        soft([sx, 24, sw, 42], radius=21, stroke=LINE2, sw=1, blur=12, dy=2, sh="#141A2609")
        ic("search", sx + 22, 45, MUTE, s=7.4, sw=1.8)
        if search_value:
            T(sx + 40, 24, sw - 120, search_value, size=13.5, color=INK, weight=600, valign="middle", h=42)
        else:
            T(sx + 40, 24, sw - 120, "Search music, photos, people…", size=13.5, color=MUTE,
              valign="middle", h=42)
        D.rect([sx + sw - 68, 31, 54, 28], fill=ACCSOFT, radius=14)
        ic("sparkle", sx + sw - 52, 45, ACC, s=5.6)
        T(sx + sw - 42, 24, 30, "AI", size=11.5, color=ACC, weight=800, valign="middle", h=42)
    else:
        cw = 46 + 7.2 * len(crumb or "")
        soft([CX0, 24, cw, 40], radius=20, stroke=LINE2, sw=1, blur=0)
        ic("home", CX0 + 22, 44, MUTE, s=6.5, sw=1.6)
        T(CX0 + 38, 24, cw - 50, crumb or "", size=12.5, color=SUB, weight=600, valign="middle", h=40)
    # right cluster (from the right edge)
    avx = W - GUT - 40
    grad_avatar(avx + 20, 24 + 20, 20, OCEAN, "P", tsize=15)
    D.circle([avx + 36, 24 + 34], 5, fill=GOOD, stroke=CARD, stroke_style={"stroke_width": 2})
    # bell button
    belx = avx - 16 - 40
    soft([belx, 24, 40, 40], radius=13, stroke=LINE2, sw=1, blur=10, dy=2, sh="#141A2608")
    ic("bell", belx + 20, 43, SUB, s=7.5, sw=1.6)
    D.circle([belx + 27, 32], 4, fill=RED, stroke=CARD, stroke_style={"stroke_width": 1.6})
    # focus status pill
    fpw = 158
    fpx = belx - 14 - fpw
    soft([fpx, 24, fpw, 40], radius=20, stroke=LINE2, sw=1, blur=10, dy=2, sh="#141A2608")
    D.circle([fpx + 20, 44], 9, fill=ACCSOFT)
    ic("user", fpx + 20, 44, ACC, s=5.2, sw=1.5)
    T(fpx + 36, 24, fpw - 60, "Focus · Personal", size=12.5, color=INK, weight=700, valign="middle", h=40)
    ic("chevd", fpx + fpw - 18, 44, MUTE, s=5, sw=1.6)

def player():
    py = H - PLAYER_H
    D.rect([SBW, py, W - SBW, PLAYER_H], fill=CARD)
    D.rect([SBW, py, W - SBW, 1], fill=LINE2)
    D.rect([SBW, py, W - SBW, 6], fill="#141A2606")  # faint top shade
    # left — now playing
    D.rect([CX0, py + 14, 56, 56], fill=OCEAN, radius=12)
    scene(CX0, py + 14, 56, 56, OCEAN, "vinyl", radius=12)
    T(CX0 + 70, py + 22, 190, "Phoenix", size=13.5, weight=700, color=INK, h=18)
    T(CX0 + 70, py + 43, 190, "Charlotte Cardin", size=11.5, color=MUTE, h=14)
    ic("heart", CX0 + 290, py + 42, ACC, s=7.5, sw=1.7, fillcol=ACC)
    # centre — transport
    c = (SBW + W) / 2
    ic("shuffle", c - 100, py + 30, MUTE, s=7.5, sw=1.6)
    ic("prev", c - 54, py + 30, INK, s=7.5)
    D.circle([c, py + 30], 20, fill=INK)
    ic("play", c + 1.5, py + 30, "#FFFFFF", s=7)
    ic("next", c + 54, py + 30, INK, s=7.5)
    ic("repeat", c + 100, py + 30, MUTE, s=7.5, sw=1.6)
    # progress
    T(c - 152, py + 52, 34, "1:42", size=10.5, color=MUTE, align="right", h=12, valign="middle")
    D.rect([c - 110, py + 56, 220, 4], fill=LINE2, radius=2)
    D.rect([c - 110, py + 56, 220 * 0.46, 4], fill=INK, radius=2)
    D.circle([c - 110 + 220 * 0.46, py + 58], 5.5, fill=INK)
    T(c + 118, py + 52, 34, "3:45", size=10.5, color=MUTE, h=12, valign="middle")
    # right controls
    rx = W - GUT - 12
    ic("expand", rx, py + 30, MUTE, s=7, sw=1.6); rx -= 34
    D.rect([rx - 72, py + 28, 72, 4], fill=LINE2, radius=2)
    D.rect([rx - 72, py + 28, 72 * 0.7, 4], fill=SUB, radius=2)
    D.circle([rx - 72 + 72 * 0.7, py + 30], 5, fill=SUB)
    rx -= 84
    ic("volume", rx, py + 30, MUTE, s=7, sw=1.6); rx -= 32
    ic("device", rx, py + 30, MUTE, s=7, sw=1.6); rx -= 32
    ic("queue", rx, py + 30, MUTE, s=7, sw=1.6)

# --------------------------------------------------------------------------- #
#  SURFACE 1 — Home dashboard
# --------------------------------------------------------------------------- #
SHARED = [
    ("Phoenix", "Charlotte Cardin", "Adam", "AD", OCEAN, "sky"),
    ("Sundial", "Halcyon Bay", "2 contacts", "+2", SUNSET, "gold"),
    ("Golden Hour", "Marlowe", "Ashley", "AS", DUSK, "vinyl"),
]
PHOTOS = [("San Francisco", SKY, "sky"), ("Bay Bridge", CITY, "city"),
          ("Muir Woods", FOREST, "forest"), ("Sunset District", GOLD, "gold")]
RECENT = [("Neon Skyline", "Vega", CITY, "city"), ("Paper Boats", "Lull", MINT, "vinyl"),
          ("Afterglow", "Marlowe", SUNSET, "gold"), ("Deep Field", "Vela", OCEAN, "sky"),
          ("Ember", "Halcyon Bay", CORAL, "vinyl")]
FOCUS = [("moon", "Do Not Disturb", "Off", False, None),
         ("user", "Personal", "On · until 6 PM", True, AURA),
         ("briefcase", "Work", "Off", False, None),
         ("bed", "Sleep", "Starts 10:30 PM", False, None)]
PEOPLE = [("Ann Li", "shared 12 photos", "2m", CORAL, "AL"),
          ("Joey Smith", "shared a playlist", "18m", OCEAN, "JS"),
          ("Sanaa Aridi", "shared 5 photos", "1h", MINT, "SA")]

def home():
    D.rect([0, 0, W, H], fill=BG)
    sidebar("home")
    topbar()
    # greeting
    T(CX0, 104, 640, "Good afternoon, Pedro", size=26, weight=800, color=INK, h=34)
    T(CX0, 142, 640, "Here's what your people shared with you today.", size=13.5, color=SUB, h=18)

    # --- Shared with You ---
    sy = 182
    section_header(CX0, sy, MAINW, "Shared with You", "See all →")
    cy = sy + 32
    cw = (MAINW - 2 * 20) / 3
    ch = 196
    for i, (title, artist, who, ini, g, kind) in enumerate(SHARED):
        x0 = CX0 + i * (cw + 20)
        soft([x0, cy, cw, ch], radius=18)
        scene(x0 + 14, cy + 14, cw - 28, 110, g, kind, radius=12)
        D.circle([x0 + cw - 32, cy + 108], 15, fill="#FFFFFF", fill_opacity=0.92,
                 shadow={"dx": 0, "dy": 2, "blur": 6, "color": "#0000002E"})
        ic("play", x0 + cw - 30, cy + 108, INK, s=5.5)
        T(x0 + 16, cy + 134, cw - 32, title, size=14, weight=700, color=INK, h=18)
        T(x0 + 16, cy + 153, cw - 32, artist, size=11.5, color=MUTE, h=14)
        # "from" chip
        D.rect([x0 + 14, cy + 172, 12 + 9 * len(who) + 30, 20], fill="#F0F0F4", radius=10)
        grad_avatar(x0 + 24, cy + 182, 8, g, ini[:2] if ini.startswith("+") else ini[0], tsize=8)
        T(x0 + 36, cy + 172, cw - 60, "From " + who, size=10.5, color=SUB, weight=600, valign="middle", h=20)

    # --- Photos from your apps ---
    py2 = cy + ch + 30
    section_header(CX0, py2, MAINW, "Photos from your Apps", "Search in app →")
    gy = py2 + 32
    cols = 4
    gap = 16
    tw = (MAINW - (cols - 1) * gap) / cols
    thh = 132
    for i, (label, g, kind) in enumerate(PHOTOS):
        x0 = CX0 + i * (tw + gap)
        scene(x0, gy, tw, thh, g, kind, radius=14)
        photo_tag(x0, gy, tw, thh, label)

    # --- Recently played ---
    ry = gy + thh + 30
    section_header(CX0, ry, MAINW, "Recently Played", "See all →")
    ay = ry + 32
    aw = 118
    agap = (MAINW - 5 * aw) / 4
    for i, (title, artist, g, kind) in enumerate(RECENT):
        x0 = CX0 + i * (aw + agap)
        scene(x0, ay, aw, aw, g, kind, radius=14)
        D.circle([x0 + aw - 22, ay + aw - 22, ], 15, fill="#FFFFFF", fill_opacity=0.92,
                 shadow={"dx": 0, "dy": 2, "blur": 6, "color": "#0000002E"})
        ic("play", x0 + aw - 20, ay + aw - 22, INK, s=5.5)
        T(x0 + 2, ay + aw + 8, aw - 4, title, size=12.5, weight=700, color=INK, h=16)
        T(x0 + 2, ay + aw + 26, aw - 4, artist, size=11, color=MUTE, h=14)

    right_rail()
    player()

def right_rail():
    # --- Focus module (dark glass) ---
    fx, fy, fw, fh = RAILX, TOP, RAILW, 396
    D.rect([fx, fy, fw, fh], fill=FOC_G, radius=22,
           shadow={"dx": 0, "dy": 10, "blur": 30, "color": "#14122633"})
    # mode dots
    modes = [("moon", OCEAN), ("user", DUSK), ("run", MINT), ("bed", SUNSET)]
    for i, (nm, g) in enumerate(modes):
        mx = fx + 24 + i * 34
        D.circle([mx + 12, fy + 30], 13, fill=g)
        ic(nm, mx + 12, fy + 30, "#FFFFFF", s=5.6, sw=1.5, fillcol=None)
    ic("more", fx + fw - 30, fy + 30, FMUTE, s=6)
    T(fx + 24, fy + 58, fw - 48, "Find Focus in the Day", size=17, weight=800, color=FTXT, h=22)
    T(fx + 24, fy + 84, fw - 48, "Silence alerts and share when you're free.",
      size=11.5, color=FMUTE, h=30)
    # pills
    py = fy + 116
    ph = 52
    for name, label, status, on, g in FOCUS:
        soft([fx + 20, py, fw - 40, ph], fill=("#FFFFFF" if on else FPILL),
             radius=15, blur=0)
        tint = INK if on else FTXT
        subt = SUB if on else FMUTE
        # icon square
        if on:
            D.rect([fx + 32, py + 10, 32, 32], fill=g, radius=10)
            ic(name, fx + 48, py + 26, "#FFFFFF", s=6.6, sw=1.6, fillcol=None)
        else:
            D.rect([fx + 32, py + 10, 32, 32], fill=FPILL2, radius=10)
            ic(name, fx + 48, py + 26, FTXT, s=6.6, sw=1.6, fillcol=FPILL2)
        T(fx + 76, py + 9, fw - 150, label, size=13, weight=700, color=tint, h=16)
        T(fx + 76, py + 27, fw - 150, status, size=10.5, color=subt, h=13)
        ic("more", fx + fw - 40, py + 26, subt, s=5.5)
        py += ph + 8
    # add a focus
    D.rect([fx + 20, py + 2, fw - 40, 32], fill="none", stroke=FMUTE,
           stroke_style={"stroke_width": 1.2, "stroke_dasharray": [5, 4]}, radius=12)
    T(fx + 20, py + 2, fw - 40, "＋  Add a focus", size=12, color=FMUTE, weight=700,
      align="center", valign="middle", h=32)

    # --- Messages ---
    mx, my, mw, mh = RAILX, TOP + 396 + 20, RAILW, 128
    soft([mx, my, mw, mh], radius=18)
    T(mx + 20, my + 16, mw - 80, "Messages", size=14.5, weight=800, color=INK, h=18)
    D.rect([mx + mw - 44, my + 15, 24, 20], fill=ACCSOFT, radius=8)
    T(mx + mw - 44, my + 15, 24, "2", size=11, color=ACC, weight=800, align="center", valign="middle", h=20)
    grad_avatar(mx + 32, my + 62, 15, CORAL, "AN", tsize=11)
    T(mx + 56, my + 48, mw - 76, "Ananya", size=12, weight=700, color=INK, h=14)
    T(mx + mw - 62, my + 48, 44, "9:14 AM", size=9.5, color=MUTE, align="right", h=14)
    T(mx + 56, my + 66, mw - 76, "Send me the SF photos when you're done sorting!",
      size=11.5, color=SUB, h=32)

    # --- People sharing with you ---
    sx, syy, swi = RAILX, TOP + 396 + 20 + 128 + 20, RAILW
    sh_ = BOT - syy
    soft([sx, syy, swi, sh_], radius=18)
    T(sx + 20, syy + 16, swi - 40, "Sharing with You", size=14.5, weight=800, color=INK, h=18)
    T(sx + swi - 70, syy + 18, 50, "See all", size=11, color=ACC, weight=700, align="right", h=14)
    ry2 = syy + 48
    for name, act, when, g, ini in PEOPLE:
        grad_avatar(sx + 34, ry2 + 16, 17, g, ini, tsize=12)
        T(sx + 60, ry2 + 4, swi - 120, name, size=12.5, weight=700, color=INK, h=15)
        T(sx + 60, ry2 + 21, swi - 120, act, size=10.5, color=MUTE, h=13)
        T(sx + swi - 54, ry2 + 8, 38, when, size=10, color=FAINT, align="right", h=13)
        ry2 += 44

# --------------------------------------------------------------------------- #
#  SURFACE 2 — Photos search results
# --------------------------------------------------------------------------- #
SUGGEST = ["photos san francisco bay", "photos san francisco golden gate bridge",
           "photos san francisco skyline"]
GRID = [("Golden Gate", SKY, "sky"), ("Downtown", CITY, "city"), ("Coastline", FOREST, "forest"),
        ("Painted Ladies", GOLD, "gold"), ("Bay Bridge", OCEAN, "city"), ("Twin Peaks", DUSK, "sky"),
        ("Presidio", MINT, "forest"), ("Ferry Building", SUNSET, "gold")]
RELATED = ["san francisco bay area", "san francisco silicon valley",
           "san francisco tourism", "san francisco at night"]

def photos_search():
    D.rect([0, 0, W, H], fill=BG)
    sidebar("photo")
    topbar(search_value="photos san francisco")
    # results header
    T(CX0, 104, 700, "Photos", size=26, weight=800, color=INK, h=34)
    T(CX0, 142, 700, "128 results for “photos san francisco”", size=13.5, color=SUB, h=18)
    # filter chips
    fy = 172
    fx = CX0
    for i, (lab, on) in enumerate([("All", True), ("This app", False), ("Shared with You", False),
                                    ("People", False), ("Places", False)]):
        wch = 22 + 8.4 * len(lab)
        D.rect([fx, fy, wch, 30], fill=(ACC if on else CARD),
               stroke=(None if on else LINE2), stroke_style=None if on else {"stroke_width": 1},
               radius=15)
        T(fx, fy, wch, lab, size=12, color=("#FFFFFF" if on else SUB), weight=700,
          align="center", valign="middle", h=30)
        fx += wch + 10

    # --- left: results grid ---
    gy = fy + 46
    section_header(CX0, gy, MAINW, "Photos from your Apps", "Show more →")
    gy2 = gy + 32
    cols, gap = 4, 16
    tw = (MAINW - (cols - 1) * gap) / cols
    thh = 150
    for i, (label, g, kind) in enumerate(GRID):
        col = i % cols
        row = i // cols
        x0 = CX0 + col * (tw + gap)
        y0 = gy2 + row * (thh + 16)
        scene(x0, y0, tw, thh, g, kind, radius=14)
        photo_tag(x0, y0, tw, thh, label)
    # related searches
    rely = gy2 + 2 * (thh + 16) + 8
    T(CX0, rely, MAINW, "Related searches", size=14, weight=800, color=INK, h=18)
    ry = rely + 28
    rxx = CX0
    for lab in RELATED:
        wch = 44 + 7.2 * len(lab)
        soft([rxx, ry, wch, 34], radius=17, stroke=LINE2, sw=1, blur=0)
        ic("search", rxx + 18, ry + 17, ACC, s=6, sw=1.6)
        T(rxx + 32, ry, wch - 40, lab, size=12, color=SUB, weight=600, valign="middle", h=34)
        rxx += wch + 12
        if rxx > CX0 + MAINW - 200:
            rxx = CX0
            ry += 44

    # --- right rail: search suggestions + a shared message ---
    # suggestions card
    sx, sy, swi = RAILX, TOP, RAILW
    sug_h = 40 + len(SUGGEST) * 44 + 16
    soft([sx, sy, swi, sug_h], radius=18)
    T(sx + 20, sy + 16, swi - 40, "Suggestions", size=14.5, weight=800, color=INK, h=18)
    yy = sy + 46
    # top exact suggestion highlighted
    for i, s in enumerate(["photos san francisco"] + SUGGEST):
        if i == 0:
            D.rect([sx + 12, yy - 6, swi - 24, 40], fill=ACCSOFT, radius=12)
        D.rect([sx + 22, yy, 22, 22], fill=(ACC if i == 0 else "#F0F0F4"), radius=6)
        ic("search", sx + 33, yy + 11, ("#FFFFFF" if i == 0 else MUTE), s=5.2, sw=1.5)
        T(sx + 54, yy, swi - 90, s, size=12, color=(INK if i == 0 else SUB),
          weight=(700 if i == 0 else 500), valign="middle", h=22)
        ic("chev", sx + swi - 30, yy + 11, FAINT, s=5, sw=1.6)
        yy += 44

    # people who shared these
    px, pyy, pw = RAILX, sy + sug_h + 20, RAILW
    ph = 150
    soft([px, pyy, pw, ph], radius=18)
    T(px + 20, pyy + 16, pw - 40, "Shared these with you", size=14.5, weight=800, color=INK, h=18)
    sharers = [("Ananya", "8 photos · SF trip", CORAL, "AN"),
               ("Joey Smith", "3 photos · Bay Bridge", OCEAN, "JS")]
    yy = pyy + 46
    for name, act, g, ini in sharers:
        grad_avatar(px + 34, yy + 16, 17, g, ini, tsize=12)
        T(px + 60, yy + 4, pw - 90, name, size=12.5, weight=700, color=INK, h=15)
        T(px + 60, yy + 21, pw - 90, act, size=10.5, color=MUTE, h=13)
        ic("chev", px + pw - 30, yy + 16, FAINT, s=5, sw=1.6)
        yy += 46

    # map preview card fills the rest
    mx, myy, mw = RAILX, pyy + ph + 20, RAILW
    mh = BOT - myy
    D.rect([mx, myy, mw, mh], fill=FOREST, radius=18,
           shadow={"dx": 0, "dy": 6, "blur": 22, "color": "#141A2610"})
    # faux map: streets + a pin
    for gx in range(1, 5):
        D.rect([mx + gx * mw / 5, myy, 1.5, mh], fill="#FFFFFF", fill_opacity=0.18)
    for gy_ in range(1, 4):
        D.rect([mx, myy + gy_ * mh / 4, mw, 1.5], fill="#FFFFFF", fill_opacity=0.18)
    D.circle([mx + mw * 0.5, myy + mh * 0.42], 20, fill="#FFFFFF", fill_opacity=0.25)
    ic("pin", mx + mw * 0.5, myy + mh * 0.42, "#FFFFFF", s=8, fillcol=FOREST)
    T(mx + 18, myy + mh - 30, mw - 36, "San Francisco · 128 nearby", size=11.5,
      color="#FFFFFF", weight=700, h=16)

    player()

def secbtn(x, y, w, h, label, *, color=SUB, radius=10):
    D.rect([x, y, w, h], fill=CARD, stroke=LINE2, stroke_style={"stroke_width": 1}, radius=radius)
    T(x, y, w, label, size=12.5, weight=700, color=color, align="center", valign="middle", h=h)

def check(cx, cy, col=GOOD, r=9):
    D.circle([cx, cy], r, fill=col)
    D.path([("M", cx - r * 0.42, cy), ("L", cx - r * 0.12, cy + r * 0.34), ("L", cx + r * 0.44, cy - r * 0.36)],
           stroke="#FFFFFF", stroke_style={"stroke_width": 1.9, "stroke_linecap": "round",
                                           "stroke_linejoin": "round"}, fill="none")

# --------------------------------------------------------------------------- #
#  SURFACE 3 — Sign in  (full-bleed split: brand panel + form)
# --------------------------------------------------------------------------- #
def signin():
    D.rect([0, 0, W, H], fill=BG)
    LW = 628
    D.rect([0, 0, LW, H], fill=SB_G)
    # faint aura texture (kept inside the brand panel)
    D.circle([70, 140], 220, fill=AURA, fill_opacity=0.16)
    D.circle([330, 812], 236, fill=OCEAN, fill_opacity=0.12)
    D.circle([506, 96], 118, fill=DUSK, fill_opacity=0.12)
    # brand
    D.rect([64, 68, 40, 40], fill=AURA, radius=12)
    D.circle([64 + 20, 68 + 20], 10.5, fill="none", stroke="#FFFFFF", stroke_style={"stroke_width": 2.4})
    D.circle([64 + 20, 68 + 20], 3.6, fill="#FFFFFF")
    T(118, 78, 300, "Aura", size=22, color="#FFFFFF", weight=800, h=28)
    # tagline
    T(64, 232, LW - 120, "Your music, photos, and the", size=34, color="#FFFFFF", weight=800, h=44)
    T(64, 276, LW - 120, "people who share them —", size=34, color="#FFFFFF", weight=800, h=44)
    T(64, 320, LW - 120, "in one calm place.", size=34, color="#B8B2E8", weight=800, h=44)
    T(64, 386, LW - 170, "Shared with You brings every song, album, and photo your "
      "friends send you — together, beautifully.", size=13.5, color=SBTXT, h=44)
    # feature bullets
    feats = [("music", "Everything shared, in one feed"),
             ("photo", "Photos from all your apps, searchable"),
             ("moon", "Focus that shares your status")]
    fy = 476
    for nm, lab in feats:
        D.circle([84, fy + 11], 15, fill="#FFFFFF", fill_opacity=0.12)
        ic(nm, 84, fy + 11, "#FFFFFF", s=6.2, sw=1.6, fillcol="#2A2340")
        T(112, fy, LW - 180, lab, size=13.5, color="#FFFFFF", weight=500, valign="middle", h=22)
        fy += 46
    T(64, H - 54, LW - 120, "© 2026 Aura · Privacy · Terms", size=11, color=SBMUTE, h=14)
    # right form card
    cardw, cardh = 392, 468
    cX = LW + ((W - LW) - cardw) / 2
    cY = (H - cardh) / 2
    soft([cX, cY, cardw, cardh], radius=22, blur=34, dy=10, sh="#141A2618")
    D.rect([cX + cardw / 2 - 22, cY + 38, 44, 44], fill=AURA, radius=13)
    D.circle([cX + cardw / 2, cY + 60], 11, fill="none", stroke="#FFFFFF", stroke_style={"stroke_width": 2.4})
    D.circle([cX + cardw / 2, cY + 60], 3.8, fill="#FFFFFF")
    T(cX, cY + 98, cardw, "Welcome back", size=21, weight=800, color=INK, align="center", h=26)
    T(cX, cY + 128, cardw, "Sign in to continue to Aura", size=12.5, color=MUTE, align="center", h=16)
    bx, bw = cX + 36, cardw - 72
    D.add(button([bx, cY + 166, bw, 44], "Continue with Apple", kind="primary", theme=TH))
    secbtn(bx, cY + 220, bw, 44, "Continue with Google", color=INK)
    # divider
    hy = cY + 288
    D.rect([bx, hy, bw / 2 - 16, 1], fill=LINE2); D.rect([bx + bw / 2 + 16, hy, bw / 2 - 16, 1], fill=LINE2)
    T(cX, hy - 7, cardw, "or", size=11, color=MUTE, align="center", h=14)
    D.add(field([bx, cY + 306, bw, 40], "", placeholder="you@email.com", theme=TH))
    D.add(button([bx, cY + 354, bw, 42], "Continue with email", kind="subtle", theme=TH))
    T(cX, cY + 414, cardw, "New to Aura?   Create your space", size=12, color=ACC, weight=600,
      align="center", h=16)

# --------------------------------------------------------------------------- #
#  SURFACE 4 — Sync run  (≈ render pipeline: connect → scan → match → ready)
# --------------------------------------------------------------------------- #
SYNC_STEPS = ["Connect apps", "Scan library · 2,481 items", "Match Shared with You",
              "De-dupe & organize", "Ready to browse"]

def sync():
    D.rect([0, 0, W, H], fill=BG)
    sidebar(None)
    topbar(mode="crumb", crumb="Aura  ›  Sync")
    rx0 = CX0
    rw = (W - GUT) - CX0
    pw = 720
    pX = rx0 + (rw - pw) / 2
    pY, pH = TOP + 6, BOT - TOP - 12
    soft([pX, pY, pw, pH], radius=20, blur=30, dy=8)
    T(pX + 30, pY + 24, 400, "Sync run", size=19, weight=800, color=INK, h=24)
    D.rect([pX + pw - 190, pY + 22, 160, 28], fill=TH.good_soft, radius=14)
    check(pX + pw - 176, pY + 36, GOOD, r=7)
    T(pX + pw - 162, pY + 22, 140, "Complete · 6.2s", size=12, color="#1B7A45", weight=700, valign="middle", h=28)
    D.rect([pX + 30, pY + 64, pw - 60, 1], fill=LINE)
    for i, nm in enumerate(SYNC_STEPS):
        yy = pY + 84 + i * 46
        check(pX + 44, yy + 9, GOOD, r=9)
        T(pX + 66, yy, 340, nm, size=13.5, weight=600, color=INK, h=18)
        D.rect([pX + 380, yy + 6, pw - 520, 6], fill=TH.good_soft, radius=3)
        D.rect([pX + 380, yy + 6, pw - 520, 6], fill=GOOD, radius=3)
        T(pX + pw - 96, yy, 66, "done", size=11.5, color=GOOD, weight=700, align="right", mono=True, h=18)
    gyy = pY + 84 + len(SYNC_STEPS) * 46 + 6
    D.rect([pX + 30, gyy, pw - 60, 1], fill=LINE)
    check(pX + 44, gyy + 24, GOOD, r=9)
    T(pX + 66, gyy + 15, 500, "4 / 4 sources synced · Music, Photos, Messages, Files", size=13.5,
      weight=700, color="#1B7A45", h=18)
    # result artifacts
    ayy = gyy + 56
    arts = [("SF Trip", "album · 128 photos", DUSK, "Open"),
            ("New Shared with You", "12 items from 5 people", OCEAN, "View")]
    for i, (nm, meta, g, cta) in enumerate(arts):
        x0 = pX + 30 + i * ((pw - 60) / 2 + 8)
        bw = (pw - 60) / 2 - 8
        D.rect([x0, ayy, bw, 74], fill=BG, stroke=LINE2, stroke_style={"stroke_width": 1}, radius=12)
        D.rect([x0 + 14, ayy + 15, 44, 44], fill=g, radius=10)
        ic("photo" if i == 0 else "share", x0 + 36, ayy + 37, "#FFFFFF", s=7, sw=1.6)
        T(x0 + 70, ayy + 15, bw - 180, nm, size=13.5, weight=700, color=INK, h=18)
        T(x0 + 70, ayy + 36, bw - 180, meta, size=11, color=MUTE, h=14)
        D.add(button([x0 + bw - 96, ayy + 20, 82, 34], cta, kind="primary", theme=TH))
    # recent runs log
    ry3 = ayy + 74 + 32
    D.rect([pX + 30, ry3 - 14, pw - 60, 1], fill=LINE)
    T(pX + 30, ry3, 300, "RECENT RUNS", size=10.5, color=MUTE, weight=700, spacing=0.8, h=14)
    for i, (when, kind, delta, ok) in enumerate([
            ("Today · 3:02 PM", "full sync", "+12 items", True),
            ("Today · 2:47 PM", "photos only", "+128 photos", True),
            ("Yesterday · 9:15 AM", "full sync", "no changes", False)]):
        yy = ry3 + 24 + i * 30
        D.circle([pX + 38, yy + 7], 3.5, fill=(GOOD if ok else FAINT))
        T(pX + 52, yy, 220, when, size=12, color=INK, weight=600, h=15)
        T(pX + 250, yy, 200, kind, size=12, color=MUTE, mono=True, h=15)
        T(pX + pw - 230, yy, 200, delta, size=12, color=(GOOD if ok else MUTE),
          weight=600, align="right", h=15)
    T(pX + 30, pY + pH - 34, 200, "↻  Re-sync now", size=13, color=ACC, weight=700, h=16)
    T(pX + pw - 260, pY + pH - 34, 230, "Auto-syncs every 15 min", size=11.5, color=MUTE,
      align="right", h=16)
    player()

# --------------------------------------------------------------------------- #
#  SURFACE 5 — Activity  (≈ history: timeline + detail)
# --------------------------------------------------------------------------- #
ACTS = [("now", "You played Phoenix", "Charlotte Cardin", "play", False, OCEAN),
        ("12m", "Ann Li shared 12 photos", "added to SF Trip", "photo", True, CORAL),
        ("1h", "Focus set to Personal", "until 6:00 PM", "user", False, DUSK),
        ("2h", "You shared “SF Trip”", "to Ananya, Joey +1", "share", True, SUNSET),
        ("Yest.", "Joey shared a playlist", "Paper Boats · Lull", "music", False, MINT),
        ("2d", "Synced 480 new photos", "from Photos & Messages", "photo", False, FOREST)]

def activity():
    D.rect([0, 0, W, H], fill=BG)
    sidebar(None)
    topbar(mode="crumb", crumb="Aura  ›  Activity")
    T(CX0, 104, 640, "Activity", size=26, weight=800, color=INK, h=34)
    T(CX0, 142, 640, "Everything you and your people did lately.", size=13.5, color=SUB, h=18)
    # timeline card
    lx, ly = CX0, 182
    lw, lh = MAINW, BOT - 182
    soft([lx, ly, lw, lh], radius=18)
    T(lx + 22, ly + 18, 300, "Timeline", size=14.5, weight=800, color=INK, h=18)
    T(lx + lw - 140, ly + 20, 120, "auto + you", size=11, color=GOOD, weight=700, align="right", h=14)
    D.rect([lx + 52, ly + 60, 2, len(ACTS) * 74 - 40], fill=LINE2)
    for i, (when, title, meta, gl, star, g) in enumerate(ACTS):
        yy = ly + 56 + i * 74
        sel = i == 3
        if sel:
            D.rect([lx + 16, yy - 6, lw - 32, 60], fill=ACCSOFT, radius=12)
        D.circle([lx + 53, yy + 18], 15, fill=g)
        ic(gl, lx + 53, yy + 18, "#FFFFFF", s=6.4, sw=1.5, fillcol=g)
        if star:
            D.circle([lx + 62, yy + 8], 6, fill=WARN, stroke=CARD, stroke_style={"stroke_width": 1.5})
        T(lx + 82, yy + 4, lw - 200, title, size=13.5, weight=700, color=(ACC if sel else INK), h=17)
        T(lx + 82, yy + 23, lw - 200, meta, size=11.5, color=MUTE, h=14)
        T(lx + lw - 90, yy + 6, 66, when + " ago" if when not in ("now", "Yest.", "2d") else when,
          size=11, color=FAINT, align="right", mono=True, h=14)
    # detail rail
    dx, dy = RAILX, TOP
    dw, dh = RAILW, 420
    soft([dx, dy, dw, dh], radius=18)
    T(dx + 20, dy + 18, dw - 40, "Details", size=14.5, weight=800, color=INK, h=18)
    scene(dx + 20, dy + 46, dw - 40, 132, SUNSET, "gold", radius=14)
    photo_tag(dx + 20, dy + 46, dw - 40, 132, "SF Trip · 128")
    T(dx + 20, dy + 190, dw - 40, "You shared “SF Trip”", size=15, weight=800, color=INK, h=20)
    T(dx + 20, dy + 214, dw - 40, "2h ago · read-only link · 3 people", size=11.5, color=MUTE, h=14)
    # recipients
    for i, (g, ini) in enumerate([(CORAL, "AN"), (OCEAN, "JS"), (MINT, "SA")]):
        grad_avatar(dx + 32 + i * 26, dy + 250, 13, g, ini, tsize=10)
    T(dx + 32 + 3 * 26 + 6, dy + 240, 120, "+ invite", size=11.5, color=ACC, weight=700, valign="middle", h=22)
    D.rect([dx + 20, dy + 282, dw - 40, 1], fill=LINE)
    changes = [("added 8 photos", GOOD), ("added a caption", GOOD), ("created a share link", ACC)]
    for i, (ch, c) in enumerate(changes):
        yy = dy + 296 + i * 26
        D.circle([dx + 28, yy + 7], 3, fill=c)
        T(dx + 40, yy, dw - 70, ch, size=12, color=SUB, h=15)
    D.add(button([dx + 20, dy + dh - 52, (dw - 52) * 0.62, 38], "Open album", kind="primary", theme=TH))
    secbtn(dx + 20 + (dw - 52) * 0.62 + 12, dy + dh - 52, (dw - 52) * 0.38, 38, "Unshare", color=RED)
    # a small "connected" card below
    cy2 = dy + dh + 20
    soft([dx, cy2, dw, BOT - cy2], radius=18)
    T(dx + 20, cy2 + 16, dw - 40, "This week", size=14, weight=800, color=INK, h=18)
    stats = [("Shared", "6"), ("Played", "142"), ("Synced", "480")]
    swi = (dw - 40) / 3
    for i, (lab, val) in enumerate(stats):
        x0 = dx + 20 + i * swi
        T(x0, cy2 + 44, swi, val, size=22, weight=800, color=ACC, h=26)
        T(x0, cy2 + 72, swi, lab, size=11, color=MUTE, h=14)
    D.rect([dx + 20, cy2 + 104, dw - 40, 1], fill=LINE)
    T(dx + 20, cy2 + 116, dw - 40, "TOP THIS WEEK", size=10, color=MUTE, weight=700, spacing=0.8, h=13)
    tops = [("music", "Phoenix", "Charlotte Cardin · 14 plays", OCEAN),
            ("user", "Ann Li", "shared 34 photos with you", CORAL),
            ("photo", "SF Trip", "your most-viewed album", SUNSET)]
    for i, (gl, nm, meta, g) in enumerate(tops):
        yy = cy2 + 140 + i * 44
        D.rect([dx + 20, yy, 32, 32], fill=g, radius=9)
        ic(gl, dx + 36, yy + 16, "#FFFFFF", s=6.2, sw=1.5)
        T(dx + 62, yy, dw - 100, nm, size=12.5, weight=700, color=INK, h=15)
        T(dx + 62, yy + 17, dw - 100, meta, size=10.5, color=MUTE, h=13)
    player()

# --------------------------------------------------------------------------- #
#  SURFACE 6 — Viewer  (public shared album, read-only + comments)
# --------------------------------------------------------------------------- #
VGRID = [("Golden Gate", SKY, "sky"), ("Downtown", CITY, "city"), ("Muir Woods", FOREST, "forest"),
         ("Painted Ladies", GOLD, "gold"), ("Twin Peaks", DUSK, "sky"), ("Ferry Bldg", SUNSET, "gold")]
VCOMM = [("AN", "Ananya", "These are gorgeous — the bridge shot!", "2h", CORAL, False),
         ("JS", "Joey", "Save me the Muir Woods one?", "1h", OCEAN, False),
         ("P", "You", "Just added 8 more from day two.", "now", DUSK, True)]

def viewer():
    D.rect([0, 0, W, H], fill="#EFEFF3")
    # public top bar
    D.rect([0, 0, W, 60], fill=CARD); D.rect([0, 60, W, 1], fill=LINE2)
    D.rect([28, 14, 32, 32], fill=AURA, radius=9)
    D.circle([28 + 16, 14 + 16], 8, fill="none", stroke="#FFFFFF", stroke_style={"stroke_width": 2})
    D.circle([28 + 16, 14 + 16], 2.8, fill="#FFFFFF")
    T(72, 13, 300, "SF Trip", size=15, weight=800, color=INK, h=18)
    T(72, 33, 300, "shared by Pedro Silva", size=11, color=MUTE, h=14)
    D.rect([190, 18, 150, 24], fill=TH.fill, radius=12)
    ic("clock", 204, 30, MUTE, s=5, sw=1.4)
    T(216, 18, 118, "Shared · view only", size=10.5, color=SUB, weight=600, valign="middle", h=24)
    secbtn(W - 320, 15, 132, 30, "Save to Library", color=INK)
    D.add(button([W - 176, 15, 148, 30], "Open in Aura", kind="primary", theme=TH))
    # left gallery
    gx, gy = 40, 88
    gw = 900
    # hero
    hh = 340
    scene(gx, gy, gw, hh, SKY, "sky", radius=18)
    photo_tag(gx, gy, gw, hh, "Golden Gate · June 2024")
    # thumbnail row
    ty = gy + hh + 16
    cols = 6
    gap = 14
    tw = (gw - (cols - 1) * gap) / cols
    for i, (label, g, kind) in enumerate(VGRID):
        x0 = gx + i * (tw + gap)
        scene(x0, ty, tw, tw * 0.72, g, kind, radius=12)
    # caption block
    cyy = ty + tw * 0.72 + 26
    T(gx, cyy, gw, "San Francisco Trip", size=22, weight=800, color=INK, h=28)
    T(gx, cyy + 34, gw, "128 photos · June 2024 · shared with 3 people", size=13, color=SUB, h=18)
    T(gx, cyy + 62, gw, "Three days along the coast — the bridge at golden hour, Muir Woods, "
      "and the painted ladies. Tap any photo to view it full-size.", size=13, color=MUTE, h=40)
    # right comments panel
    cpx = gx + gw + 32
    cpw = W - cpx - 32
    soft([cpx, 88, cpw, H - 88 - 32], radius=18)
    T(cpx + 22, 108, cpw - 60, "Comments", size=15, weight=800, color=INK, h=18)
    D.rect([cpx + cpw - 46, 107, 26, 20], fill=ACCSOFT, radius=8)
    T(cpx + cpw - 46, 107, 26, "3", size=11, color=ACC, weight=800, align="center", valign="middle", h=20)
    D.rect([cpx + 22, 138, cpw - 44, 1], fill=LINE)
    for i, (ini, who, msg, when, g, me) in enumerate(VCOMM):
        yy = 158 + i * 108
        grad_avatar(cpx + 36, yy + 14, 15, g, ini, tsize=11)
        T(cpx + 60, yy + 2, cpw - 120, who, size=12.5, weight=700, color=INK, h=15)
        T(cpx + cpw - 70, yy + 3, 48, when, size=10, color=MUTE, align="right", h=14)
        D.rect([cpx + 60, yy + 22, cpw - 84, 58], fill=(ACCSOFT if me else BG), radius=12)
        T(cpx + 74, yy + 32, cpw - 112, msg, size=12, color=INK, h=40)
    # composer
    D.add(field([cpx + 22, H - 88, cpw - 110, 40], "", placeholder="Add a comment…", theme=TH))
    D.add(button([cpx + cpw - 80, H - 88, 58, 40], "Send", kind="primary", theme=TH))

# --------------------------------------------------------------------------- #
#  SURFACE 7 — Settings
# --------------------------------------------------------------------------- #
SETNAV = [("Profile", True), ("Connected apps", False), ("Focus", False),
          ("Sharing & privacy", False), ("Notifications", False), ("Billing", False)]

def settings():
    D.rect([0, 0, W, H], fill=BG)
    sidebar(None)
    topbar(mode="crumb", crumb="Aura  ›  Settings")
    T(CX0, 104, 400, "Settings", size=26, weight=800, color=INK, h=34)
    # settings sub-nav
    nvx, nvy, nvw = CX0, 168, 210
    soft([nvx, nvy, nvw, 300], radius=16)
    for i, (nm, on) in enumerate(SETNAV):
        yy = nvy + 12 + i * 44
        if on:
            D.rect([nvx + 10, yy, nvw - 20, 36, ], fill=ACCSOFT, radius=10)
        T(nvx + 24, yy, nvw - 40, nm, size=13, weight=(700 if on else 500),
          color=(ACC if on else SUB), valign="middle", h=36)
    T(nvx + 24, nvy + 12 + len(SETNAV) * 44 + 6, nvw - 40, "Sign out", size=13, color=RED, weight=600, h=18)
    # profile detail
    dxx = nvx + nvw + 28
    dww = (RAILX - GUT) - dxx
    soft([dxx, nvy, dww, 300], radius=16)
    T(dxx + 24, nvy + 22, 300, "Profile", size=16, weight=800, color=INK, h=20)
    D.rect([dxx + 24, nvy + 52, dww - 48, 1], fill=LINE)
    grad_avatar(dxx + 54, nvy + 104, 30, OCEAN, "P", tsize=22)
    T(dxx + 96, nvy + 84, 200, "Change photo", size=12.5, color=ACC, weight=700, h=16)
    T(dxx + 96, nvy + 104, 200, "JPG or PNG · max 4 MB", size=11, color=MUTE, h=14)
    for i, (lab, val) in enumerate([("Name", "Pedro Silva"), ("Email", "pedro@aura.app")]):
        x0 = dxx + 24 + i * ((dww - 48) / 2 + 8)
        bw = (dww - 48) / 2 - 8
        T(x0, nvy + 158, bw, lab.upper(), size=10.5, color=MUTE, weight=700, spacing=0.6, h=14)
        D.rect([x0, nvy + 176, bw, 40], fill=CARD, stroke=LINE2, stroke_style={"stroke_width": 1}, radius=9)
        T(x0 + 14, nvy + 176, bw - 24, val, size=13, color=INK, valign="middle", h=40)
    T(dxx + 24, nvy + 234, 100, "STATUS", size=10.5, color=MUTE, weight=700, spacing=0.6, h=14)
    D.rect([dxx + 24, nvy + 252, dww - 48, 40], fill=CARD, stroke=LINE2, stroke_style={"stroke_width": 1}, radius=9)
    D.circle([dxx + 40, nvy + 272], 5, fill=GOOD)
    T(dxx + 54, nvy + 252, 240, "Premium · renews Jul 2026", size=13, color=INK, valign="middle", h=40)
    # right rail cards
    rlx = RAILX
    # connected apps
    soft([rlx, TOP, RAILW, 232], radius=18)
    T(rlx + 20, TOP + 16, RAILW - 40, "Connected apps", size=14.5, weight=800, color=INK, h=18)
    apps = [("music", "Music", OCEAN, True), ("photo", "Photos", DUSK, True),
            ("share", "Messages", MINT, True), ("grid", "Files", SUNSET, False)]
    for i, (gl, nm, g, on) in enumerate(apps):
        yy = TOP + 48 + i * 44
        D.rect([rlx + 20, yy, 30, 30], fill=g, radius=9)
        ic(gl, rlx + 35, yy + 15, "#FFFFFF", s=6, sw=1.5)
        T(rlx + 60, yy, 160, nm, size=13, weight=600, color=INK, valign="middle", h=30)
        D.add(toggle_pill(rlx + RAILW - 62, yy + 4, on))
    # sharing & privacy
    sy2 = TOP + 232 + 20
    soft([rlx, sy2, RAILW, 224], radius=18)
    T(rlx + 20, sy2 + 16, RAILW - 40, "Sharing & privacy", size=14.5, weight=800, color=INK, h=18)
    T(rlx + 20, sy2 + 48, RAILW - 40, "DEFAULT SHARE LINK", size=10, color=MUTE, weight=700, spacing=0.6, h=13)
    D.rect([rlx + 20, sy2 + 66, RAILW - 40, 38], fill=CARD, stroke=LINE2, stroke_style={"stroke_width": 1}, radius=9)
    T(rlx + 34, sy2 + 66, RAILW - 90, "Anyone with link · comment", size=12, color=INK, valign="middle", h=38)
    ic("chevd", rlx + RAILW - 34, sy2 + 85, MUTE, s=5, sw=1.6)
    D.rect([rlx + 20, sy2 + 118, RAILW - 40, 1], fill=LINE)
    # focus lock
    D.rect([rlx + 20, sy2 + 138, 30, 30], fill=INK, radius=9)
    ic("moon", rlx + 35, sy2 + 153, "#FFFFFF", s=6, sw=1.4, fillcol=INK)
    T(rlx + 60, sy2 + 134, 200, "Focus lock", size=13, weight=700, color=INK, h=16)
    T(rlx + 60, sy2 + 152, 220, "A PIN protects presence sharing", size=10.5, color=MUTE, h=13)
    D.rect([rlx + RAILW - 78, sy2 + 138, 58, 24], fill=TH.good_soft, radius=12)
    T(rlx + RAILW - 78, sy2 + 138, 58, "ON", size=10.5, color="#1B7A45", weight=800, align="center", valign="middle", h=24)
    secbtn(rlx + 20, sy2 + 176, RAILW - 40, 34, "Change PIN", color=INK)
    # devices card (fills the rail)
    dvy = sy2 + 224 + 20
    soft([rlx, dvy, RAILW, BOT - dvy], radius=18)
    T(rlx + 20, dvy + 16, RAILW - 40, "Devices", size=14.5, weight=800, color=INK, h=18)
    for i, (nm, meta, here) in enumerate([("MacBook Pro", "this device · active now", True),
                                          ("iPhone 16", "Cupertino · 2h ago", False),
                                          ("iPad Air", "Home · yesterday", False)]):
        yy = dvy + 46 + i * 56
        D.rect([rlx + 20, yy, 34, 34], fill=(ACCSOFT if here else TH.fill), radius=9)
        ic("device", rlx + 37, yy + 17, (ACC if here else SUB), s=6.5, sw=1.6)
        T(rlx + 64, yy + 2, 180, nm, size=12.5, weight=700, color=INK, h=15)
        T(rlx + 64, yy + 19, 210, meta, size=10.5, color=MUTE, h=13)
        if here:
            D.circle([rlx + RAILW - 32, yy + 17], 4, fill=GOOD)
        else:
            T(rlx + RAILW - 84, yy + 8, 64, "Log out", size=10.5, color=ACC, weight=700, align="right", h=14)

    # --- appearance card (center, below profile) ---
    ay = nvy + 320
    soft([dxx, ay, dww, 168], radius=16)
    T(dxx + 24, ay + 20, 300, "Appearance", size=16, weight=800, color=INK, h=20)
    D.rect([dxx + 24, ay + 50, dww - 48, 1], fill=LINE)
    AUTO = lin(90, ("#FFFFFF", "0%"), ("#FFFFFF", "50%"), ("#20202A", "50%"), ("#20202A", "100%"))
    tw3 = (dww - 48 - 2 * 14) / 3
    for i, (lab, swx, on) in enumerate([("Light", "#FFFFFF", True), ("Dark", "#20202A", False),
                                        ("Auto", AUTO, False)]):
        x0 = dxx + 24 + i * (tw3 + 14)
        D.rect([x0, ay + 64, tw3, 66], fill=CARD, stroke=(ACC if on else LINE2),
               stroke_style={"stroke_width": (2 if on else 1)}, radius=12)
        D.rect([x0 + 12, ay + 76, tw3 - 24, 26], fill=swx, stroke=LINE2,
               stroke_style={"stroke_width": 1}, radius=6)
        T(x0, ay + 106, tw3, lab, size=11.5, weight=(700 if on else 600),
          color=(ACC if on else SUB), align="center", h=16)
        if on:
            check(x0 + tw3 - 14, ay + 76, ACC, r=7)
    # --- account card (center, fills to bottom) ---
    cay = ay + 168 + 20
    soft([dxx, cay, dww, BOT - cay], radius=16)
    T(dxx + 24, cay + 20, 300, "Account", size=16, weight=800, color=INK, h=20)
    D.rect([dxx + 24, cay + 50, dww - 48, 1], fill=LINE)
    for i, (k, v) in enumerate([("Language", "English (US)"), ("Time zone", "America / Los Angeles"),
                                ("Two-factor auth", "On")]):
        yy = cay + 66 + i * 30
        T(dxx + 24, yy, 220, k, size=12.5, color=SUB, h=16)
        T(dxx + dww - 284, yy, 260, v, size=12.5, color=INK, weight=600, align="right", h=16)
    T(dxx + 24, cay + 66 + 3 * 30 + 8, 300, "Delete account", size=12.5, color=RED, weight=700, h=16)
    # --- storage card (left nav column) ---
    stx, sty = nvx, nvy + 320
    soft([stx, sty, nvw, 204], radius=16)
    T(stx + 20, sty + 18, nvw - 40, "Storage", size=14, weight=800, color=INK, h=18)
    T(stx + 20, sty + 42, nvw - 40, "42.8 GB of 200 GB", size=11.5, color=MUTE, h=14)
    D.rect([stx + 20, sty + 64, nvw - 40, 8], fill=TH.fill, radius=4)
    D.rect([stx + 20, sty + 64, (nvw - 40) * 0.21, 8], fill=ACC, radius=4)
    for i, (lab, c, val) in enumerate([("Photos", ACC, "28 GB"), ("Music", "#4F8BFF", "9 GB"),
                                       ("Files", "#8B5CFF", "5 GB")]):
        yy = sty + 88 + i * 24
        D.circle([stx + 26, yy + 7], 4, fill=c)
        T(stx + 40, yy, 120, lab, size=11.5, color=SUB, h=14)
        T(stx + nvw - 74, yy, 54, val, size=11, color=MUTE, align="right", h=14)
    secbtn(stx + 20, sty + 162, nvw - 40, 30, "Upgrade plan", color=ACC)
    player()

def toggle_pill(x, y, on):
    w, h = 40, 22
    return {"type": "group", "box": [x, y, w, h], "children": [
        {"type": "rect", "box": [0, 0, w, h], "fill": (ACC if on else "#D7D9E1"), "radius": h / 2},
        {"type": "ellipse", "center": [(w - h / 2) if on else h / 2, h / 2], "rx": h / 2 - 3, "ry": h / 2 - 3,
         "fill": "#FFFFFF"}]}

# --------------------------------------------------------------------------- #
#  SURFACE 8 — Sitemap & Journey  (the product flow, Aura-styled)
# --------------------------------------------------------------------------- #
def sitemap():
    D.rect([0, 0, W, H], fill=BG)
    MXs = 96
    CWDs = W - 2 * MXs
    T(MXs, 40, 600, "AURA", size=11, color=MUTE, weight=800, spacing=2.4, caps=True, h=14)
    T(MXs, 40, CWDs, "Sitemap & Journey", size=11, color=MUTE, weight=800, spacing=2.4, caps=True, align="right", h=14)
    D.rect([MXs, 60, CWDs, 1], fill=LINE2)
    T(MXs, 76, 600, "Information Architecture", size=11, color=ACC, weight=800, spacing=1.6, caps=True, h=14)
    T(MXs, 94, CWDs, "One home, a few rooms", size=30, color=INK, weight=800, h=40)
    T(MXs, 138, CWDs - 200, "The whole product around one calm home — sign in, land in the shared "
      "feed, and step into rooms to sync, review, and share.", size=13.5, color=SUB, h=20)
    D.rect([MXs, 168, 56, 3], fill=ACC)
    # persona strip
    py = 196
    soft([MXs, py, CWDs, 68], radius=14)
    grad_avatar(MXs + 40, py + 34, 20, OCEAN, "P", tsize=15)
    T(MXs + 76, py + 14, 460, "Pedro · listener & sharer", size=14, weight=700, color=INK, h=18)
    T(MXs + 76, py + 37, 540, "signed in · Premium · music, photos & people in one place", size=12, color=MUTE, h=15)
    T(MXs + CWDs - 476, py + 14, 460, "PRIMARY GOAL", size=10, color=FAINT, weight=700, spacing=1, caps=True, align="right", h=13)
    T(MXs + CWDs - 476, py + 32, 460, "browse & play → share with friends → stay in sync", size=13,
      color=ACC, weight=700, align="right", h=17)
    # journey flow: 3 boxes + arrows
    fy, fh = 300, 158
    xs = [MXs, MXs + 470, MXs + 470 + 456]
    ws = [400, 386, CWDs - (470 + 456)]
    FLOW = [("Sign in", "auth · SSO · email", "reach your space, zero friction", "p3", False),
            ("Home", "the shared feed", "listen · browse photos · focus · play", "p1", True),
            ("Share & Sync", "push album · pull items", "a shared album link, and a fresh library", "p4", False)]
    midy = fy + fh / 2
    for i in range(2):
        x0 = xs[i] + ws[i]; x1 = xs[i + 1]
        D.line([x0 + 8, midy], [x1 - 14, midy], stroke=ACC, stroke_style={"stroke_width": 1.8})
        D.path([("M", x1 - 14, midy), ("L", x1 - 22, midy - 4.4), ("L", x1 - 22, midy + 4.4), ("Z",)],
               fill=ACC, stroke="none")
    for (nm, bc, gl, folio, primary), x, w in zip(FLOW, xs, ws):
        yy = fy - (10 if primary else 0)
        hh = fh + (20 if primary else 0)
        D.rect([x, yy, w, hh], fill=("#FFFFFF" if not primary else "#FFFFFF"),
               stroke=(ACC if primary else LINE2), stroke_style={"stroke_width": 1.8 if primary else 1},
               radius=16, shadow={"dx": 0, "dy": 8, "blur": 24, "color": "#141A2614"})
        ty = yy + 18
        if primary:
            D.rect([x + 18, ty, 118, 20], fill=ACCSOFT, radius=10)
            T(x + 18, ty, 118, "PRIMARY SURFACE", size=9, color=ACC, weight=800, spacing=0.8,
              align="center", valign="middle", h=20)
            ty += 30
        T(x + 18, ty, w - 36, nm, size=20 if primary else 16, weight=800, color=INK, h=26)
        ty += 30 if primary else 24
        T(x + 18, ty, w - 36, bc, size=11.5, color=ACC, weight=700, mono=True, h=15)
        ty += 20
        T(x + 18, ty, w - 36, gl, size=12.5, color=MUTE, h=18)
        T(x + 18, yy + hh - 24, w - 36, folio, size=10.5, color=FAINT, weight=700, mono=True, h=14)
    # satellite branches from Home
    scx = xs[1] + ws[1] / 2
    sby = fy + fh
    ly, lh, lw = fy + fh + 70, 116, (CWDs - 3 * 24) / 4
    SATS = [("Photos", "search by place & person", "p2", OCEAN, False),
            ("Activity", "what you & your people did", "p5", DUSK, False),
            ("Viewer", "a friend opens your album", "p6", MINT, False),
            ("Settings", "apps · focus · privacy", "p7", CORAL, True)]
    for i, (nm, gl, folio, g, dashed) in enumerate(SATS):
        x = MXs + i * (lw + 24)
        nx = x + lw / 2
        ss = {"stroke_width": 1.4}
        if dashed:
            ss["stroke_dasharray"] = [5, 4]
        D.line([scx, sby + 4], [nx, ly], stroke=(FAINT if dashed else ACC),
               stroke_style=ss)
        soft([x, ly, lw, lh], radius=14, blur=0, stroke=LINE2, sw=1)
        D.rect([x + 16, ly + 16, 30, 30], fill=g, radius=9)
        ic({"Photos": "photo", "Activity": "clock", "Viewer": "share", "Settings": "grid"}[nm],
           x + 31, ly + 31, "#FFFFFF", s=6, sw=1.5)
        T(x + 56, ly + 16, lw - 70, nm, size=14, weight=700, color=INK, h=18)
        T(x + 16, ly + 58, lw - 32, gl, size=11.5, color=MUTE, h=15)
        T(x + 16, ly + lh - 24, lw - 32, folio, size=10, color=FAINT, weight=700, mono=True, h=13)
    # journeys legend
    jy = ly + lh + 30
    T(MXs, jy, 160, "THREE JOURNEYS", size=11, color=FAINT, weight=700, spacing=1.2, caps=True, h=14)
    jx = MXs + 150
    for lbl, col in [("Listen & share", ACC), ("Sync & import", "#4F8BFF"), ("Friend opens an album", GOOD)]:
        D.rect([jx, jy + 5, 28, 3], fill=col, radius=2)
        T(jx + 38, jy, 220, lbl, size=12.5, color=INK, h=16)
        jx += 38 + 7.0 * len(lbl) + 34
    # decisions
    dcy = jy + 40
    T(MXs, dcy, 200, "DECISIONS · defaults", size=11, color=FAINT, weight=700, spacing=1.2, caps=True, h=14)
    D.rect([MXs, dcy + 18, CWDs, 1], fill=LINE2)
    DEC = [("home", "the shared feed is the landing surface, not a plain library grid"),
           ("sharing", "a link anyone can open read-only + comment; save-to-library is optional"),
           ("sync", "connected apps pull automatically; manual re-sync is always available"),
           ("focus", "presence is shareable; Do-Not-Disturb also silences shared alerts"),
           ("journey end", "it ends when a friend saves the album — not at a download")]
    for i, (k, v) in enumerate(DEC):
        yy = dcy + 30 + i * 26
        T(MXs, yy, 150, k, size=12.5, color=ACC, weight=700, h=16)
        T(MXs + 160, yy, CWDs - 160, v, size=12.5, color=MUTE, h=16)
    D.rect([MXs, H - 54, CWDs, 1], fill=LINE2)
    T(MXs, H - 42, 980, "Principle — one home you return to; every room is one click away and one "
      "click back.", size=12.5, color=FAINT, italic=True, h=16)
    T(MXs, H - 42, CWDs, "8", size=11, color=FAINT, align="right", mono=True, h=16)

# --------------------------------------------------------------------------- #
#  Build
# --------------------------------------------------------------------------- #
PAGES = [("home", home), ("photos", photos_search), ("signin", signin),
         ("sync", sync), ("activity", activity), ("viewer", viewer),
         ("settings", settings), ("sitemap", sitemap)]

def build():
    global D
    b = DocumentBuilder(title="Aura — desktop media & focus hub", profile="deck", lang="en")
    for pid, fn in PAGES:
        pg = b.page(pid, canvas={"size": [W, H], "units": "px"}, coordinate_mode="absolute")
        D = pg.layer("app")
        fn()
    return b


if __name__ == "__main__":
    b = build()
    rep = validate_static_rules(b.build())
    errs = [x for x in rep.issues if x.severity == "error"]
    print(f"ok={rep.ok} errors={len(errs)} warns={len(rep.issues) - len(errs)} "
          f"pages={len(PAGES)} canvas={W}x{H}")
    for x in errs[:15]:
        print("  ERR:", x.rule_id, x.path, x.message)
    out = os.environ.get("OUTPUT_YAML_PATH", "aura-desktop-app.fg.yaml")
    build().write(out, fail_on_error=True)
    print("wrote", out)
