"""The Adequacy Machine — backend_spec v2.0.0, A3 infographic.

Generated by Claude Fable 5 via the FrameForge SDK.
Source of truth: backend_spec_v2_0_0.md (proposed standard, 2026-07-20).
Every claim on the poster is drawn from that document; nothing is invented.
"""
import math

from frameforge.sdk import DocumentBuilder
from frameforge.sdk.paint import stroke

W, H = 842, 1191
MX = 36
CW = W - 2 * MX

# Closed palette (Chevreul): ground scale + ink scale + one accent + one subdued complement.
GROUND = "#0F1218"    # deep ink ground
PANEL = "#161B24"     # raised panel
PANEL2 = "#1D2431"    # higher raised
RING = "#3A4356"      # node rings
HAIR = "#2A3242"      # hairlines
PAPER = "#EDEAE0"     # warm paper-white ink
QUIET = "#9AA3B4"     # second rank
DIM = "#5D6678"       # third rank / decorative
ACCENT = "#FF5233"    # vermilion — duty: THE NEW (axes P & W) + fatality
ACC_DIM = "#251510"   # vermilion's dark ground tint
TEAL = "#57C9B8"      # subdued complement — duty: verification / proof / flow
TEAL_D1 = "#24443F"
TEAL_D2 = "#2E6157"
TEAL_D3 = "#39786D"

SG = "Space Grotesk"
INTER = "Inter"
IM = "Inter Medium"
ISB = "Inter SemiBold"
IXB = "Inter ExtraBold"
MONO = "Fira Mono"
DMONO = "DejaVu Sans Mono"   # guaranteed δ, ₀, →, × coverage

doc = DocumentBuilder(title="The Adequacy Machine — backend_spec v2.0.0", profile="diagram")
page = doc.page("poster", canvas={"preset": "A3"}, coordinate_mode="absolute")
bg = page.layer("bg")
grid = page.layer("grid")
L = page.layer("content")


def T(box, s, f=INTER, size=8.7, color=PAPER, align="left", ls=None, lh=None,
      weight=None, opacity=None):
    st = {"font_family": f, "size": size, "color": color, "align": align}
    # static Inter weight families are resolved via CSS weight matching
    if f == ISB:
        st["font_family"], st["weight"] = INTER, 600
    elif f == IXB:
        st["font_family"], st["weight"] = INTER, 800
    if ls is not None:
        st["letter_spacing"] = ls
    if lh is not None:
        st["line_height"] = lh
    if weight is not None:
        st["weight"] = weight
    if opacity is not None:
        st["opacity"] = opacity
    if "\n" in s:
        st["white_space"] = "pre-line"
    L.text(box, s, style=st)


def hairline(x, y, w, h=0.8, color=HAIR, opacity=None):
    kw = {"fill": color}
    if opacity is not None:
        kw["opacity"] = opacity
    L.rect([x, y, w, h], **kw)


# ---------------------------------------------------------------- ground + grid
bg.rect([0, 0, W, H], fill=GROUND)
for k in range(11):
    grid.rect([MX + k * 77, 24, 0.5, H - 60], fill=PAPER, opacity=0.03)
for k in range(15):
    grid.rect([24, MX + k * 77, W - 48, 0.5], fill=PAPER, opacity=0.03)
# ghost numerals behind the hero
grid.text([380, 150, 426, 330], "2.0",
          style={"font_family": SG, "size": 250, "color": PAPER, "align": "right",
                 "weight": 700, "opacity": 0.035})
# corner registration marks
for cx_, cy_, dx, dy in [(14, 14, 1, 1), (W - 14, 14, -1, 1),
                         (14, H - 14, 1, -1), (W - 14, H - 14, -1, -1)]:
    L.polyline([[cx_ + dx * 10, cy_], [cx_, cy_], [cx_, cy_ + dy * 10]],
               **stroke(0.8, color=DIM), opacity=0.6)

# ---------------------------------------------------------------- masthead
T([MX, 26, 300, 12], "URN:BACKEND-SPEC:SCHEMA:2.0.0", f=DMONO, size=7, color=DIM,
  ls="0.08em")
T([271, 26, 300, 12], "PLATE 01 · SPECIFICATION FAMILY: BACKEND_SPEC", f=DMONO,
  size=7, color=DIM, align="center", ls="0.08em")
T([506, 26, 300, 12], "STATUS: PROPOSED_STANDARD · 2026-07-20", f=DMONO, size=7,
  color=DIM, align="right", ls="0.08em")
hairline(MX, 44, CW)

T([MX, 54, 604, 56], "THE ADEQUACY MACHINE", f=SG, size=41.7, color=PAPER,
  weight=700, ls="0.005em")
T([MX, 110, 560, 28],
  "Adequate Backend System Specification · Framework v2.0.0 — the machine-consumable "
  "contract for describing, diagnosing, generating, and reconstructing a production "
  "backend without silently swapping in surrogate semantics.",
  f=INTER, size=8.7, color=QUIET, lh=1.4)

T([640, 50, 166, 44], "6 → 8", f=IXB, size=33.4, color=ACCENT, align="right")
T([632, 96, 174, 44],
  "axes in v2.0.0 — provenance & trust and workload execution become first-class, "
  "capability-gated contracts",
  f=INTER, size=7, color=QUIET, align="right", lh=1.4)

stats = ["8 AXES", "12 KEYS", "3 INTENTS", "4 PREDICATES", "6 LEVELS", "10 PHASES",
         "30+ LAWS"]
for i, s_ in enumerate(stats):
    sx = MX + i * 86
    L.rect([sx, 146, 82, 16], fill=PANEL, **stroke(0.8, color=HAIR))
    T([sx, 150.5, 82, 10], s_, f=MONO, size=7, color=PAPER, align="center",
      ls="0.06em")


def section(num, title, y):
    T([MX, y, 34, 16], num, f=SG, size=13.7, color=PAPER, weight=700)
    T([MX + 34, y + 3.5, 560, 12], title, f=ISB, size=8.7, color=QUIET, ls="0.2em")
    hairline(MX, y + 18, CW)


# ---------------------------------------------------------------- 01 · axis rose
section("01", "THE EIGHT-AXIS CONTRACT SPACE", 170)

CXR, CYR, RR, RN = 283, 368, 131, 29
AXES = [
    ("D", "DATA", False, 0),
    ("O", "OPERATIONS", False, 45),
    ("B", "BEHAVIOR", False, 90),
    ("I", "INTERFACE", False, 135),
    ("X", "POLICY", False, 180),
    ("N", "RUNTIME", False, 225),
    ("P", "PROVENANCE", True, 270),
    ("W", "WORKLOADS", True, 315),
]


def axpos(deg, rad=RR):
    a = math.radians(deg)
    return (CXR + rad * math.sin(a), CYR - rad * math.cos(a))


# halo zone behind the rose
L.circle(center=[CXR, CYR], r=176, fill=PANEL, opacity=0.35)

# orbital microtext ring (axis-applicability law, §2.4)
try:
    from frameforge.sdk.pathtext import text_on_path
    _arc = [list(axpos(a / 10.0, 183)) for a in range(-300, 1501, 25)]
    _ring_txt = ("AXIS APPLICABILITY — SPECIFIED · NOT_APPLICABLE · "
                 "UNKNOWN (DIAGNOSTIC ONLY)")
    L.extend(text_on_path(_arc, _ring_txt, size=5.6, family=MONO, color=QUIET))
except Exception:
    pass

# orbit ticks + rings + faint octagon
for k in range(48):
    a = k * 7.5
    x1, y1 = axpos(a, 169)
    x2, y2 = axpos(a, 173)
    L.polyline([[x1, y1], [x2, y2]], **stroke(0.7, color=HAIR), opacity=0.8)
L.circle(center=[CXR, CYR], r=173, fill="none", **stroke(0.6, color=HAIR),
         opacity=0.4)
oct_pts = [list(axpos(22.5 + 45 * i)) for i in range(8)]
L.polygon(oct_pts, fill="none", **stroke(0.6, color=HAIR), opacity=0.5)

# spokes
for _, _, _, deg in AXES:
    p1 = axpos(deg, 72)
    p2 = axpos(deg, RR - RN - 2)
    L.polyline([list(p1), list(p2)], **stroke(0.8, color=HAIR), opacity=0.85)


def chord(a1, a2, label, wlab, tlab=0.5):
    p1 = axpos(a1, RR - RN - 4)
    p2 = axpos(a2, RR - RN - 4)
    mx_, my_ = (p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2
    cx_ = CXR + (mx_ - CXR) * 0.42
    cy_ = CYR + (my_ - CYR) * 0.42
    pts = []
    for i in range(25):
        t = i / 24
        x = (1 - t) ** 2 * p1[0] + 2 * (1 - t) * t * cx_ + t * t * p2[0]
        y = (1 - t) ** 2 * p1[1] + 2 * (1 - t) * t * cy_ + t * t * p2[1]
        pts.append([x, y])
    L.polyline(pts, **stroke(0.9, color=TEAL), opacity=0.38)
    # anchor the label plate where the chord enters the hub annulus; the plate
    # itself is emitted after the node discs so nothing clips it
    qx, qy = pts[12]
    for px, py in pts:
        if math.hypot(px - CXR, py - CYR) <= 88:
            qx, qy = px, py
            break
    CHORD_LABELS.append((qx, qy, label, wlab))


CHORD_LABELS = []


chord(45, 315, "async execution", 62, 0.26)    # O–W
chord(90, 315, "lease · fencing", 58, 0.3)     # B–W
chord(0, 225, "store placement", 62, 0.24)     # D–N
chord(270, 0, "derived artifacts", 68, 0.28)   # P–D

# center hub (covers chord middles — chords emerge from behind it)
L.circle(center=[CXR, CYR], r=66, fill=PANEL, **stroke(1.0, color=RING))
L.circle(center=[CXR, CYR], r=59, fill="none", **stroke(0.5, color=HAIR),
         opacity=0.7)
T([CXR - 40, CYR - 42, 80, 40], "M", f=SG, size=33.4, color=PAPER, align="center",
  weight=700)
T([CXR - 56, CYR + 2, 112, 10], "THE SPECIFIED SYSTEM", f=INTER, size=7,
  color=QUIET, align="center", ls="0.16em")
T([CXR - 62, CYR + 15, 124, 10], "State × Invocation → Outcome", f=DMONO, size=7,
  color=TEAL, align="center")

# axis nodes
for letter, name, new, deg in AXES:
    x, y = axpos(deg)
    if new:
        L.circle(center=[x, y], r=RN, fill=ACCENT,
                 effects=[{"kind": "glow", "color": ACCENT, "blur": 9,
                           "opacity": 0.5}])
        lc, nc = GROUND, GROUND
    else:
        L.circle(center=[x, y], r=RN, fill=PANEL2, **stroke(1.2, color=RING))
        lc, nc = PAPER, QUIET
    T([x - 20, y - 21, 40, 26], letter, f=SG, size=21.4, color=lc, align="center",
      weight=700)
    T([x - 27, y + 5, 54, 9], name, f=ISB, size=5.6, color=nc, align="center",
      ls="0.08em")
    if new:
        a = math.radians(deg)
        fx = x + (RN + 16) * math.sin(a)
        fy = y - (RN + 16) * math.cos(a)
        L.rect([fx - 16, fy - 5.5, 32, 11], fill=ACCENT)
        T([fx - 16, fy - 3.5, 32, 9], "NEW", f=SG, size=7, color=GROUND,
          align="center", weight=700, ls="0.14em")

# chord label plates — above the node discs
for qx, qy, label, wlab in CHORD_LABELS:
    L.rect([qx - wlab / 2, qy - 6, wlab, 12], fill=GROUND, opacity=0.9)
    T([qx - wlab / 2, qy - 3.6, wlab, 10], label, f=MONO, size=5.6, color=TEAL,
      align="center")

# ------------------------------------------------- eight contract questions
QUESTIONS = [
    ("D", False, "What information, relations, indexes & derived structures exist?"),
    ("O", False, "What may be requested, observed, scheduled, or administered?"),
    ("B", False, "How does domain state change and recover?"),
    ("I", False, "Through which protocols, media, envelopes & sessions is it used?"),
    ("X", False, "Which security, tenancy, privacy, audit & budget rules apply?"),
    ("N", False, "Which stores, deployables, resources & service levels run it?"),
    ("P", True, "How is each derived assertion produced, verified & licensed?"),
    ("W", True, "How does async work lease, retry, cancel, chain, route & drain?"),
]
for i, (letter, new, q) in enumerate(QUESTIONS):
    ci, ri = i % 4, i // 4
    x = MX + ci * 125
    y = 546 + ri * 30
    L.rect([x, y + 1, 13, 13], fill=(ACCENT if new else PANEL2))
    T([x, y + 2.6, 13, 11], letter, f=SG, size=8.7,
      color=(GROUND if new else PAPER), align="center", weight=700)
    T([x + 18, y, 103, 29], q, f=INTER, size=7, color=QUIET, lh=1.3)

# ------------------------------------------------- the machine model strip
L.rect([MX, 606, CW, 22], fill=PANEL, **stroke(0.8, color=HAIR))
T([46, 612, 470, 12],
  "M = (State, s₀, Inv, Out, Job, Artifact, δD, δW, observe, provenance, legal)",
  f=DMONO, size=8.7, color=PAPER)
T([500, 613.5, 296, 10],
  "δD domain step · δW workload step · legal(history) — the concurrency law",
  f=INTER, size=7, color=QUIET, align="right")

# ---------------------------------------------------------------- right rail
RX = 560
RW = 246

# Panel A — twelve required keys
L.rect([RX, 170, RW, 188], fill=PANEL, **stroke(0.8, color=HAIR))
T([RX + 12, 180, RW - 24, 12], "ONE PACKAGE · TWELVE REQUIRED KEYS", f=ISB,
  size=8.7, color=PAPER, ls="0.12em")
KEYS = ["/meta", "/scope", "/data", "/operations", "/behavior", "/interface",
        "/policy", "/runtime", "/provenance", "/workloads", "/imports",
        "/extensions"]
for i, key in enumerate(KEYS):
    ci, ri = i % 2, i // 2
    kx = RX + 12 + ci * 115
    ky = 198 + ri * 21.5
    new = key in ("/provenance", "/workloads")
    if new:
        L.rect([kx, ky, 107, 17], fill=ACC_DIM, **stroke(1.0, color=ACCENT))
        kc = ACCENT
    else:
        L.rect([kx, ky, 107, 17], fill=PANEL2, **stroke(0.8, color=RING))
        kc = PAPER
    T([kx, ky + 5, 107, 10], key, f=MONO, size=7, color=kc, align="center")
T([RX + 12, 332, RW - 24, 22],
  "$schema is optional — when present it MUST equal the v2 instance-schema ID. "
  "No v1.x root aliases survive conversion.",
  f=INTER, size=5.6, color=DIM, lh=1.3)

# Panel B — three intents
L.rect([RX, 366, RW, 96], fill=PANEL, **stroke(0.8, color=HAIR))
T([RX + 12, 375, RW - 24, 12], "THREE INTENTS, ONE TRUTH", f=ISB, size=8.7,
  color=PAPER, ls="0.12em")
INTENTS = [
    ("diagnostic", "partial; unknowns permitted, reported as gaps"),
    ("generation", "unknowns forbidden; a generator profile is required"),
    ("reconstruction", "round-trip; a binding for every in-scope item"),
]
for i, (name, desc) in enumerate(INTENTS):
    iy = 390 + i * 19
    T([RX + 12, iy, 88, 10], name, f=MONO, size=7, color=PAPER)
    T([RX + 100, iy + 0.5, 134, 17], desc, f=INTER, size=5.6, color=QUIET, lh=1.25)
T([RX + 12, 447, RW - 24, 10],
  "Diagnostic validity MUST NOT be reported as generation adequacy.",
  f=INTER, size=5.6, color=QUIET)

# Panel C — four predicates
L.rect([RX, 470, RW, 134], fill=PANEL, **stroke(0.8, color=HAIR))
T([RX + 12, 479, RW - 24, 12], "FOUR PREDICATES, NO ESCAPE HATCH", f=ISB,
  size=8.7, color=PAPER, ls="0.12em")
PREDS = [
    ("well_formed (S, F)", "structure resolves & intrinsic laws pass"),
    ("adequate (S, F, K, Ex)", "profile-independent completeness"),
    ("generatable (S, P)", "profile interpretation is total"),
    ("conformant (A, S, P, G)", "artifact evidence satisfies obligations"),
]
for i, (name, gloss) in enumerate(PREDS):
    py_ = 494 + i * 24
    L.rect([RX + 12, py_, 132, 16], fill=PANEL2, **stroke(0.8, color=RING))
    T([RX + 20, py_ + 4.5, 124, 10], name, f=MONO, size=7, color=PAPER)
    T([RX + 152, py_ + 1.5, 84, 15], gloss, f=INTER, size=5.6, color=QUIET, lh=1.25)
    if i < 3:
        L.polyline([[RX + 22, py_ + 17], [RX + 22, py_ + 22]],
                   **stroke(0.9, color=TEAL), opacity=0.8)
        L.polygon([[RX + 19.5, py_ + 21], [RX + 24.5, py_ + 21], [RX + 22, py_ + 24]],
                  fill=TEAL, opacity=0.8)
T([RX + 12, 590, RW - 20, 10],
  "A waiver → deployable_with_waiver; it cannot change any truth value.",
  f=INTER, size=5.6, color=QUIET)

# ---------------------------------------------------------------- 02 · ladder
section("02", "THE LADDER OF PROOF — SIX CONFORMANCE LEVELS", 636)

LEVELS = [
    ("schema_valid", "JSON Schema passes", PANEL),
    ("well_formed", "references, imports & intrinsic semantic laws resolve",
     PANEL2),
    ("adequate", "every in-scope contract represented; no fatal, unsafe or "
     "applicable gap", "#2C3648"),
    ("generatable", "profile capabilities & interpretation total over every token",
     "#364257"),
    ("artifact_conformant", "artifact evidence meets observation + traceability "
     "obligations", TEAL_D2),
    ("round_trip_conformant", "plus complete bidirectional inventory mappings",
     TEAL_D3),
]
BASE_Y = 790
for i, (name, req, col) in enumerate(LEVELS):
    xi = MX + i * 100.5
    hi = 28 + 18 * i
    yi = BASE_Y - hi
    L.rect([xi, yi, 97, hi], fill=col)
    T([xi + 5, yi + 4, 30, 10], "L%d" % (i + 1), f=SG, size=8.7, color=QUIET,
      weight=700)
    T([xi - 1, yi - 12, 99, 11], name, f=MONO, size=7, color=PAPER,
      align="center")
    T([xi, BASE_Y + 5, 97, 32], req, f=INTER, size=5.6, color=QUIET, lh=1.3)
hairline(MX, BASE_Y, 604, 1)

L.rect([650, 662, 0.8, 128], fill=HAIR)
T([662, 666, 144, 12], "NO SINGLE BOOLEAN", f=ISB, size=8.7, color=PAPER,
  ls="0.1em")
T([662, 680, 144, 70],
  "Tools MUST report the highest level actually reached — never collapse the six "
  "levels into one boolean. Adequacy is profile-independent: a generator profile "
  "cannot redefine it.",
  f=INTER, size=7, color=QUIET, lh=1.35)
T([662, 754, 144, 24],
  "A gap blocks adequacy whenever it concerns an applicable contract.",
  f=INTER, size=7, color=QUIET, lh=1.35)

# ---------------------------------------------------------------- 03 · pipeline
section("03", "TEN VALIDATION PHASES, IN ORDER", 838)

PHASES = [
    "parse_and_\nschema_validation", "version_\nselection",
    "import_and_\nextension_resolution", "reference_and_\ntype_resolution",
    "axis_applicability_\nactivation", "scope_coverage_\nvalidation",
    "intra_axis_\nlaws", "cross_axis_\nlaws", "profile_\ncompatibility",
    "conformance_decision\n_and_report",
]
ROW1_Y, ROW2_Y = 880, 934
XS = [76 + k * 118 for k in range(5)]


def phase_node(x, y, num, final=False):
    if final:
        L.circle(center=[x, y], r=11, fill=TEAL_D1, **stroke(1.2, color=TEAL),
                 effects=[{"kind": "glow", "color": TEAL, "blur": 8, "opacity": 0.4}])
        nc = TEAL
    else:
        L.circle(center=[x, y], r=11, fill=PANEL2, **stroke(1.1, color=RING))
        nc = PAPER
    T([x - 11, y - 5.5, 22, 11], str(num), f=SG, size=8.7, color=nc, align="center",
      weight=700)


def h_arrow(x1, x2, y):
    L.polyline([[x1, y], [x2 - 5, y]], **stroke(0.9, color=HAIR))
    d = 1 if x2 > x1 else -1
    L.polygon([[x2 - 5 * d, y - 3], [x2 - 5 * d, y + 3], [x2, y]], fill=DIM)


for k in range(5):
    phase_node(XS[k], ROW1_Y, k + 1)
    T([XS[k] - 57, ROW1_Y + 16, 114, 20], PHASES[k], f=MONO, size=7, color=QUIET,
      align="center", lh=1.25)
    if k < 4:
        h_arrow(XS[k] + 13, XS[k + 1] - 11, ROW1_Y)
for k in range(5):
    x = XS[4 - k]
    phase_node(x, ROW2_Y, k + 6, final=(k == 4))
    T([x - 57, ROW2_Y + 16, 114, 20], PHASES[k + 5], f=MONO, size=7, color=QUIET,
      align="center", lh=1.25)
    if k < 4:
        h_arrow(x - 13, XS[3 - k] + 11, ROW2_Y)
L.polyline([[XS[4] + 13, ROW1_Y], [604, ROW1_Y], [604, ROW2_Y], [XS[4] + 16, ROW2_Y]],
           **stroke(0.9, color=HAIR))
L.polygon([[XS[4] + 16, ROW2_Y - 3], [XS[4] + 16, ROW2_Y + 3], [XS[4] + 11, ROW2_Y]],
          fill=DIM)

T([628, 868, 178, 52],
  "An unknown framework_version MUST fail with a stable machine-readable error. "
  "Schema selection follows meta.framework_version — never a hard-coded v1.1 path.",
  f=INTER, size=7, color=QUIET, lh=1.35)
T([628, 928, 178, 12], "decision: pass · diagnostic_only · fail", f=DMONO,
  size=7, color=TEAL)

# ---------------------------------------------------------------- 04 · tri-panels
P_Y, P_H, P_W = 978, 136, 243

# Panel 1 — severity
L.rect([36, P_Y, P_W, P_H], fill=PANEL, **stroke(0.8, color=HAIR))
T([48, P_Y + 10, 219, 12], "SEVERITY IS LAW", f=ISB, size=8.7, color=PAPER,
  ls="0.14em")
SEVS = [
    ("FATAL", "validation & generation stop — no profile may downgrade it",
     "fill_accent"),
    ("UNSAFE", "generation inadequate — diagnostic artifact only, with explicit "
     "attestation", "outline_accent"),
    ("ADVISORY", "does not block; remains in the report", "outline_hair"),
]
for i, (name, desc, kind) in enumerate(SEVS):
    sy = P_Y + 26 + i * 30
    if kind == "fill_accent":
        L.rect([48, sy, 219, 24], fill=ACCENT)
        nc, dc = GROUND, GROUND
    elif kind == "outline_accent":
        L.rect([48, sy, 219, 24], fill=ACC_DIM, **stroke(1.1, color=ACCENT))
        nc, dc = ACCENT, QUIET
    else:
        L.rect([48, sy, 219, 24], fill=PANEL2, **stroke(0.9, color=HAIR))
        nc, dc = QUIET, QUIET
    T([56, sy + 7.5, 52, 12], name, f=SG, size=8.7, color=nc, weight=700)
    T([112, sy + 3.5, 150, 18], desc, f=INTER, size=5.6, color=dc, lh=1.25)
T([48, P_Y + 118, 219, 9],
  "gap = classification, not severity · blocks applicable adequacy",
  f=DMONO, size=5.6, color=DIM)
T([48, P_Y + 127, 219, 9], "secrets as literal values → ALWAYS FATAL", f=DMONO,
  size=5.6, color=ACCENT)

# Panel 2 — determinism
P2X = 299.5
L.rect([P2X, P_Y, P_W, P_H], fill=PANEL, **stroke(0.8, color=HAIR))
T([P2X + 12, P_Y + 10, 219, 12], "THREE GRADES OF DETERMINISM", f=ISB, size=8.7,
  color=PAPER, ls="0.14em")
BCX, BCY = P2X + 70, P_Y + 66
L.circle(center=[BCX, BCY], r=40, fill="none", **stroke(8, color=TEAL_D1))
L.circle(center=[BCX, BCY], r=27, fill="none", **stroke(8, color=TEAL_D2))
L.circle(center=[BCX, BCY], r=13, fill=TEAL_D3)
GRADES = [
    ("observational", "external observations equivalent", -42, 40),
    ("structural", "+ stable file, route, migration & test sets", -10, 27),
    ("byte_reproducible", "+ byte identity", 28, 13),
]
for gi, (name, desc, ang, rad) in enumerate(GRADES):
    a = math.radians(ang)
    ex = BCX + rad * math.cos(a)
    ey = BCY + rad * math.sin(a)
    ly = P_Y + 30 + gi * 26
    L.polyline([[ex, ey], [P2X + 128, ly + 4]], **stroke(0.6, color=DIM),
               opacity=0.8)
    T([P2X + 132, ly, 100, 9], name, f=MONO, size=7, color=PAPER)
    T([P2X + 132, ly + 9, 100, 16], desc, f=INTER, size=5.6, color=QUIET, lh=1.25)
T([P2X + 12, P_Y + 114, 219, 18],
  "Same spec + profile + imports + seed → the same artifact. No undeclared "
  "entropy, wall-clock, environment, or network.",
  f=INTER, size=5.6, color=QUIET, lh=1.3)

# Panel 3 — anti-degeneracy
P3X = 563
L.rect([P3X, P_Y, P_W, P_H], fill=PANEL, **stroke(0.8, color=HAIR))
T([P3X + 12, P_Y + 10, 219, 12], "THE ANTI-DEGENERACY RULE", f=ISB, size=8.7,
  color=PAPER, ls="0.14em")
T([P3X + 12, P_Y + 24, 219, 15], "A JOB RECEIPT IS", f=SG, size=13.7, color=PAPER,
  weight=700)
T([P3X + 12, P_Y + 37, 219, 30], "NOT", f=SG, size=26.7, color=ACCENT, weight=700)
T([P3X + 12, P_Y + 66, 219, 15], "A DOMAIN OUTCOME.", f=SG, size=13.7, color=PAPER,
  weight=700)
T([P3X + 12, P_Y + 84, 219, 9], "an asynchronous command declares —", f=INTER,
  size=5.6, color=QUIET)
T([P3X + 16, P_Y + 92, 210, 10], "δD  its domain intention", f=DMONO, size=7,
  color=TEAL)
T([P3X + 16, P_Y + 102, 210, 10], "δW  its execution contract", f=DMONO, size=7,
  color=TEAL)
T([P3X + 16, P_Y + 112, 210, 10], "P   usually, a provenance result", f=DMONO,
  size=7, color=TEAL)
L.rect([P3X + 12, P_Y + 122, 219, 13], fill=PANEL2, **stroke(0.8, color=HAIR))
T([P3X + 12, P_Y + 125.5, 219, 8],
  "RFC 8785 JCS · UTF-8 · NFC · sha256 over canonical bytes",
  f=DMONO, size=5.6, color=PAPER, align="center")

# ---------------------------------------------------------------- footer
hairline(MX, 1126, CW)
T([MX, 1132, 500, 10],
  "SOURCE — backend_spec_v2_0_0.md + companion artifacts: instance · profile · "
  "validation-report · change-manifest · rules schemas + law catalog",
  f=INTER, size=5.6, color=DIM)
T([MX, 1141, 500, 10],
  "predecessors: backend_spec.schema.v1.1.0 · backend_spec_v1_2_0 draft — v2.0.0 "
  "proposed 2026-07-20",
  f=INTER, size=5.6, color=DIM)
T([556, 1132, 250, 10], "GENERATED BY Claude Fable 5 · FrameForge SDK",
  f=INTER, size=5.6, color=DIM, align="right")
T([556, 1141, 250, 10], "verified against rendered pixels — PALS's LAW",
  f=INTER, size=5.6, color=DIM, align="right")
T([MX, 1154, CW, 9],
  "sha256  3b6a9cb52cfe1946…d86757624f9dedf6 · bdc23471cffb04ff…0709dc422b3da40b9 "
  "· b39a73b73b2f90ba…8318f5660c95dc — source anchors, not percentages",
  f=DMONO, size=5.6, color=DIM, opacity=0.85)


def build():
    return doc
