"""CONVERGENCE — the Pedro Anisio personal design system, rendered in itself.

A complete FrameForge interpretation of ``_tmp/PALS.md``: all 23 sections of
the spec (identity, principles, visual architecture, color, gradients,
typography, hierarchy, space, surfaces, component philosophy, the fifteen core
components, states, buttons, iconography, data visualization, motion, content
design, navigation, modes, accessibility, governance, anti-patterns, and the
closing statement) typeset as a 21-page dark deck that OBEYS the rules it
documents — its own tokens, its three faces, its radii, spacing and semantic
color duties.

Generated by Claude Opus 4.8 via the FrameForge SDK.
Source document: _tmp/PALS.md (CONVERGENCE / PEDRO.SYSTEM v1.0).
"""
import math

from frameforge.sdk import DocumentBuilder
from frameforge.sdk.paint import linear_gradient, radial_gradient, rgba, stroke

# ---------------------------------------------------------------- tokens (§22)
W, H = 1600, 1000
MX = 80                       # page margin -> 1440 content width (§7 grid)
INK1000 = "#080C14"
INK950 = "#0D1320"
INK900 = "#131C2C"
INK800 = "#1C283B"
BONE100 = "#F4F6F2"
BONE300 = "#CDD3D8"
SLATE = "#718096"
CYAN = "#3DD5E7"              # evidence, validation, connection
CORAL = "#FF4F40"             # decision, urgency, contradiction
VIOLET = "#8067FF"            # exploration, AI, emerging capability
AMBER = "#F4B942"             # pending, uncertain, requires review
MINT = "#58D6A9"              # completed, healthy, verified
B_SUB = rgba(BONE300, 0.12)   # --border-subtle
B_STR = rgba(BONE300, 0.28)   # --border-strong
B_EVD = rgba(CYAN, 0.56)      # --border-evidence

UI = "Inter"
UID = "Inter Display"
ED = "Source Serif 4"
MONO = "IBM Plex Mono"

PAGES = 21

doc = DocumentBuilder(title="CONVERGENCE — Pedro Anisio Design System",
                      profile="diagram")


# ---------------------------------------------------------------- helpers
def gc(i, span):
    """12-col grid (§7): column i (0-based), spanning `span` columns."""
    cw = (1440 - 11 * 24) / 12.0
    return MX + i * (cw + 24), span * cw + (span - 1) * 24


def T(L, box, s, size=15.5, color=BONE300, weight=400, family=UI,
      align="left", lh=1.5, ls=None, opacity=None):
    st = {"font_family": family, "size": size, "color": color,
          "weight": weight, "align": align, "line_height": lh}
    if ls is not None:
        st["letter_spacing"] = ls
    if isinstance(s, str) and "\n" in s:
        st["white_space"] = "pre-line"
    kw = {}
    if opacity is not None:
        kw["opacity"] = opacity
    L.text(box, s, style=st, **kw)


def mono(L, box, s, size=11, color=SLATE, weight=500, align="left",
        ls="0.04em", lh=1.35):
    T(L, box, s, size=size, color=color, weight=weight, family=MONO,
      align=align, ls=ls, lh=lh)


def lbl(L, box, s, color=CYAN, size=11, align="left"):
    """§6 label: uppercase, tracked, compact."""
    T(L, box, s.upper(), size=size, color=color, weight=600, ls="0.12em",
      align=align, lh=1.2)


def card(L, box, fill=INK900, r=16, border=B_SUB, accent=None, bw=1.2):
    L.rect(box, fill=fill, radius=r, **stroke(bw, color=border))
    if accent:                          # semantic top border (§10)
        x, y, w, _ = box
        L.rect([x + r, y, w - 2 * r, 3], fill=accent)


def chip(L, x, y, s, color, w=None, h=26, fill=None, size=11):
    w = w or (len(s) * size * 0.72 + 26)
    L.rect([x, y, w, h], fill=fill or rgba(color, 0.10), radius=8,
           **stroke(1, color=rgba(color, 0.45)))
    lbl(L, [x, y + h / 2 - 7, w, 14], s, color=color, size=size,
        align="center")
    return w


def button(L, x, y, w, s, kind="primary"):
    fills = {"primary": CORAL, "system": CYAN, "exploratory": VIOLET}
    if kind in fills:
        L.rect([x, y, w, 40], fill=fills[kind], radius=12)
        tcol = BONE100 if kind == "exploratory" else INK1000
        T(L, [x, y + 11, w, 18], s, size=14, color=tcol, weight=600,
          align="center", lh=1.2)
    elif kind == "secondary":
        L.rect([x, y, w, 40], fill=rgba(BONE300, 0.04), radius=12,
               **stroke(1.2, color=B_STR))
        T(L, [x, y + 11, w, 18], s, size=14, color=BONE300, weight=500,
          align="center", lh=1.2)
    else:                               # destructive: outlined coral
        L.rect([x, y, w, 40], fill=rgba(CORAL, 0.08), radius=12,
               **stroke(1.4, color=rgba(CORAL, 0.7), dash=[5, 4]))
        T(L, [x, y + 11, w, 18], s, size=14, color=CORAL, weight=600,
          align="center", lh=1.2)


def tick(L, x, y, color=MINT, s=1.0):
    L.polyline([[x, y + 5 * s], [x + 4.5 * s, y + 9.5 * s],
                [x + 12 * s, y]], **stroke(2.2 * s, color=color,
                                           cap="round", join="round"))


def cross(L, x, y, color=CORAL, s=1.0):
    L.line([x, y], [x + 10 * s, y + 10 * s],
           **stroke(2.2 * s, color=color, cap="round"))
    L.line([x + 10 * s, y], [x, y + 10 * s],
           **stroke(2.2 * s, color=color, cap="round"))


def arrow(L, x1, y1, x2, y2, color=BONE300, w=2.0, head=7.0):
    L.line([x1, y1], [x2, y2], **stroke(w, color=color, cap="round"))
    ang = math.atan2(y2 - y1, x2 - x1)
    for da in (2.65, -2.65):
        L.line([x2, y2], [x2 + head * math.cos(ang + da),
                          y2 + head * math.sin(ang + da)],
               **stroke(w, color=color, cap="round"))


def arc(L, cx, cy, r, a0, a1, color=BONE100, w=3.0, n=48, dash=None):
    pts = []
    for k in range(n + 1):
        a = math.radians(a0 + (a1 - a0) * k / n)
        pts.append([cx + r * math.cos(a), cy + r * math.sin(a)])
    L.polyline(pts, **stroke(w, color=color, cap="round", dash=dash))


def mark(L, cx, cy, r, lw=None, exit_len=None):
    """§13 signature symbol: a partially open convergence loop — independent
    paths entering a shared structure, one path continuing outward as action."""
    lw = lw or max(r * 0.055, 1.6)
    exit_len = exit_len if exit_len is not None else r * 1.35
    arc(L, cx, cy, r, 28, 332, color=BONE100, w=lw)     # open on the right
    feeds = [(148, CYAN), (180, VIOLET), (212, AMBER), (116, MINT),
             (244, SLATE)]
    for a, c in feeds:
        th = math.radians(a)
        x0, y0 = cx + r * 1.85 * math.cos(th), cy + r * 1.85 * math.sin(th)
        x1, y1 = cx + r * 1.06 * math.cos(th), cy + r * 1.06 * math.sin(th)
        L.line([x0, y0], [x1, y1], **stroke(lw, color=c, cap="round"))
        L.circle([x0, y0], lw * 1.35, fill=c)
    ex = math.radians(0)
    x0 = cx + r * math.cos(math.radians(20))
    y0 = cy + r * math.sin(math.radians(-0)) * 0
    arrow(L, cx + r * 0.9, cy, cx + r + exit_len, cy, color=CORAL, w=lw,
          head=lw * 3.2)


def chrome(name, idx, label, thesis, sub=None, tsize=42, tw=1250, tlines=1):
    """Page chrome per §6/§7: mono system strip, tracked label, thesis head."""
    page = doc.page(name, canvas={"size": [W, H]}, coordinate_mode="absolute")
    bg = page.layer("bg")
    L = page.layer("content")
    bg.rect([0, 0, W, H], fill=INK950)
    mono(L, [MX, 46, 700, 14], "CONVERGENCE / PEDRO.SYSTEM v1.0",
        size=10.5, ls="0.08em")
    mono(L, [W - MX - 300, 46, 300, 14], f"{idx:02d} / {PAGES}",
        size=10.5, align="right", ls="0.08em")
    L.line([MX, 74], [W - MX, 74], **stroke(1, color=B_SUB))
    lbl(L, [MX, 102, 900, 14], label)
    th = tsize * 1.12 * tlines
    T(L, [MX, 130, tw, th], thesis, size=tsize, color=BONE100, weight=600,
      lh=1.12, family=UID)
    y = 130 + th + 10
    if sub:
        T(L, [MX, y, 1100, 26], sub, size=16.5, color=BONE300, weight=400,
          lh=1.5)
        y += 36
    L.line([MX, 934], [W - MX, 934], **stroke(1, color=B_SUB))
    mono(L, [MX, 950, 980, 13],
        "TRUTH AT THE CORE · EXPRESSION AT THE EDGE · ACTION AT THE END",
        size=10, ls="0.1em")
    mono(L, [W - MX - 460, 950, 460, 13],
        "SOURCE _tmp/PALS.md · 2026-07-22", size=10, align="right")
    return L, y + 14


def field_row(L, x, y, w, k, v, kcol=SLATE, vcol=BONE300, size=12.5):
    mono(L, [x, y, 132, 15], k.upper(), size=10.5, ls="0.08em")
    T(L, [x + 140, y - 1, w - 140, 17], v, size=size, color=vcol, weight=450,
      lh=1.3)


# ================================================================ 01 · cover
page = doc.page("cover", canvas={"size": [W, H]}, coordinate_mode="absolute")
bg = page.layer("bg")
L = page.layer("content")
bg.rect([0, 0, W, H], fill=INK1000)
# a restrained emergence whisper (the edge, kept at the edge)
bg.rect([0, 0, W, H], fill=radial_gradient(
    [(rgba(CYAN, 0.10), 0), (rgba(CYAN, 0.0), 0.60)], at="22% 12%"))
bg.rect([0, 0, W, H], fill=radial_gradient(
    [(rgba(VIOLET, 0.10), 0), (rgba(VIOLET, 0.0), 0.55)], at="82% 78%"))

mono(L, [MX, 54, 700, 15], "CONVERGENCE / SYSTEM 01", size=11.5,
    color=BONE300, ls="0.14em")
mono(L, [W - MX - 400, 54, 400, 15], "PEDRO.SYSTEM / v1.0", size=11.5,
    align="right", ls="0.14em")
L.line([MX, 84], [W - MX, 84], **stroke(1, color=B_STR))

mark(L, 800, 236, 92)
mono(L, [800 + 92 * 0.9 + 132, 218, 90, 13], "ACTION", size=10,
    color=CORAL, ls="0.14em")

T(L, [0, 408, W, 100], "CONVERGENCE", size=92, color=BONE100, weight=650,
  align="center", family=UID, lh=1.0, ls="0.02em")
T(L, [0, 528, W, 76],
  "Complex systems should not become simpler.\nThey should become legible.",
  size=27, color=BONE300, weight=350, align="center", family=ED, lh=1.4)
T(L, [0, 636, W, 24],
  "A design system for synthesis, evidence, invention, and execution.",
  size=17, color=SLATE, weight=400, align="center", lh=1.5)

qw = 760
L.rect([(W - qw) / 2, 700, qw, 52], fill=rgba(BONE300, 0.035), radius=12,
       **stroke(1, color=B_SUB))
mono(L, [(W - qw) / 2, 718, qw, 15],
    "TRUTH AT THE CORE · EXPRESSION AT THE EDGE · ACTION AT THE END",
    size=11.5, color=BONE300, align="center", ls="0.12em")

# metadata strip (§23: version, state, confidence, source, ownership, date)
META = [("VERSION", "1.0.0"), ("STATE", "proposed"),
        ("CONFIDENCE", "0.87"), ("SOURCE", "_tmp/PALS.md"),
        ("OWNER", "Pedro Anisio"), ("DATE", "2026-07-22")]
mw = 1440 / 6.0
L.line([MX, 828], [W - MX, 828], **stroke(1, color=B_SUB))
for i, (k, v) in enumerate(META):
    x = MX + i * mw
    if i:
        L.line([x, 840], [x, 892], **stroke(1, color=B_SUB))
    mono(L, [x + 22, 846, mw - 30, 13], k, size=10, ls="0.12em")
    mono(L, [x + 22, 866, mw - 30, 16], v, size=12.5, color=BONE100,
        weight=500)
L.line([MX, 906], [W - MX, 906], **stroke(1, color=B_SUB))
mono(L, [MX, 948, 1200, 13],
    "A HIGH-DENSITY OPERATING SYSTEM FOR TURNING COMPLEXITY INTO COHERENT ACTION",
    size=10, ls="0.1em")

# ================================================================ 02 · identity
L, cy = chrome("identity", 2, "01 · System identity",
               "Convergence without collapse",
               "Multiple independent forces become one coherent system — "
               "each preserves its identity inside a larger structure.")
# left: positioning + personality coordinates
T(L, [MX, 262, 620, 68],
  "A design system for synthesis, evidence,\ninvention, and execution.",
  size=21, color=BONE100, weight=450, family=ED, lh=1.45)
mono(L, [MX, 342, 400, 14], "ALTERNATIVE DESIGNATION  PEDRO.SYSTEM / v1.0",
    size=10.5, ls="0.08em")

lbl(L, [MX, 396, 400, 14], "Personality coordinates")
PERS = [("Rational", "Structured, explicit, inspectable"),
        ("Creative", "Authorial, surprising, expressive at the edges"),
        ("Executive", "Restrained, decisive, confident"),
        ("Technical", "Precise, stateful, evidence-backed"),
        ("Experimental", "Open to untested possibilities"),
        ("Human", "Direct, constructive, never sterile"),
        ("Ambitious", "Platform-scale thinking"),
        ("Grounded", "Every idea must eventually become an artifact")]
for i, (dim, expr) in enumerate(PERS):
    y = 426 + i * 56
    L.line([MX, y + 44], [MX + 640, y + 44], **stroke(1, color=B_SUB))
    T(L, [MX, y + 8, 170, 20], dim, size=15, color=BONE100, weight=600)
    T(L, [MX + 190, y + 9, 450, 20], expr, size=13.5, color=BONE300, lh=1.35)

# right: the convergence diagram — eight forces, one structure, one action
DX, DY, DR = 1268, 566, 84
FORCES = [("business", CYAN), ("technology", CYAN), ("design", VIOLET),
          ("AI", VIOLET), ("architecture", BONE300), ("strategy", BONE300),
          ("implementation", MINT), ("evidence", MINT)]
lbl(L, [860, 268, 400, 14], "Core metaphor", color=SLATE)
for i, (name, c) in enumerate(FORCES):
    fy = 320 + i * 62
    L.circle([880, fy], 4.5, fill=c)
    T(L, [898, fy - 9, 150, 16], name, size=13.5, color=BONE300, weight=500)
    # converge toward the ring edge
    th = math.atan2(DY - fy, DX - 880)
    ex = DX - (DR + 8) * math.cos(th)
    ey = DY - (DR + 8) * math.sin(th)
    L.line([1052, fy], [ex, ey], **stroke(1.3, color=rgba(c, 0.5),
                                          cap="round"))
arc(L, DX, DY, DR, 28, 332, color=BONE100, w=4.5)
T(L, [DX - 70, DY - 22, 140, 44], "one\nsystem", size=14, color=BONE100,
  weight=600, align="center", lh=1.25)
arrow(L, DX + DR * 0.9, DY, DX + DR + 130, DY, color=CORAL, w=4.0, head=13)
mono(L, [DX + DR - 26, DY + 22, 200, 13], "ACTION", size=10, color=CORAL,
    ls="0.14em")

# ================================================================ 03 · principles
L, cy = chrome("principles", 3, "02 · Foundational principles",
               "Truth before appearance",
               "A beautiful component cannot hide an incomplete model. "
               "Five principles with zero exceptions.")
PRIN = [("2.1", "Truth before appearance",
         "Every important claim exposes source, confidence, assumptions, "
         "dependencies, state, owner, next action.", CYAN),
        ("2.2", "Complexity is layered, not removed",
         "The system never pretends complex things are simple — it reveals "
         "them progressively.", VIOLET),
        ("2.3", "Every surface moves toward action",
         "Each screen, card, diagram and document answers a question that "
         "changes what happens next.", CORAL),
        ("2.4", "Components are semantic, not decorative",
         "A card is not just a rectangle. It carries a defined role.", AMBER),
        ("2.5", "Freedom without loss of coherence",
         "Tokens, constraints and primitives provide coherence. They do not "
         "dictate authorship.", MINT)]
cw = (1440 - 4 * 24) / 5.0
for i, (num, title, body, c) in enumerate(PRIN):
    x = MX + i * (cw + 24)
    card(L, [x, 262, cw, 210], accent=c)
    mono(L, [x + 20, 282, 60, 14], num, size=11, color=c, weight=600)
    T(L, [x + 20, 306, cw - 40, 66], title, size=16, color=BONE100,
      weight=600, lh=1.28)
    T(L, [x + 20, 380, cw - 40, 78], body, size=12.5, color=BONE300, lh=1.42)

# bottom-left: progressive levels (2.2)
bx, bw = MX, 452
lbl(L, [bx, 512, 400, 14], "Progressive levels", color=VIOLET)
LEVELS = [("1", "Signal", "what matters now"),
          ("2", "Structure", "how it works"),
          ("3", "Evidence", "why it is believed"),
          ("4", "System", "how everything connects"),
          ("5", "Source", "the underlying data or implementation")]
for i, (n, name, what) in enumerate(LEVELS):
    y = 544 + i * 70
    ind = i * 26
    L.rect([bx + ind, y, bw - ind, 56], fill=INK900, radius=8,
           **stroke(1, color=B_SUB))
    mono(L, [bx + ind + 16, y + 21, 20, 14], n, size=11, color=VIOLET,
        weight=600)
    T(L, [bx + ind + 44, y + 9, 130, 18], name, size=14.5, color=BONE100,
      weight=600)
    T(L, [bx + ind + 44, y + 29, bw - ind - 60, 16], what, size=11.5,
      color=SLATE, lh=1.3)

# bottom-middle: the five questions (2.3)
qx, qw = MX + 492, 452
lbl(L, [qx, 512, 400, 14], "Every surface answers", color=CORAL)
QS = ["What is happening?", "Why does it matter?", "What is uncertain?",
      "What decision is needed?", "What happens next?"]
card(L, [qx, 544, qw, 346], fill=INK900, r=16)
for i, q in enumerate(QS):
    y = 576 + i * 62
    L.circle([qx + 34, y + 9], 3.5, fill=CORAL)
    T(L, [qx + 54, y, qw - 80, 22], q, size=16.5, color=BONE100, weight=500,
      family=ED, lh=1.3)
    if i < 4:
        L.line([qx + 24, y + 38], [qx + qw - 24, y + 38],
               **stroke(1, color=B_SUB))

# bottom-right: semantic roles (2.4)
rx, rw = MX + 984, 456
lbl(L, [rx, 512, 400, 14], "Semantic roles a card may carry", color=AMBER)
ROLES = ["assertion", "evidence", "decision", "capability", "risk",
         "experiment", "artifact", "dependency", "contradiction",
         "next action"]
x, y = rx, 548
for r_ in ROLES:
    wpx = len(r_) * 7.6 + 34
    if x + wpx > rx + rw:
        x = rx
        y += 40
    chip(L, x, y, r_, BONE300, w=wpx, fill=rgba(BONE300, 0.05))
    x += wpx + 12
T(L, [rx, y + 62, rw, 66],
  "A generic card without one of these roles is an anti-pattern (§21).",
  size=12.5, color=SLATE, lh=1.5)

# ================================================================ 04 · core/edge
L, cy = chrome("architecture", 4, "03 · Visual architecture",
               "Two layers: the core and the edge",
               "Closer to truth and operation: more restrained. Closer to "
               "possibility and exploration: more expressive.")
py, ph = 268, 560
# THE CORE — controlled, dark, rigorous, sharp geometry (§7 rule)
card(L, [MX, py, 700, ph], fill=INK1000, r=8, border=B_STR)
lbl(L, [MX + 36, py + 34, 300, 14], "The core", color=CYAN)
T(L, [MX + 36, py + 60, 620, 30], "Controlled. Dark. Rigorous. Stable.",
  size=21, color=BONE100, weight=600)
CORE_USES = ["strategy", "executive communication", "systems",
             "architecture", "evidence", "product interfaces",
             "operational dashboards"]
for i, u in enumerate(CORE_USES):
    y = py + 122 + i * 44
    L.line([MX + 36, y + 30], [MX + 664, y + 30], **stroke(1, color=B_SUB))
    mono(L, [MX + 36, y + 4, 30, 14], f"{i+1:02d}", size=10.5, color=SLATE)
    T(L, [MX + 84, y + 2, 540, 18], u, size=14.5, color=BONE300, weight=500)
mono(L, [MX + 36, py + ph - 44, 620, 14],
    "GEOMETRY 8PX · GRADIENTS NONE · ONE SIGNAL COLOR", size=10,
    color=SLATE, ls="0.1em")

# THE EDGE — energetic, experimental, soft geometry + emergence field
ex = MX + 740
L.rect([ex, py, 700, ph], fill=INK950, radius=32,
       **stroke(1.4, color=rgba(VIOLET, 0.5)))
L.rect([ex, py, 700, ph], radius=32, fill=radial_gradient(
    [(rgba(CYAN, 0.32), 0), (rgba(CYAN, 0.0), 0.42)], at="25% 20%"))
L.rect([ex, py, 700, ph], radius=32, fill=radial_gradient(
    [(rgba(VIOLET, 0.28), 0), (rgba(VIOLET, 0.0), 0.45)], at="80% 70%"))
lbl(L, [ex + 36, py + 34, 300, 14], "The edge", color=VIOLET)
T(L, [ex + 36, py + 60, 620, 30], "Energetic. Experimental. Expressive.",
  size=21, color=BONE100, weight=600)
EDGE_USES = ["labs", "hypotheses", "explorations", "emerging capabilities",
             "generative visuals", "speculative concepts",
             "creative computation"]
for i, u in enumerate(EDGE_USES):
    y = py + 122 + i * 44
    L.line([ex + 36, y + 30], [ex + 664, y + 30],
           **stroke(1, color=rgba(VIOLET, 0.18)))
    mono(L, [ex + 36, y + 4, 30, 14], f"{i+1:02d}", size=10.5,
        color=rgba(VIOLET, 0.9))
    T(L, [ex + 84, y + 2, 540, 18], u, size=14.5, color=BONE300, weight=500)
mono(L, [ex + 36, py + ph - 44, 620, 14],
    "GEOMETRY 32PX · GRADIENTS PERMITTED · UNCERTAINTY VISIBLE", size=10,
    color=rgba(VIOLET, 0.9), ls="0.1em")

T(L, [0, 862, W, 30],
  "Restraint is proximity to truth. Expression is proximity to possibility.",
  size=19, color=BONE300, weight=400, family=ED, align="center", lh=1.4)

# ================================================================ 05 · color
L, cy = chrome("color", 5, "04 · Color system",
               "Colors do not decorate. They communicate state.",
               "Twelve tokens, seven duties, one distribution law — only one "
               "signal color may dominate a composition.")
TOKENS = [("ink-1000", INK1000, "Absolute foundation"),
          ("ink-950", INK950, "Primary background"),
          ("ink-900", INK900, "Elevated surface"),
          ("ink-800", INK800, "Interactive surface"),
          ("bone-100", BONE100, "Primary foreground"),
          ("bone-300", BONE300, "Secondary foreground"),
          ("slate-500", SLATE, "Metadata and quiet information"),
          ("signal-cyan", CYAN, "Evidence, validation, connection"),
          ("action-coral", CORAL, "Decision, urgency, contradiction"),
          ("possibility-violet", VIOLET, "Exploration, AI, emerging"),
          ("attention-amber", AMBER, "Pending, uncertain, review"),
          ("success-mint", MINT, "Completed, healthy, verified")]
for i, (name, hexv, meaning) in enumerate(TOKENS):
    colx = MX + (i // 6) * 466
    y = 268 + (i % 6) * 106
    L.rect([colx, y, 440, 92], fill=INK900, radius=16,
           **stroke(1, color=B_SUB))
    L.rect([colx + 16, y + 16, 84, 60], fill=hexv, radius=8,
           **stroke(1, color=B_STR))
    mono(L, [colx + 116, y + 16, 200, 15], name, size=12.5, color=BONE100,
        weight=600)
    mono(L, [colx + 116, y + 37, 120, 14], hexv.upper(), size=11)
    T(L, [colx + 116, y + 58, 310, 16], meaning, size=12, color=BONE300,
      lh=1.3)

# right rail: distribution + behavior
rx = MX + 952
lbl(L, [rx, 268, 400, 14], "Distribution")
segs = [(0.70, INK800), (0.20, BONE300), (0.10, CYAN)]
x = rx
for frac, c in segs:
    L.rect([x, 298, 488 * frac, 30], fill=c, **stroke(1, color=B_STR))
    x += 488 * frac
mono(L, [rx, 340, 500, 13],
    "70% DARK NEUTRAL · 20% LIGHT INFO · 10% SIGNAL", size=9.5,
    ls="0.06em")
lbl(L, [rx, 388, 400, 14], "Semantic duties")
BEHAV = [(CYAN, "Cyan", "known · connected · measured · verified"),
         (CORAL, "Coral", "action · conflict · risk · breaking change"),
         (VIOLET, "Violet", "hypothesis · possibility · AI-generated"),
         (AMBER, "Amber", "uncertainty · review · unresolved dependency"),
         (MINT, "Mint", "validated · released · functioning"),
         (SLATE, "Gray", "inactive · historical · secondary"),
         (BONE100, "White", "primary meaning · intellectual focus")]
for i, (c, name, duty) in enumerate(BEHAV):
    y = 420 + i * 56
    L.circle([rx + 10, y + 10], 7, fill=c)
    T(L, [rx + 32, y, 90, 18], name, size=14, color=BONE100, weight=600)
    T(L, [rx + 32, y + 22, 456, 16], duty, size=12, color=BONE300, lh=1.3)
    if i < 6:
        L.line([rx, y + 44], [rx + 488, y + 44], **stroke(1, color=B_SUB))
T(L, [rx, 828, 488, 60],
  "Only one signal color dominates a composition. Other accents remain "
  "contextual.", size=12.5, color=SLATE, lh=1.5)

# ================================================================ 06 · gradients
L, cy = chrome("gradients", 6, "04 · Gradients",
               "Gradients indicate emergence — never settled truth",
               "They belong to the experimental edge, not to core "
               "operational interfaces.")
# intelligence gradient
gx, gy, gw2, gh = MX, 272, 660, 190
lbl(L, [gx, gy - 26, 400, 14], "Intelligence gradient", color=VIOLET)
L.rect([gx, gy, gw2, gh], radius=32, fill=linear_gradient(
    [("#3DD5E7", 0), ("#8067FF", 0.52), ("#FF4F80", 1.0)], angle=120))
card(L, [gx, gy + gh + 24, gw2, 128], fill=INK1000, r=8)
mono(L, [gx + 24, gy + gh + 44, gw2 - 48, 90],
    "linear-gradient(\n  120deg,\n  #3DD5E7 0%, #8067FF 52%, #FF4F80 100%\n)",
    size=12, color=CYAN, lh=1.6)

# emergence field
ex2 = MX + 740
lbl(L, [ex2, gy - 26, 400, 14], "Emergence field", color=VIOLET)
L.rect([ex2, gy, 700, 342], fill=INK950, radius=32,
       **stroke(1.2, color=B_SUB))
L.rect([ex2, gy, 700, 342], radius=32, fill=radial_gradient(
    [(rgba(CYAN, 0.32), 0), (rgba(CYAN, 0.0), 0.42)], at="25% 20%"))
L.rect([ex2, gy, 700, 342], radius=32, fill=radial_gradient(
    [(rgba(VIOLET, 0.28), 0), (rgba(VIOLET, 0.0), 0.45)], at="80% 70%"))
mono(L, [ex2 + 28, gy + 270, 640, 48],
    "radial 25% 20% rgba(61,213,231,.32) → 42%\nradial 80% 70% "
    "rgba(128,103,255,.28) → 45%", size=11.5, color=BONE300, lh=1.7)

# what gradients mean
iy = 668
lbl(L, [MX, iy, 500, 14], "A gradient may indicate", color=VIOLET)
IND = ["emergence", "ambiguity", "transition", "generative space",
       "multiple forces interacting"]
x = MX
for s in IND:
    x += chip(L, x, iy + 30, s, VIOLET, h=32) + 14
cross(L, MX + 6, iy + 96, color=CORAL)
T(L, [MX + 32, iy + 88, 900, 22],
  "Never settled truth — and never on core operational interfaces.",
  size=15.5, color=BONE300, weight=500, lh=1.4)

# ================================================================ 07 · typography
L, cy = chrome("typography", 7, "05 · Typography",
               "Three voices: command, authorship, evidence",
               "Each face carries one part of the identity — none substitutes "
               "for another.")
SPEC = [("Inter Variable", UI, "Primary interface", CYAN,
         "interfaces · dashboards · diagrams · navigation · product "
         "documentation · executive summaries",
         "Systems-oriented, direct communication.",
         'font-feature-settings:\n"cv02","cv03","cv04","cv11"'),
        ("Source Serif 4", ED, "Editorial", AMBER,
         "theses · long-form writing · manifestos · strategic documents · "
         "quotations · reflective passages",
         "Intellectual depth without an academic aesthetic.",
         "variable wght 200–900\noptical size 8–60"),
        ("IBM Plex Mono", MONO, "Evidence", MINT,
         "provenance · source refs · IDs · timestamps · system states · "
         "versions · confidence values",
         "Never used for long body copy.",
         "tabular rhythm\none advance width")]
cw = (1440 - 2 * 32) / 3.0
for i, (name, fam, role, c, uses, note, feat) in enumerate(SPEC):
    x = MX + i * (cw + 32)
    card(L, [x, 268, cw, 606], accent=c)
    T(L, [x + 32, 300, cw - 64, 120], "Ag", size=104, color=BONE100,
      weight=550, family=fam, lh=1.0)
    lbl(L, [x + 32, 436, cw - 64, 14], role, color=c)
    T(L, [x + 32, 462, cw - 64, 30], name, size=23, color=BONE100,
      weight=600, family=fam)
    T(L, [x + 32, 506, cw - 64, 84], uses, size=13, color=BONE300, lh=1.55)
    L.line([x + 32, 608], [x + cw - 32, 608], **stroke(1, color=B_SUB))
    T(L, [x + 32, 626, cw - 64, 44], note, size=14.5, color=BONE100,
      weight=500, family=fam, lh=1.45)
    card(L, [x + 32, 700, cw - 64, 96], fill=INK1000, r=8)
    mono(L, [x + 52, 722, cw - 104, 60], feat, size=11.5, color=c, lh=1.65)
    sample = {0: "The system assembles and operates the solution.",
              1: "Every idea must eventually become an artifact.",
              2: "conf 0.96 · sha256 2829b7e · 2026-07-22T09:00Z"}[i]
    T(L, [x + 32, 820, cw - 64, 40], sample, size=13, color=SLATE,
      family=fam, lh=1.5)

# ================================================================ 08 · hierarchy
L, cy = chrome("hierarchy", 8, "06 · Typographic hierarchy",
               "A heading states a thesis, not a label",
               "Dramatic differences in scale; compact vertical rhythm.")
LADDER = [("Display Thesis", 60, 650, "72–96 · 650 · 0.98"),
          ("Page Thesis", 44, 650, "48–64 · 650 · 1.02"),
          ("Section Title", 32, 620, "32–40 · 620 · 1.10"),
          ("Component Title", 21, 600, "20–24 · 600 · 1.20"),
          ("Lead", 19, 420, "20 · 420 · 1.50"),
          ("Body", 15.5, 400, "16 · 400 · 1.60"),
          ("Compact Body", 13.5, 430, "14 · 430 · 1.50"),
          ("LABEL", 11.5, 600, "12 · 600 · tracked"),
          ("Metadata", 10.5, 500, "10–11 · 500 · 1.35")]
y = 258
for name, sz, wt, meta in LADDER:
    hgt = max(sz * 1.15, 18)
    fam = UID if sz >= 32 else UI
    ls = "0.12em" if name == "LABEL" else None
    fam2 = MONO if name == "Metadata" else fam
    T(L, [MX, y, 830, hgt], name, size=sz, color=BONE100, weight=wt,
      family=fam2, lh=1.05, ls=ls)
    mono(L, [MX + 860, y + hgt / 2 - 7, 180, 14], meta, size=10.5)
    y += hgt + 22
    L.line([MX, y - 12], [MX + 1020, y - 12], **stroke(1, color=B_SUB))

# right: weak vs strong + signature treatment
rx = MX + 1090
card(L, [rx, 258, 350, 240])
lbl(L, [rx + 26, 282, 300, 14], "Weak — a label", color=CORAL)
T(L, [rx + 26, 306, 300, 26], "Architecture", size=19, color=SLATE,
  weight=600)
L.line([rx + 26, 352], [rx + 324, 352], **stroke(1, color=B_SUB))
lbl(L, [rx + 26, 372, 300, 14], "Strong — a thesis", color=MINT)
T(L, [rx + 26, 396, 300, 80],
  "The architecture must preserve intent across every transformation",
  size=16.5, color=BONE100, weight=600, lh=1.35)

card(L, [rx, 528, 350, 346], fill=INK1000, r=8)
mono(L, [rx + 26, 556, 300, 14], "CONVERGENCE / SYSTEM 01", size=10.5,
    color=BONE300, ls="0.12em")
L.line([rx + 26, 582], [rx + 324, 582], **stroke(1, color=B_STR))
T(L, [rx + 26, 604, 300, 116],
  "Complex systems\nshould not become\nsimpler. They should\nbecome legible.",
  size=20, color=BONE100, weight=600, family=UID, lh=1.28)
mono(L, [rx + 26, 744, 300, 58],
    "the title is large and human;\nthe system around it is small,\nprecise, "
    "machine-like", size=10.5, lh=1.6)

# ================================================================ 09 · space
L, cy = chrome("space", 9, "07 · Spatial system",
               "The more human a surface, the softer it becomes",
               "Base unit 8px. The more technical and evidentiary, the "
               "sharper the geometry.")
# spacing scale
lbl(L, [MX, 268, 400, 14], "Spacing scale · base 8px")
SPACES = [2, 4, 8, 12, 16, 24, 32, 48, 64, 96, 128]
x = MX
for v in SPACES:
    L.rect([x, 298, v, 30], fill=CYAN if v in (8, 24) else INK800,
           **stroke(1, color=B_SUB))
    mono(L, [x - 10, 338, v + 20, 13], str(v), size=10, align="center")
    x += v + 18
DUTY = [("8", "internal alignment"), ("16", "compact relationships"),
        ("24", "component padding"), ("32", "semantic separation"),
        ("48–64", "between sections"), ("96–128", "narrative movements")]
for i, (k, v) in enumerate(DUTY):
    xx = MX + (i % 3) * 232
    yy = 376 + (i // 3) * 26
    mono(L, [xx, yy, 66, 13], k, size=10.5, color=CYAN, weight=600)
    T(L, [xx + 60, yy - 1, 176, 15], v, size=11.5, color=SLATE, lh=1.3)

# corner geometry
lbl(L, [MX, 466, 400, 14], "Corner geometry")
RADII = [("8", 8, "small controls · evidence · code"),
         ("12", 12, "inputs and buttons"),
         ("16", 16, "cards"),
         ("24", 24, "major surfaces — the signature"),
         ("32", 32, "narrative panels")]
for i, (name, r, use) in enumerate(RADII):
    x = MX + i * 148
    sig = r == 24
    L.rect([x, 498, 120, 120], fill=INK900, radius=r,
           **stroke(2 if sig else 1.2, color=B_EVD if sig else B_STR))
    mono(L, [x, 542, 120, 15], f"{name}px", size=12.5,
        color=CYAN if sig else BONE100, weight=600, align="center")
    T(L, [x - 10, 630, 140, 42], use, size=10.5, color=SLATE,
      align="center", lh=1.35)

T(L, [MX, 706, 700, 56],
  "Evidence, code and system internals sharpen to 8px.\nHuman and "
  "exploratory surfaces soften toward 32px.", size=14.5, color=BONE300,
  family=ED, lh=1.55)

# grid
gx2 = MX + 800
lbl(L, [gx2, 268, 400, 14], "Grid · desktop 12 col / max 1440")
gw3, gh3 = 480, 300
gcw = (gw3 - 11 * 10) / 12.0
for i in range(12):
    L.rect([gx2 + i * (gcw + 10), 298, gcw, gh3], fill=rgba(BONE300, 0.05))
domw = 8 * gcw + 7 * 10
L.rect([gx2, 298, domw, gh3], fill="none", radius=4,
       **stroke(1.6, color=B_EVD))
lbl(L, [gx2 + 14, 312, 300, 13], "dominant column", size=10)
railx = gx2 + 8 * (gcw + 10)
L.rect([railx, 298, 4 * gcw + 3 * 10, gh3], fill="none", radius=4,
       **stroke(1.6, color=rgba(AMBER, 0.6)))
lbl(L, [railx + 14, 312, 200, 13], "evidence rail", color=AMBER, size=10)
mono(L, [gx2, 610, 480, 14], "GUTTERS 24–32 · ASYMMETRY ENCOURAGED",
    size=10, ls="0.08em")

lbl(L, [gx2 + 540, 268, 160, 14], "Mobile · 4 col")
for i in range(4):
    L.rect([gx2 + 540 + i * 26, 298, 20, 300], fill=rgba(BONE300, 0.05))
L.rect([gx2 + 540, 298, 98, 300], fill="none", radius=4,
       **stroke(1.2, color=B_STR))
mono(L, [gx2 + 540, 610, 160, 36], "16PX MARGINS\n44PX TARGETS", size=9.5,
    ls="0.06em", lh=1.5)

# hierarchy tree
lbl(L, [gx2, 682, 400, 14], "Surface containment", color=SLATE)
mono(L, [gx2, 710, 620, 150],
    "Foundation\n└── Region\n    └── Surface\n        └── Semantic Component"
    "\n            └── Evidence / Action / State",
    size=12.5, color=BONE300, lh=1.75)

# ================================================================ 10 · surfaces
L, cy = chrome("surfaces", 10, "08 · Surface hierarchy",
               "Elevation is border, contrast and separation — not shadow",
               "Six levels, from application background to blocking "
               "decision.")
# nested demo (left)
nx, ny = MX, 268
L.rect([nx, ny, 700, 600], fill=INK1000, radius=8,
       **stroke(1, color=B_SUB))
mono(L, [nx + 20, ny + 16, 200, 13], "surface-0", size=10.5, color=SLATE)
L.rect([nx + 44, ny + 48, 612, 508], fill=INK950, radius=16,
       **stroke(1, color=B_SUB))
mono(L, [nx + 64, ny + 64, 200, 13], "surface-1", size=10.5, color=SLATE)
L.rect([nx + 88, ny + 96, 250, 180], fill=INK900, radius=16,
       **stroke(1, color=B_SUB))
mono(L, [nx + 108, ny + 112, 200, 13], "surface-2", size=10.5,
    color=BONE300)
T(L, [nx + 108, ny + 140, 210, 60], "Cards and grouped information",
  size=13, color=BONE300, lh=1.45)
L.rect([nx + 368, ny + 96, 250, 180], fill=INK800, radius=16,
       **stroke(1.6, color=B_EVD))
mono(L, [nx + 388, ny + 112, 200, 13], "surface-3", size=10.5, color=CYAN)
T(L, [nx + 388, ny + 140, 210, 60], "Active, selected, expanded",
  size=13, color=BONE100, weight=500, lh=1.45)
# floating
L.rect([nx + 196, ny + 320, 300, 108], fill=INK800, radius=16,
       **stroke(1.4, color=B_STR))
mono(L, [nx + 216, ny + 336, 260, 13], "surface-floating", size=10.5,
    color=BONE100)
T(L, [nx + 216, ny + 360, 260, 40], "Command menus, inspectors, tooltips",
  size=12.5, color=BONE300, lh=1.4)
# critical
L.rect([nx + 88, ny + 452, 528, 76], fill=rgba(CORAL, 0.08), radius=16,
       **stroke(1.6, color=rgba(CORAL, 0.65)))
mono(L, [nx + 108, ny + 466, 200, 13], "surface-critical", size=10.5,
    color=CORAL)
T(L, [nx + 108, ny + 488, 480, 20], "Blocking risk or decision", size=13,
  color=BONE100, weight=500)

# right: tokens + principle
rx2 = MX + 760
lbl(L, [rx2, 268, 400, 14], "Elevation tokens")
card(L, [rx2, 296, 680, 150], fill=INK1000, r=8)
mono(L, [rx2 + 26, 320, 640, 104],
    "--border-subtle:   rgba(205,211,216, 0.12);\n"
    "--border-active:   rgba(61,213,231,  0.56);\n"
    "--shadow-floating: 0 24px 80px rgba(0,0,0,0.42);",
    size=12.5, color=CYAN, lh=1.85)
LV = [("surface-0", "Application background"),
      ("surface-1", "Main content region"),
      ("surface-2", "Cards and grouped information"),
      ("surface-3", "Active, selected, expanded component"),
      ("surface-floating", "Command menus, inspectors, tooltips"),
      ("surface-critical", "Blocking risk or decision")]
for i, (k, v) in enumerate(LV):
    y = 486 + i * 46
    L.line([rx2, y + 34], [rx2 + 680, y + 34], **stroke(1, color=B_SUB))
    mono(L, [rx2, y + 4, 220, 15], k, size=12,
        color=CORAL if "critical" in k else BONE100, weight=600)
    T(L, [rx2 + 240, y + 4, 440, 17], v, size=13, color=BONE300, lh=1.3)
T(L, [rx2, 786, 680, 52],
  "Heavy shadows are reserved for genuinely floating surfaces; everything "
  "else separates by border and contrast.", size=13, color=SLATE, lh=1.5)

# ================================================================ 11 · card anatomy
L, cy = chrome("anatomy", 11, "09 · Component philosophy",
               "A card is a claim with slots — not a rectangle",
               "Every major component supports five conceptual slots, even "
               "when not all are visible.")
# left: the five slots
SLOTS = [("Intent", "what this component is for", CYAN),
         ("State", "where it stands right now", AMBER),
         ("Evidence", "why its claim is believed", MINT),
         ("Interpretation", "what the numbers mean", VIOLET),
         ("Next action", "what should happen now", CORAL)]
for i, (name, what, c) in enumerate(SLOTS):
    y = 280 + i * 108
    L.circle([MX + 14, y + 26], 6, fill=c)
    if i < 4:
        L.line([MX + 14, y + 40], [MX + 14, y + 108],
               **stroke(1.4, color=B_SUB))
    T(L, [MX + 44, y, 300, 26], name, size=20, color=BONE100, weight=600)
    T(L, [MX + 44, y + 32, 420, 20], what, size=13.5, color=SLATE, lh=1.4)

# right: the generic system card, rendered for real
cx2, cy2, cw2, ch2 = MX + 640, 292, 620, 420
card(L, [cx2, cy2, cw2, ch2], fill=INK900, r=16, border=B_STR, accent=CYAN)
lbl(L, [cx2 + 32, cy2 + 30, 320, 14], "Capability · Verified")
mono(L, [cx2 + cw2 - 110, cy2 + 30, 80, 14], "03/12", size=11.5,
    color=SLATE, align="right")
T(L, [cx2 + 32, cy2 + 62, cw2 - 64, 32], "Agentic artifact generation",
  size=24, color=BONE100, weight=600)
T(L, [cx2 + 32, cy2 + 108, cw2 - 64, 48],
  "Translates structured intent into inspectable and reproducible "
  "artifacts.", size=14.5, color=BONE300, lh=1.55)
L.line([cx2 + 32, cy2 + 182], [cx2 + cw2 - 32, cy2 + 182],
       **stroke(1, color=B_SUB))
field_row(L, cx2 + 32, cy2 + 202, cw2 - 64, "Evidence",
          "14 passing tests · 3 fixtures", vcol=BONE100)
field_row(L, cx2 + 32, cy2 + 232, cw2 - 64, "Confidence", "92%",
          vcol=BONE100)
# confidence bar
L.rect([cx2 + 172, cy2 + 258, 300, 6], fill=INK800, radius=3)
L.rect([cx2 + 172, cy2 + 258, 276, 6], fill=MINT, radius=3)
button(L, cx2 + 32, cy2 + ch2 - 72, 210, "Inspect evidence", "secondary")
button(L, cx2 + cw2 - 202, cy2 + ch2 - 72, 170, "Deploy →", "system")

# annotation arrows from slots to card zones
mono(L, [cx2, cy2 + ch2 + 28, cw2, 15],
    "INTENT → TITLE · STATE → LABEL · EVIDENCE → FIELDS · "
    "INTERPRETATION → BAR · ACTION → BUTTONS", size=10, ls="0.06em")

# ================================================================ 12 · components I
L, cy = chrome("components-1", 12, "10 · Core components I",
               "Belief, possibility, decision, constraint",
               "Four semantic cards — each signals its role before its "
               "content is read.")
cw4, ch4 = 700, 296
# Evidence Card
x, y = MX, 264
card(L, [x, y, cw4, ch4], accent=CYAN)
lbl(L, [x + 28, y + 24, 320, 14], "Evidence · Verified")
mono(L, [x + cw4 - 130, y + 24, 100, 14], "ev-2214", size=11, align="right")
T(L, [x + 28, y + 52, cw4 - 56, 26],
  "Flow justification matches the KP oracle", size=18.5, color=BONE100,
  weight=600)
field_row(L, x + 28, y + 98, cw4 - 56, "Type", "regression test")
field_row(L, x + 28, y + 128, cw4 - 56, "Source",
          "tests/test_flow_justify.py")
field_row(L, x + 28, y + 158, cw4 - 56, "Confidence", "0.96")
field_row(L, x + 28, y + 188, cw4 - 56, "Verified", "2026-07-21")
field_row(L, x + 28, y + 218, cw4 - 56, "Contradicts", "none recorded")
L.rect([x + 28, y + 252, 110, 24], fill=rgba(MINT, 0.1), radius=8,
       **stroke(1, color=rgba(MINT, 0.45)))
lbl(L, [x + 28, y + 258, 110, 12], "believed", color=MINT, size=9.5,
    align="center")

# Hypothesis Card
x = MX + 740
card(L, [x, y, cw4, ch4], accent=VIOLET)
lbl(L, [x + 28, y + 24, 340, 14], "Hypothesis · Exploring", color=VIOLET)
mono(L, [x + cw4 - 130, y + 24, 100, 14], "hy-0031", size=11, align="right")
T(L, [x + 28, y + 52, cw4 - 56, 26],
  "Geometry descent converges under band shading", size=18.5,
  color=BONE100, weight=600)
field_row(L, x + 28, y + 98, cw4 - 56, "Expected", "NCC ≥ 0.99 on lotus")
field_row(L, x + 28, y + 128, cw4 - 56, "Test", "refine_reconstruction, "
          "6-ladder + shading")
field_row(L, x + 28, y + 158, cw4 - 56, "Success", "NCC ≥ 0.99 within 40 "
          "iterations")
field_row(L, x + 28, y + 188, cw4 - 56, "Failure", "descent oscillates or "
          "stalls < 0.97")
field_row(L, x + 28, y + 218, cw4 - 56, "Owner", "vision/domain")
L.rect([x + 28, y + 252, 150, 24], fill=rgba(VIOLET, 0.1), radius=8,
       **stroke(1, color=rgba(VIOLET, 0.45)))
lbl(L, [x + 28, y + 258, 150, 12], "not yet shown", color=VIOLET, size=9.5,
    align="center")

# Decision Gate
y2 = y + ch4 + 32
card(L, [MX, y2, cw4, ch4], border=rgba(CORAL, 0.55), bw=1.6)
L.rect([MX + 16, y2, cw4 - 32, 3], fill=CORAL)
lbl(L, [MX + 28, y2 + 24, 340, 14], "Decision · Required", color=CORAL)
mono(L, [MX + cw4 - 190, y2 + 24, 160, 14], "DEADLINE 2026-07-29",
    size=10.5, color=AMBER, align="right")
T(L, [MX + 28, y2 + 52, cw4 - 56, 26],
  "Adopt the DSL as the single source of truth", size=18.5, color=BONE100,
  weight=600)
field_row(L, MX + 28, y2 + 98, cw4 - 56, "Why now", "two renderers drifted "
          "from the token file this month")
field_row(L, MX + 28, y2 + 128, cw4 - 56, "Options", "A · authoritative DSL"
          "   B · generated docs only")
field_row(L, MX + 28, y2 + 158, cw4 - 56, "Trade-offs", "A costs tooling; "
          "B keeps drift risk")
field_row(L, MX + 28, y2 + 188, cw4 - 56, "Recommends", "Option A",
          vcol=BONE100)
field_row(L, MX + 28, y2 + 218, cw4 - 56, "Reversible", "yes — DSL emits "
          "today's CSS unchanged")
button(L, MX + 28, y2 + ch4 - 52, 170, "Decide now →", "primary")
button(L, MX + 214, y2 + ch4 - 52, 190, "Compare options", "secondary")

# Constraint Stack
x = MX + 740
card(L, [x, y2, cw4, ch4])
lbl(L, [x + 28, y2 + 24, 340, 14], "Constraint stack", color=AMBER)
CONS = [("cairosvg drops filter primitives", "origin · renderer", "HIGH",
         CORAL, "fixed", "route glow through raster backend"),
        ("MCP result budget caps payloads", "origin · protocol", "MED",
         AMBER, "fixed", "binaries by reference, text paginated"),
        ("one signal color per composition", "origin · this system", "LOW",
         MINT, "negotiable", "contextual accents stay quiet")]
for i, (t, orig, sev, c, kind, path) in enumerate(CONS):
    yy = y2 + 58 + i * 76
    L.rect([x + 28, yy, cw4 - 56, 64], fill=INK800, radius=8,
           **stroke(1, color=B_SUB))
    L.circle([x + 48, yy + 20], 5, fill=c)
    T(L, [x + 64, yy + 10, 440, 18], t, size=13.5, color=BONE100,
      weight=550)
    mono(L, [x + 64, yy + 34, 250, 13], orig.upper(), size=9.5,
        ls="0.06em")
    mono(L, [x + 330, yy + 34, 90, 13], sev, size=9.5, color=c, weight=600)
    mono(L, [x + 396, yy + 34, 100, 13], kind.upper(), size=9.5,
        ls="0.06em")
    T(L, [x + 500, yy + 22, 176, 32], path, size=10.5, color=SLATE, lh=1.35)

# ================================================================ 13 · components II
L, cy = chrome("components-2", 13, "10 · Core components II",
               "Capabilities connect to form graphs, not lists",
               "The system map, the capability node, and the proof ledger — "
               "the platform-thinking trio.")
# system map (left)
mx2, my2, mw2, mh2 = MX, 262, 880, 380
card(L, [mx2, my2, mw2, mh2], fill=INK1000, r=8)
lbl(L, [mx2 + 24, my2 + 20, 300, 14], "System map", size=10)
NODES = {
    "model":   (150, 120, "model.py", MINT, "operational"),
    "schema":  (390, 88,  "schema", MINT, "operational"),
    "render":  (390, 210, "rendering", CYAN, "validated"),
    "mcp":     (640, 140, "mcp tools", CYAN, "validated"),
    "vision":  (640, 280, "vision loop", VIOLET, "exploring"),
    "coach":   (170, 288, "coach", AMBER, "blocked"),
}
EDGES = [("model", "schema", CYAN, None), ("model", "render", CYAN, None),
         ("render", "mcp", CYAN, None), ("mcp", "vision", VIOLET, [5, 5]),
         ("coach", "render", AMBER, [3, 4]),
         ("schema", "mcp", CYAN, None)]
for a, b, c, dash in EDGES:
    ax, ay = NODES[a][0] + mx2 + 60, NODES[a][1] + my2 + 20
    bx2, by2 = NODES[b][0] + mx2 + 60, NODES[b][1] + my2 + 20
    L.line([ax, ay], [bx2, by2], **stroke(1.6, color=rgba(c, 0.6),
                                          dash=dash))
for k, (nx2, ny2, name, c, state) in NODES.items():
    x, y = mx2 + nx2, my2 + ny2
    L.rect([x, y, 120, 40], fill=INK900, radius=8,
           **stroke(1.4, color=rgba(c, 0.7)))
    T(L, [x, y + 6, 120, 15], name, size=12, color=BONE100, weight=600,
      align="center")
    mono(L, [x, y + 23, 120, 11], state.upper(), size=8, color=c,
        align="center", ls="0.08em")
mono(L, [mx2 + 24, my2 + mh2 - 34, mw2 - 48, 14],
    "CYAN VERIFIED · VIOLET EXPLORING · AMBER UNRESOLVED DEPENDENCY",
    size=9.5, ls="0.08em")
# zoom strip
zy = my2 + mh2 + 20
ZOOM = ["Portfolio", "System", "Capability", "Component", "Source"]
x = mx2
for i, z in enumerate(ZOOM):
    wz = chip(L, x, zy, z, CYAN if i == 1 else SLATE, h=30)
    x += wz + 8
    if i < 4:
        arrow(L, x, zy + 15, x + 22, zy + 15, color=SLATE, w=1.4, head=5)
        x += 34
mono(L, [mx2, zy + 44, 500, 14], "SEMANTIC ZOOM — EVERY LEVEL INSPECTABLE",
    size=9.5, ls="0.08em")

# capability node anatomy (right)
rx3 = MX + 920
card(L, [rx3, 262, 520, 380], accent=CYAN)
lbl(L, [rx3 + 28, 286, 300, 14], "Capability node — the atomic unit")
T(L, [rx3 + 28, 312, 460, 24], "vectorize_image", size=19, color=BONE100,
  weight=600, family=MONO)
CAP = [("Inputs", "raster crop · thresholds · fill mode"),
       ("Outputs", "layered vector draft + score"),
       ("Depends", "measure_image · gradient_fit"),
       ("Consumers", "reconstruction loop · coach"),
       ("Maturity", "operational since 2026-07-22"),
       ("Evidence", "lotus NCC 0.9938 · 99.1% coverage")]
for i, (k, v) in enumerate(CAP):
    field_row(L, rx3 + 28, 352 + i * 32, 460, k, v)
L.line([rx3 + 28, 556], [rx3 + 492, 556], **stroke(1, color=B_SUB))
T(L, [rx3 + 28, 574, 460, 44],
  "Nodes declare contracts, so the map above can be generated — never "
  "drawn by hand.", size=12.5, color=SLATE, lh=1.5)

# proof ledger (bottom)
py2 = 726
lbl(L, [MX, py2, 400, 14], "Proof ledger — claims meet tests, in order",
    color=MINT)
LEDGER = [("2026-07-17", "flow styles honor authored fonts",
           "emit_flow regression suite", "PASS", MINT, "commit 9b0a1"),
          ("2026-07-21", "no tool result exceeds budget",
           "mcp result-budget gate", "PASS", MINT, "commit 14c9a"),
          ("2026-07-22", "descent converges with shading",
           "refine_reconstruction ladder", "PASS", MINT, "NCC 0.9938"),
          ("2026-07-22", "pre-line breaks stable in LaTeX",
           "test_pre_line_breaks.py", "OPEN", AMBER, "uncommitted")]
colw = [150, 420, 330, 90, 240]
hx = [MX, MX + 160, MX + 610, MX + 960, MX + 1080]
for h2, xx in zip(["DATE", "CLAIM", "TEST", "RESULT", "EVIDENCE"], hx):
    mono(L, [xx, py2 + 28, 200, 13], h2, size=9.5, ls="0.1em")
L.line([MX, py2 + 46], [W - MX, py2 + 46], **stroke(1, color=B_STR))
for i, (d, c2, t, res, rc, ev) in enumerate(LEDGER):
    yy = py2 + 58 + i * 36
    mono(L, [hx[0], yy, 150, 14], d, size=10.5, color=BONE300)
    T(L, [hx[1], yy - 1, 430, 16], c2, size=12.5, color=BONE100, lh=1.3)
    T(L, [hx[2], yy - 1, 330, 16], t, size=12, color=BONE300, lh=1.3)
    mono(L, [hx[3], yy, 80, 14], res, size=10.5, color=rc, weight=600)
    mono(L, [hx[4], yy, 240, 14], ev, size=10.5)
    if i < 3:
        L.line([MX, yy + 26], [W - MX, yy + 26], **stroke(1, color=B_SUB))

# ================================================================ 14 · components III
L, cy = chrome("components-3", 14, "10 · Core components III",
               "Drift is detected, scope is compressed, agents are "
               "accountable", tsize=38)
cw5, ch5 = 452, 330
# Divergence Alert
x, y = MX, 250
card(L, [x, y, cw5, ch5], border=rgba(CORAL, 0.45))
lbl(L, [x + 24, y + 20, 300, 14], "Divergence alert", color=CORAL)
T(L, [x + 24, y + 44, cw5 - 48, 44],
  "Implementation drifted from intent", size=16.5, color=BONE100,
  weight=600, lh=1.3)
DIV = [("Expected", "24px card radius (token)"),
       ("Observed", "hard-coded 20px in 3 views"),
       ("Difference", "signature geometry lost"),
       ("Severity", "medium — brand erosion"),
       ("Cause", "values pasted before tokens"),
       ("Correction", "regenerate CSS from DSL")]
for i, (k, v) in enumerate(DIV):
    field_row(L, x + 24, y + 100 + i * 30, cw5 - 48, k, v, size=12)
mono(L, [x + 24, y + ch5 - 34, cw5 - 48, 13],
    "CORAL, WITHOUT ALARMIST STYLING", size=9, ls="0.1em")

# Compression Panel
x = MX + 492
card(L, [x, y, cw5, ch5], accent=AMBER)
lbl(L, [x + 24, y + 20, 300, 14], "Compression panel", color=AMBER)
T(L, [x + 24, y + 44, cw5 - 48, 44], "A large vision becomes an "
  "executable wedge", size=16.5, color=BONE100, weight=600, lh=1.3)
COMP = [("One user", "the agent operator"),
        ("One problem", "unverifiable design claims"),
        ("One transaction", "spec → rendered artifact"),
        ("One proof", "this deck, from one source file"),
        ("One horizon", "a single working session"),
        ("One exclusion", "no component library yet")]
for i, (k, v) in enumerate(COMP):
    field_row(L, x + 24, y + 100 + i * 30, cw5 - 48, k, v, size=12)
mono(L, [x + 24, y + ch5 - 34, cw5 - 48, 13],
    "EXISTS TO COUNTER SCOPE EXPANSION", size=9, ls="0.1em")

# Agent Console
x = MX + 984
card(L, [x, y, cw5 + 4, ch5], accent=VIOLET)
lbl(L, [x + 24, y + 20, 300, 14], "Agent console", color=VIOLET)
mono(L, [x + cw5 - 120, y + 20, 100, 14], "run 0142", size=10.5,
    align="right")
field_row(L, x + 24, y + 48, cw5 - 44, "Objective",
          "render PALS.md as a deck", size=12)
field_row(L, x + 24, y + 78, cw5 - 44, "Plan", "21 pages · tokens first",
          size=12)
field_row(L, x + 24, y + 108, cw5 - 44, "Actions", "38 tool calls · 3 "
          "renders", size=12)
field_row(L, x + 24, y + 138, cw5 - 44, "Artifacts", "deck.pdf · 21 SVG "
          "pages", size=12)
field_row(L, x + 24, y + 168, cw5 - 44, "Assumes", "deck format fits "
          "intent", size=12)
field_row(L, x + 24, y + 198, cw5 - 44, "Uncertain", "final page order",
          size=12)
L.rect([x + 24, y + 232, 180, 26], fill=rgba(AMBER, 0.1), radius=8,
       **stroke(1, color=rgba(AMBER, 0.5)))
lbl(L, [x + 24, y + 239, 180, 12], "approval gate open", color=AMBER,
    size=9)
mono(L, [x + 24, y + 270, cw5 - 44, 13], "COST 412K TOKENS · 6 MIN",
    size=9, ls="0.08em")
mono(L, [x + 24, y + ch5 - 34, cw5 - 44, 13],
    "NEVER A ROBOT, FACE, OR GLOWING BRAIN", size=9, ls="0.1em")

# bottom row: four compact components
MINIS = [("Execution queue", CORAL,
          ["outcome · capability · evidence", "owner · blocking dependency",
           "acceptance condition"],
          "not a generic task list"),
         ("Portfolio constellation", VIOLET,
          ["strategic alignment · maturity", "shared capabilities · effort",
           "commercial proximity"],
          "related systems, not isolated cards"),
         ("Annotation thread", CYAN,
          ["pinned to object + state + version", "decision history · "
           "linked evidence", "resolved and reopened states"],
          "annotations never detach"),
         ("Artifact preview", MINT,
          ["source · generation history", "validation status",
           "available revisions"],
          "a result is always paired with its why")]
mw3 = (1440 - 3 * 24) / 4.0
for i, (name, c, lines, note) in enumerate(MINIS):
    x = MX + i * (mw3 + 24)
    y = 618
    card(L, [x, y, mw3, 256], accent=c)
    T(L, [x + 22, y + 24, mw3 - 44, 44], name, size=16.5, color=BONE100,
      weight=600, lh=1.25)
    for j, ln in enumerate(lines):
        L.circle([x + 27, y + 88 + j * 40], 3, fill=c)
        T(L, [x + 42, y + 76 + j * 40, mw3 - 62, 34], ln, size=11.5,
          color=BONE300, lh=1.4)
    mono(L, [x + 22, y + 216, mw3 - 44, 14], note.upper(), size=8.5,
        ls="0.08em")

# ================================================================ 15 · states+buttons
L, cy = chrome("states", 15, "11 · States  /  12 · Buttons and actions",
               "State is first-class information",
               "A component never disappears because it stopped being "
               "active — it becomes history.")
STATES = [
    ("latent", "low-contrast outline", lambda x, y: L.rect(
        [x, y, 60, 26], fill="none", radius=8,
        **stroke(1.2, color=rgba(BONE300, 0.25)))),
    ("proposed", "violet marker", lambda x, y: (
        L.rect([x, y, 60, 26], fill=INK800, radius=8),
        L.circle([x + 8, y + 13], 4, fill=VIOLET))),
    ("exploring", "animated violet/cyan field", lambda x, y: L.rect(
        [x, y, 60, 26], radius=8, fill=linear_gradient(
            [(rgba(VIOLET, 0.55), 0), (rgba(CYAN, 0.55), 1.0)], angle=90))),
    ("active", "strong white foreground", lambda x, y: (
        L.rect([x, y, 60, 26], fill=BONE100, radius=8))),
    ("blocked", "amber border", lambda x, y: L.rect(
        [x, y, 60, 26], fill=INK800, radius=8,
        **stroke(1.8, color=AMBER))),
    ("challenged", "coral annotation", lambda x, y: (
        L.rect([x, y, 60, 26], fill=INK800, radius=8),
        L.circle([x + 60, y], 5, fill=CORAL))),
    ("validated", "cyan confirmation", lambda x, y: (
        L.rect([x, y, 60, 26], fill=INK800, radius=8,
               **stroke(1.4, color=B_EVD)),
        tick(L, x + 24, y + 8, color=CYAN, s=0.85))),
    ("operational", "mint status", lambda x, y: (
        L.rect([x, y, 60, 26], fill=INK800, radius=8),
        L.circle([x + 10, y + 13], 4, fill=MINT))),
    ("deprecated", "desaturated + replacement link", lambda x, y: (
        L.rect([x, y, 60, 26], fill=rgba(BONE300, 0.06), radius=8),
        L.line([x + 12, y + 13], [x + 48, y + 13],
               **stroke(1.2, color=SLATE)))),
    ("archived", "quiet gray, still accessible", lambda x, y: L.rect(
        [x, y, 60, 26], fill="none", radius=8,
        **stroke(1, color=rgba(SLATE, 0.5), dash=[3, 4]))),
]
sw2 = (1440 - 4 * 20) / 5.0
for i, (name, treat, draw) in enumerate(STATES):
    x = MX + (i % 5) * (sw2 + 20)
    y = 262 + (i // 5) * 112
    L.rect([x, y, sw2, 96], fill=INK900, radius=16,
           **stroke(1, color=B_SUB))
    draw(x + 22, y + 20)
    T(L, [x + 100, y + 18, sw2 - 120, 18], name, size=14.5, color=BONE100,
      weight=600, family=MONO)
    T(L, [x + 22, y + 60, sw2 - 44, 28], treat, size=11, color=SLATE,
      lh=1.35)

# buttons by decision weight
by3 = 520
lbl(L, [MX, by3, 500, 14], "Buttons are organized by decision weight, "
    "not visual preference", color=CORAL)
BTN = [("primary", "Deploy", "commit · deploy · approve · publish · "
        "execute"),
       ("system", "Inspect", "inspect · connect · analyze · open · "
        "compare"),
       ("exploratory", "Generate", "generate · simulate · branch · "
        "imagine · prototype"),
       ("secondary", "Later", "everything that must not shout"),
       ("destructive", "Delete model", "explicit context + confirmation "
        "required")]
bw3 = (1440 - 4 * 24) / 5.0
for i, (kind, s, verbs) in enumerate(BTN):
    x = MX + i * (bw3 + 24)
    card(L, [x, by3 + 32, bw3, 190], fill=INK900, r=16)
    button(L, x + 24, by3 + 60, bw3 - 48, s, kind)
    lbl(L, [x + 24, by3 + 118, bw3 - 48, 13], kind, color=SLATE, size=9.5)
    T(L, [x + 24, by3 + 142, bw3 - 48, 62], verbs, size=11.5, color=BONE300,
      lh=1.5)

T(L, [MX, by3 + 258, 1440, 44],
  "Confirmation copy states consequences, not feelings: “This action "
  "changes the source model and regenerates all dependent artifacts.”",
  size=14.5, color=BONE300, family=ED, lh=1.5)

# ================================================================ 16 · iconography
L, cy = chrome("icons", 16, "13 · Iconography",
               "Geometry over cliché",
               "24 × 24 grid · 1.75px stroke · round caps · no brains, "
               "robots, sparkles or lightning.")


def icon_frame(x, y, s, name):
    L.rect([x, y, s, s], fill=INK900, radius=12, **stroke(1, color=B_SUB))
    T(L, [x - 14, y + s + 10, s + 28, 15], name, size=11, color=SLATE,
      align="center", lh=1.2)
    return x + s / 2, y + s / 2


IS = 84
IW = 2.6
def icon_node(cx, cy):
    L.circle([cx, cy], 15, fill="none", **stroke(IW, color=BONE100))
    L.circle([cx, cy], 4, fill=CYAN)
def icon_loop(cx, cy):
    arc(L, cx, cy, 15, -40, 230, color=BONE100, w=IW)
    arrow(L, cx + 15 * math.cos(math.radians(-40)),
          cy + 15 * math.sin(math.radians(-40)),
          cx + 19, cy - 3, color=BONE100, w=IW, head=5)
def icon_layers(cx, cy):
    for k in range(3):
        L.polyline([[cx - 16, cy - 8 + k * 8], [cx, cy - 15 + k * 8],
                    [cx + 16, cy - 8 + k * 8], [cx, cy - 1 + k * 8],
                    [cx - 16, cy - 8 + k * 8]],
                   **stroke(IW, color=BONE100 if k == 0 else
                            rgba(BONE300, 0.55), join="round"))
def icon_bridge(cx, cy):
    L.line([cx - 16, cy + 12], [cx - 16, cy - 2],
           **stroke(IW, color=BONE100, cap="round"))
    L.line([cx + 16, cy + 12], [cx + 16, cy - 2],
           **stroke(IW, color=BONE100, cap="round"))
    arc(L, cx, cy - 2 + 16, 22.6, 225, 315, color=BONE100, w=IW)
def icon_boundary(cx, cy):
    L.rect([cx - 15, cy - 15, 30, 30], fill="none", radius=6,
           **stroke(IW, color=BONE100, dash=[4, 4]))
    L.circle([cx, cy], 4, fill=VIOLET)
def icon_convergence(cx, cy):
    for a in (150, 180, 210):
        th = math.radians(a)
        L.line([cx + 20 * math.cos(th), cy + 20 * math.sin(th)],
               [cx - 2, cy], **stroke(IW, color=BONE100, cap="round"))
    arrow(L, cx, cy, cx + 18, cy, color=CORAL, w=IW, head=6)
def icon_branching(cx, cy):
    L.line([cx - 18, cy], [cx - 2, cy], **stroke(IW, color=BONE100,
                                                 cap="round"))
    L.line([cx - 2, cy], [cx + 14, cy - 10], **stroke(IW, color=BONE100,
                                                      cap="round"))
    L.line([cx - 2, cy], [cx + 14, cy + 10], **stroke(IW, color=BONE100,
                                                      cap="round"))
    L.circle([cx + 16, cy - 11], 3, fill=VIOLET)
    L.circle([cx + 16, cy + 11], 3, fill=CYAN)
def icon_frame2(cx, cy):
    for sx in (-1, 1):
        for sy in (-1, 1):
            L.polyline([[cx + sx * 16, cy + sy * 8],
                        [cx + sx * 16, cy + sy * 16],
                        [cx + sx * 8, cy + sy * 16]],
                       **stroke(IW, color=BONE100, cap="round",
                                join="round"))
def icon_planes(cx, cy):
    L.rect([cx - 18, cy - 12, 22, 22], fill="none", radius=4,
           **stroke(IW, color=BONE100))
    L.rect([cx - 4, cy - 10, 22, 22], fill="none", radius=4,
           **stroke(IW, color=rgba(CYAN, 0.85)))
def icon_open(cx, cy):
    L.polyline([[cx + 8, cy - 15], [cx - 15, cy - 15], [cx - 15, cy + 15],
                [cx + 8, cy + 15]], **stroke(IW, color=BONE100,
                                             cap="round", join="round"))
    arrow(L, cx - 4, cy, cx + 18, cy, color=CYAN, w=IW, head=6)


FORMS = [("node", icon_node), ("loop", icon_loop), ("layers", icon_layers),
         ("bridge", icon_bridge), ("boundary", icon_boundary),
         ("convergence", icon_convergence), ("branching", icon_branching),
         ("frame", icon_frame2), ("linked planes", icon_planes),
         ("open system", icon_open)]
for i, (name, fn) in enumerate(FORMS):
    x = MX + (i % 5) * 118
    y = 268 + (i // 5) * 148
    cx3, cy3 = icon_frame(x, y, IS, name)
    fn(cx3, cy3)

# construction panel
bx2 = MX + 660
card(L, [bx2, 268, 360, 328], fill=INK1000, r=8)
lbl(L, [bx2 + 24, 288, 300, 14], "Construction", color=SLATE, size=10)
gx3, gy3, gs3 = bx2 + 60, 316, 240
for k in range(7):
    o = k * gs3 / 6.0
    L.line([gx3 + o, gy3], [gx3 + o, gy3 + gs3],
           **stroke(0.6, color=rgba(BONE300, 0.10)))
    L.line([gx3, gy3 + o], [gx3 + gs3, gy3 + o],
           **stroke(0.6, color=rgba(BONE300, 0.10)))
_ccx, _ccy = gx3 + gs3 / 2, gy3 + gs3 / 2
for _a in (150, 180, 210):
    _th = math.radians(_a)
    L.line([_ccx + 100 * math.cos(_th), _ccy + 100 * math.sin(_th)],
           [_ccx - 10, _ccy], **stroke(8.75, color=BONE100, cap="round"))
arrow(L, _ccx, _ccy, _ccx + 90, _ccy, color=CORAL, w=8.75, head=26)
mono(L, [bx2 + 24, gy3 + gs3 + 14, 320, 14],
    "24 × 24 GRID · 1.75PX STROKE · ROUND CAPS", size=9, ls="0.08em")

# avoid list
ax2 = MX + 1080
lbl(L, [ax2, 268, 300, 14], "Avoid", color=CORAL)
AVOID = ["brains", "robots", "lightning bolts", "magic wands",
         "circuit-board clichés", "speed lines", "AI sparkles",
         "meaningless arrows"]
for i, a in enumerate(AVOID):
    y = 298 + i * 36
    cross(L, ax2 + 2, y + 2, s=0.85)
    T(L, [ax2 + 26, y - 3, 320, 17], a, size=13.5, color=BONE300)

# signature symbol
sy3 = 640
lbl(L, [MX, sy3, 700, 14], "The signature symbol — a partially open "
    "convergence loop")
mark(L, MX + 150, sy3 + 158, 62)
T(L, [MX + 360, sy3 + 74, 620, 100],
  "Several independent paths enter a shared structure.\nOne path continues "
  "outward — as action.", size=17, color=BONE300, family=ED, lh=1.6)
mono(L, [MX + 360, sy3 + 178, 500, 14],
    "READS AT 16PX AND 24PX · CONSISTENT OPTICAL WEIGHT", size=9.5,
    ls="0.08em")

# ================================================================ 17 · dataviz
L, cy = chrome("dataviz", 17, "14 · Data visualization",
               "Charts emphasize decisions, not decoration",
               "Direct labels, visible sources, explicit uncertainty — "
               "comparisons over isolated values.")
# chart panel
px2, py3, pw2, ph2 = MX, 268, 880, 520
card(L, [px2, py3, pw2, ph2], fill=INK1000, r=8)
lbl(L, [px2 + 28, py3 + 24, 600, 14], "Reconstruction fidelity · NCC by "
    "iteration", size=10)
ox, oy, cw6, ch6 = px2 + 70, py3 + 70, pw2 - 130, ph2 - 160
# gridlines + axis
for i in range(5):
    yy = oy + ch6 * i / 4.0
    L.line([ox, yy], [ox + cw6, yy], **stroke(0.8, color=rgba(BONE300,
                                                              0.08)))
    mono(L, [ox - 52, yy - 6, 42, 12], f"{1.0 - 0.1 * i:.2f}", size=9.5,
        align="right")
def pty(v):
    return oy + ch6 * (1.0 - (v - 0.60) / 0.40)
def ptx(i, n=10):
    return ox + cw6 * i / n
ACTUAL = [0.62, 0.71, 0.78, 0.84, 0.89, 0.925, 0.951]
PROJ = [0.951, 0.968, 0.982, 0.991]
apts = [[ptx(i), pty(v)] for i, v in enumerate(ACTUAL)]
ppts = [[ptx(6 + i), pty(v)] for i, v in enumerate(PROJ)]
# amber uncertainty band around projection
band = ([[x2, y2 - 8 - 5 * i] for i, (x2, y2) in enumerate(ppts)]
        + [[x2, y2 + 8 + 5 * i] for i, (x2, y2)
           in reversed(list(enumerate(ppts)))])
L.polygon(band, fill=rgba(AMBER, 0.10))
# target line (bone dashed)
L.line([ox, pty(0.99)], [ox + cw6, pty(0.99)],
       **stroke(1.4, color=rgba(BONE100, 0.7), dash=[7, 6]))
mono(L, [ox + cw6 - 240, pty(0.99) - 20, 240, 13], "TARGET 0.99",
    size=9.5, color=BONE100, align="right", ls="0.08em")
L.polyline(apts, **stroke(2.6, color=CYAN, cap="round", join="round"))
for p in apts:
    L.circle(p, 4, fill=INK1000, **stroke(2.2, color=CYAN))
L.polyline(ppts, **stroke(2.4, color=VIOLET, cap="round", dash=[2, 7]))
mono(L, [apts[-1][0] - 240, apts[-1][1] + 34, 200, 13],
    "ACTUAL · VERIFIED", size=9.5, color=CYAN, align="right", ls="0.06em")
mono(L, [ppts[-1][0] - 230, ppts[-1][1] - 24, 220, 13],
    "PROJECTION · HYPOTHESIS", size=9.5, color=VIOLET, align="right",
    ls="0.06em")
# annotation: intervention
ix2 = ptx(4)
L.line([ix2, pty(0.89) + 8], [ix2, pty(0.89) + 56],
       **stroke(1.2, color=rgba(CORAL, 0.8)))
L.circle([ix2, pty(0.89)], 5, fill="none", **stroke(2, color=CORAL))
T(L, [ix2 + 12, pty(0.89) + 44, 220, 18],
  "shading pass enabled here", size=11.5, color=CORAL, lh=1.3)
mono(L, [px2 + 28, py3 + ph2 - 40, pw2 - 56, 14],
    "SOURCE session/fazai-brand-06 · MEASURED 2026-07-22 09:00Z · "
    "UNCERTAINTY 80% BAND", size=9.5, ls="0.06em")

# right rail: rules + mapping
rx4 = MX + 920
lbl(L, [rx4, 268, 500, 14], "Default chart rules")
RULES = ["dark neutral background", "no rainbow categorical palettes",
         "direct labels, not distant legends", "visible source and "
         "freshness", "uncertainty represented explicitly",
         "annotations live inside the chart",
         "comparisons over isolated values"]
for i, r_ in enumerate(RULES):
    y = 296 + i * 32
    tick(L, rx4, y + 2, s=0.8)
    T(L, [rx4 + 26, y - 3, 494, 17], r_, size=13, color=BONE300)
lbl(L, [rx4, 532, 500, 14], "Semantic mapping")
MAPPING = [("Actual / verified", CYAN), ("Target / intended", BONE100),
           ("Risk / deviation", CORAL), ("Projection / hypothesis", VIOLET),
           ("Pending / incomplete", AMBER), ("Successful operation", MINT),
           ("Historical context", SLATE)]
for i, (k, c) in enumerate(MAPPING):
    y = 560 + i * 30
    L.rect([rx4, y, 26, 12], fill=c, radius=3)
    T(L, [rx4 + 40, y - 3, 480, 17], k, size=12.5, color=BONE300)
mono(L, [rx4, 790, 520, 40],
    "SIGNATURES · capability lattices · dependency graphs ·\nevidence maps "
    "· maturity matrices · decision trees", size=9.5, lh=1.7,
    ls="0.04em")

# ================================================================ 18 · motion+content
L, cy = chrome("motion", 18, "15 · Motion  /  16 · Content design",
               "Motion communicates causality, not excitement",
               "And copy states what is true, what it means, what is "
               "uncertain, what must happen next.")
# durations
lbl(L, [MX, 262, 400, 14], "Durations")
DUR = [("micro feedback", 120, "100–140ms"),
       ("component state", 210, "180–240ms"),
       ("panel transition", 320, "280–360ms"),
       ("system reconfiguration", 575, "450–700ms"),
       ("narrative reveal", 850, "700–1000ms")]
for i, (name, ms, rng) in enumerate(DUR):
    y = 292 + i * 44
    L.rect([MX, y, ms * 0.52, 18], fill=rgba(CYAN, 0.75), radius=4)
    T(L, [MX + ms * 0.52 + 14, y - 1, 240, 18], name, size=12.5,
      color=BONE100, weight=550)
    mono(L, [MX + 590, y + 1, 110, 14], rng, size=10.5, align="right")

# signature motion storyboard
lbl(L, [MX, 528, 700, 14], "Signature motion — divergence, synthesis, "
    "coherence, execution")
FRAMES = ["independent\nnodes appear", "relationships\nbecome visible",
          "paths\nconverge", "structure\nstabilizes",
          "the next action\nemerges"]
fs2 = 118
for i, cap2 in enumerate(FRAMES):
    x = MX + i * (fs2 + 22)
    L.rect([x, 558, fs2, fs2], fill=INK900, radius=12,
           **stroke(1, color=B_SUB))
    ccx, ccy = x + fs2 / 2, 558 + fs2 / 2
    if i == 0:
        for a, c in [(140, CYAN), (200, VIOLET), (260, AMBER)]:
            th = math.radians(a)
            L.circle([ccx + 34 * math.cos(th), ccy + 34 * math.sin(th)],
                     4, fill=c)
    elif i == 1:
        pts2 = []
        for a, c in [(140, CYAN), (200, VIOLET), (260, AMBER)]:
            th = math.radians(a)
            p = [ccx + 34 * math.cos(th), ccy + 34 * math.sin(th)]
            pts2.append(p)
            L.circle(p, 4, fill=c)
        for a2, b2 in ((0, 1), (1, 2), (0, 2)):
            L.line(pts2[a2], pts2[b2], **stroke(0.9, color=rgba(BONE300,
                                                                0.3)))
    elif i == 2:
        for a, c in [(140, CYAN), (200, VIOLET), (260, AMBER)]:
            th = math.radians(a)
            L.line([ccx + 34 * math.cos(th), ccy + 34 * math.sin(th)],
                   [ccx, ccy], **stroke(1.6, color=c, cap="round"))
    elif i == 3:
        arc(L, ccx, ccy, 20, 28, 332, color=BONE100, w=2.4)
    else:
        arc(L, ccx - 6, ccy, 18, 28, 332, color=BONE100, w=2.2)
        arrow(L, ccx + 8, ccy, ccx + 34, ccy, color=CORAL, w=2.2, head=6)
    T(L, [x - 8, 558 + fs2 + 8, fs2 + 16, 30], cap2, size=10, color=SLATE,
      align="center", lh=1.3)
mono(L, [MX, 790, 700, 14],
    "GLOW ONLY FOR · ACTIVE COMPUTATION · LIVE CONNECTION · NEW EVIDENCE "
    "· EMERGING STRUCTURE", size=9, ls="0.08em")
mono(L, [MX, 816, 700, 14],
    "SUBTLE · INTERRUPTIBLE · REVERSIBLE · REDUCED-MOTION COMPATIBLE",
    size=9, ls="0.08em")

# content design (right)
cx4 = MX + 800
lbl(L, [cx4, 262, 500, 14], "Copy: consequence, not comfort", color=CORAL)
PAIRS = [("Explore our innovative AI-powered solutions.",
          "Describe the business outcome. The system assembles and "
          "operates the solution."),
         ("Something went wrong.",
          "The artifact was generated, but it failed two structural "
          "validations."),
         ("Are you sure?",
          "This action changes the source model and regenerates all "
          "dependent artifacts."),
         ("Success!",
          "Deployed. All 47 acceptance checks passed.")]
for i, (weak, strong2) in enumerate(PAIRS):
    y = 292 + i * 136
    mono(L, [cx4, y, 120, 13], "INSTEAD OF", size=9, ls="0.1em")
    T(L, [cx4, y + 18, 640, 20], f"“{weak}”", size=13.5, color=SLATE,
      lh=1.4)
    L.rect([cx4, y + 48, 3, 46], fill=CYAN)
    mono(L, [cx4 + 16, y + 46, 120, 13], "USE", size=9, color=CYAN,
        ls="0.1em")
    T(L, [cx4 + 16, y + 63, 624, 40], strong2, size=14.5, color=BONE100,
      weight=500, lh=1.45)

# ================================================================ 19 · nav+modes
L, cy = chrome("navigation", 19, "17 · Navigation  /  18 · Modes",
               "Move through space, time, and intent",
               "Six modes reconfigure the same truth for different work.")
NAVS = [("Spatial", ["Overview", "System", "Capability", "Component",
                     "Evidence"], CYAN),
        ("Temporal", ["Previous state", "Current state", "Proposed state"],
         AMBER),
        ("Intent", ["Understand", "Decide", "Build", "Validate", "Operate",
                    "Evolve"], VIOLET)]
for i, (name, steps, c) in enumerate(NAVS):
    y = 262 + i * 64
    lbl(L, [MX, y + 8, 110, 13], name, color=c, size=10)
    x = MX + 130
    for j, s in enumerate(steps):
        wz = chip(L, x, y, s, c if j == (1 if i == 1 else 0) else SLATE,
                  h=30, size=10.5)
        x += wz + 6
        if j < len(steps) - 1:
            arrow(L, x, y + 15, x + 18, y + 15, color=SLATE, w=1.3, head=5)
            x += 26

# modes grid
MODES = [("Executive", "decisions · alignment · portfolio · risk",
          "restrained · high contrast · prominent thesis", CYAN, "core"),
         ("Architect", "systems · dependencies · schemas",
          "dense · graph-oriented · monospace metadata", CYAN, "core"),
         ("Builder", "creating and executing",
          "command palette · artifact workspace · live status", MINT,
          "core"),
         ("Laboratory", "experimentation and possibility",
          "spectral gradients · branching hypotheses", VIOLET, "edge"),
         ("Editorial", "publication and thought leadership",
          "bone background · Source Serif 4 · narrative rhythm", AMBER,
          "light"),
         ("Field", "mobile use and operational clarity",
          "single column · large targets · offline-first", CORAL, "core")]
mw4, mh4 = (1440 - 2 * 24) / 3.0, 212
for i, (name, purpose, look, c, kind) in enumerate(MODES):
    x = MX + (i % 3) * (mw4 + 24)
    y = 470 + (i // 3) * (mh4 + 24)
    if kind == "light":                  # editorial: the one light surface
        card(L, [x, y, mw4, mh4], fill=BONE100, r=24, border=B_STR)
        T(L, [x + 28, y + 24, mw4 - 56, 30], name, size=21, color=INK950,
          weight=600, family=ED)
        T(L, [x + 28, y + 62, mw4 - 56, 40], purpose, size=13,
          color="#3A4656", family=ED, lh=1.5)
        T(L, [x + 28, y + 118, mw4 - 56, 60], look, size=12.5,
          color="#5A6675", family=ED, lh=1.55)
    elif kind == "edge":
        L.rect([x, y, mw4, mh4], fill=INK950, radius=32,
               **stroke(1.3, color=rgba(VIOLET, 0.5)))
        L.rect([x, y, mw4, mh4], radius=32, fill=radial_gradient(
            [(rgba(VIOLET, 0.3), 0), (rgba(VIOLET, 0.0), 0.55)],
            at="75% 25%"))
        T(L, [x + 28, y + 24, mw4 - 56, 30], name, size=21, color=BONE100,
          weight=600)
        T(L, [x + 28, y + 62, mw4 - 56, 40], purpose, size=13,
          color=BONE300, lh=1.5)
        T(L, [x + 28, y + 118, mw4 - 56, 60], look, size=12.5, color=SLATE,
          lh=1.55)
    else:
        card(L, [x, y, mw4, mh4], accent=c, r=16 if kind == "core" else 24)
        T(L, [x + 28, y + 24, mw4 - 56, 30], name, size=21, color=BONE100,
          weight=600)
        T(L, [x + 28, y + 62, mw4 - 56, 40], purpose, size=13,
          color=BONE300, lh=1.5)
        T(L, [x + 28, y + 118, mw4 - 56, 60], look, size=12.5, color=SLATE,
          lh=1.55)
    lbl(L, [x + 28, y + mh4 - 34, 200, 12],
        {"core": "the core", "edge": "the edge", "light": "light mode"}[
            kind], color=c if kind != "light" else "#8A6A18", size=9)

# ================================================================ 20 · a11y+governance
L, cy = chrome("governance", 20,
               "19 · Accessibility  /  20 · Governance",
               "Structural accessibility, versioned semantics",
               "Accessibility is architecture, and the design system is a "
               "versioned semantic contract — not a component library.")
A11Y = ["WCAG AA minimum", "keyboard-first navigation",
        "semantic HTML and ARIA", "visible focus states",
        "reduced-motion support", "color-independent state communication",
        "minimum 44px touch targets", "16px default mobile body text",
        "charts readable in monochrome", "i18n at token and component "
        "level"]
lbl(L, [MX, 268, 400, 14], "The system requires", color=MINT)
for i, a in enumerate(A11Y):
    x = MX + (i % 2) * 330
    y = 300 + (i // 2) * 44
    tick(L, x, y + 3, s=0.9)
    T(L, [x + 26, y - 3, 300, 34], a, size=13, color=BONE300, lh=1.3)
lbl(L, [MX, 542, 620, 14], "Every semantic color also carries",
    color=MINT)
x = MX
for s in ["icon", "label", "pattern / border", "machine-readable state"]:
    x += chip(L, x, 572, s, BONE300, h=30, fill=rgba(BONE300, 0.05)) + 12
T(L, [MX, 632, 620, 66],
  "Hue is never the only channel: rank and state ride on tone, position "
  "and label — the ~8% of men with red–green deficiency read the same "
  "system.", size=13, color=SLATE, lh=1.55)

# governance (right)
gx4 = MX + 740
lbl(L, [gx4, 268, 500, 14], "Source of truth lifecycle")
PIPE = [("External CSS", SLATE), ("ingestion JSON", SLATE),
        ("authoritative DSL", CYAN), ("generated CSS", MINT)]
x = gx4
for i, (s, c) in enumerate(PIPE):
    wz = len(s) * 8.0 + 30
    L.rect([x, 296, wz, 40], fill=INK900 if c == SLATE else rgba(c, 0.1),
           radius=8, **stroke(1.3, color=rgba(c, 0.6)))
    T(L, [x, 308, wz, 16], s, size=12.5, color=BONE100 if c == SLATE
      else c, weight=600, align="center", family=MONO)
    x += wz + 8
    if i < 3:
        arrow(L, x, 316, x + 20, 316, color=SLATE, w=1.5, head=6)
        x += 30
T(L, [gx4, 352, 700, 22],
  "The DSL — not screenshots, not design files — defines:", size=13.5,
  color=BONE300)
DSL = ["tokens", "semantic roles", "components", "states", "constraints",
       "responsive behavior", "accessibility", "interaction",
       "relationships", "provenance", "versioning"]
x, y = gx4, 384
for s in DSL:
    wpx = len(s) * 7.4 + 28
    if x + wpx > gx4 + 700:
        x = gx4
        y += 38
    chip(L, x, y, s, CYAN, w=wpx, h=28, size=9.5)
    x += wpx + 10
# component contract
card(L, [gx4, y + 52, 700, 300], fill=INK1000, r=8)
lbl(L, [gx4 + 26, y + 72, 400, 14], "Every component carries", size=10)
CONTRACT = ["stable UUID", "semantic name", "purpose", "variants",
            "states", "tokens", "dependencies", "accessibility contract",
            "interaction contract", "test fixtures", "version history"]
for i, s in enumerate(CONTRACT):
    xx = gx4 + 26 + (i % 2) * 340
    yy = y + 100 + (i // 2) * 34
    mono(L, [xx, yy, 30, 14], f"{i:02d}", size=10, color=CYAN)
    mono(L, [xx + 40, yy, 300, 14], s, size=11.5, color=BONE300)
mono(L, [gx4 + 26, y + 100 + 6 * 34 + 8, 640, 14],
    "STORYBOOK = THE INSPECTABLE IMPLEMENTATION HUB", size=9.5,
    ls="0.08em")

# ================================================================ 21 · close
page = doc.page("close", canvas={"size": [W, H]}, coordinate_mode="absolute")
bg = page.layer("bg")
L = page.layer("content")
bg.rect([0, 0, W, H], fill=INK1000)
mono(L, [MX, 46, 700, 14], "CONVERGENCE / PEDRO.SYSTEM v1.0", size=10.5,
    color=SLATE, ls="0.08em")
mono(L, [W - MX - 300, 46, 300, 14], f"21 / {PAGES}", size=10.5,
    color=SLATE, align="right", ls="0.08em")
L.line([MX, 74], [W - MX, 74], **stroke(1, color=B_SUB))
lbl(L, [MX, 102, 900, 14], "21 · Anti-patterns  /  23 · The complete "
    "system", color=CORAL)
T(L, [MX, 130, 1250, 48], "What the system refuses", size=42,
  color=BONE100, weight=600, family=UID, lh=1.1)

ANTI = ["generic cards without semantic purpose",
        "decoration presented as meaning", "gradients everywhere",
        "AI clichés", "hidden uncertainty", "unsupported claims",
        "dashboards with no decisions", "disconnected features",
        "hard-coded values", "invisible provenance",
        "interaction without state history",
        "prototypes mistaken for foundations",
        "foundations that never ship artifacts",
        "complexity as performance", "simplification that destroys the "
        "model"]
for i, a in enumerate(ANTI):
    x = MX + (i % 2) * 330
    y = 220 + (i // 2) * 42
    cross(L, x, y + 2, s=0.8)
    T(L, [x + 24, y - 3, 306, 34], a, size=12.5, color=BONE300, lh=1.3)

card(L, [MX, 580, 640, 150], fill=INK950, r=16,
     border=rgba(CORAL, 0.45))
lbl(L, [MX + 30, 604, 500, 13], "The most important anti-pattern",
    color=CORAL, size=10)
T(L, [MX + 30, 630, 580, 76],
  "A visually finished result that cannot explain\nhow or why it exists.",
  size=21, color=BONE100, weight=500, family=ED, lh=1.45)

# closing (right)
cxr = MX + 760
mark(L, cxr + 90, 300, 64)
WORDS = [("Understand.", CYAN), ("Decide.", CORAL), ("Build.", MINT)]
for i, (w2, c) in enumerate(WORDS):
    T(L, [cxr, 408 + i * 92, 680, 84], w2, size=66, color=c, weight=650,
      family=UID, lh=1.0)
T(L, [cxr, 704, 680, 90],
  "Not a visual style applied to components — a complete language for "
  "turning ambitious thought into inspectable reality.", size=18,
  color=BONE300, family=ED, lh=1.6)

L.line([MX, 872], [W - MX, 872], **stroke(1, color=B_SUB))
mono(L, [MX, 890, 1000, 13],
    "EVERY PATH LEADS TO ONE OF THREE THINGS — UNDERSTAND · DECIDE · "
    "BUILD", size=10, color=SLATE, ls="0.1em")
mono(L, [MX, 914, 1440, 13],
    "CYAN = VERIFIED · VIOLET = EXPLORED · AMBER = UNRESOLVED · CORAL = "
    "DECISION REQUIRED · RENDERED FROM _tmp/PALS.md BY FRAMEFORGE",
    size=10, color=SLATE, ls="0.08em")


def build():
    return doc
