#!/usr/bin/env python3
"""
build_schema.py — mirror the contract's JSON Schema into this repo's docs tree.

The schema is NOT generated here. It is generated by the distribution that owns
the contract, `frameforge_api.build_schema()`, and this script writes that result
to `docs/schema/frameforge-v2.schema.json` so the docs site has a copy to serve
and link.

It used to re-implement the generation — `Document.model_json_schema()` plus a
hand-set `$id`/`version`/`title` — and that re-implementation is exactly how the
two copies drifted: the local build silently omitted the
`x-frameforge-deprecations` registry the contract emits, so this repo published a
schema no other consumer would produce. A mirror can go stale and be caught; a
second generator produces a *different artifact* and looks fine.

Usage:
    python3 build_schema.py                 # write ../schema/frameforge-v2.schema.json
    python3 build_schema.py --check         # exit non-zero if the file is stale
    python3 build_schema.py path/to/doc.yml # also validate a document against the models
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
SCHEMA_PATH = os.path.normpath(os.path.join(HERE, "..", "schema", "frameforge-v2.schema.json"))
SRC_DIR = os.path.join(ROOT, "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

# Import ONLY under the canonical dotted name: an alias registered as
# `frameforge` in sys.modules would poison every later import of the package in
# the process (order-dependent failures; see tests/test_module_shadow_regression.py).
import frameforge_api  # noqa: E402
import frameforge_api.model as fg  # noqa: E402


def build() -> dict:
    """The contract's schema, verbatim.

    Delegation, not generation: `$id`, `version`, `title` and the
    `x-frameforge-deprecations` registry are all decided by the contract
    distribution, which is the only place they should be decided.
    """
    return frameforge_api.build_schema()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("document", nargs="?", help="optional document to validate against the models")
    ap.add_argument("--check", action="store_true", help="fail if the on-disk schema is stale")
    args = ap.parse_args(argv)

    schema = build()
    text = json.dumps(schema, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        on_disk = open(SCHEMA_PATH, encoding="utf-8").read() if os.path.exists(SCHEMA_PATH) else ""
        if on_disk != text:
            print("STALE: schema/frameforge-v2.schema.json differs from a fresh build. Run build_schema.py.")
            return 1
        print("OK: schema is in sync with the models.")
        return 0

    os.makedirs(os.path.dirname(SCHEMA_PATH), exist_ok=True)
    with open(SCHEMA_PATH, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {SCHEMA_PATH}  ({len(schema.get('$defs', {}))} $defs)")

    if args.document:
        import yaml
        doc = yaml.safe_load(open(args.document, encoding="utf-8"))
        try:
            fg.Document.model_validate(doc)
            print(f"VALID against the models: {args.document}")
        except Exception as exc:  # noqa: BLE001
            print(f"INVALID: {args.document}\n{exc}")
            return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
