"""Python SDK for authoring, validating, expanding, and serializing FrameForge.

The SDK is a hand-written Python binding over the repository's authoritative
Pydantic model in :mod:`frameforge.model`. It deliberately does not duplicate
core schema types; builders and helpers lower into the model and validate there.
"""
from __future__ import annotations

from frameforge.sdk.author import DocumentBuilder, Handle, MasterBuilder, PageBuilder, StackBuilder
from frameforge.sdk.canon import (
    caps_tracking,
    content_box,
    johnston_margins,
    measure_fits,
    modular_scale,
)
from frameforge.sdk.chart import Chart
from frameforge.sdk.chevreul import (
    ClosedPalette,
    closed_palette,
    color_guide,
    complement,
    contrast_of_colours,
    contrast_of_hues,
    contrast_of_scale,
    contrast_ratio,
    dominant_light,
    grey_document,
    harmony_of_hues,
    harmony_of_scale,
    relative_luminance,
    tone_scale,
)
from frameforge.sdk.clip import (
    clip_circle,
    clip_ellipse,
    clip_inset,
    clip_path,
    clip_polygon,
    clip_rect,
    mask_gradient,
    mask_none,
    mask_style,
    mask_url,
    normalize_clip,
    normalize_mask,
)
from frameforge.sdk.conform import (
    OverflowSignal,
    assert_golden,
    overflow_report,
    page_hashes,
    render_page_svgs,
    render_pages_with_stats,
    write_golden,
)
from frameforge.sdk.draw import (
    Frame, Material, Scene3D, function_plot, multiview, parametric_curve, polar_plot,
)
from frameforge.sdk.expand import ExpandOptions, ExpandedDocument, expand
from frameforge.sdk.humanize import Hand, apply_humanize
from frameforge.sdk.separate import apply_separation, separate_rects
from frameforge.sdk.geometry import (
    Camera,
    CubicBezier,
    Mat3,
    Mat4,
    Path,
    Vec2,
    Vec3,
    ViewingPipeline,
    aabb,
    aabb3,
    convex_hull,
    convex_hull_3d,
    line_curve_intersections,
    line_intersection,
    mirror,
    obb,
    point_in_polygon,
    polygon_area,
    polyline_length,
    quarter_circle_kappa,
    ray_plane_intersection,
    ray_segment_intersection,
    ray_triangle_intersection,
    segment_curve_intersections,
    segment_intersection,
    segment_plane_intersection,
    segment_polygon_intersections,
    surface_curvature,
    window_to_viewport,
)
from frameforge.sdk.fractal import (
    dragon_curve,
    koch_curve,
    lsystem,
    sierpinski_arrowhead,
    turtle,
)
from frameforge.sdk.figure import (
    FigureAsset,
    FigureContent,
    FigurePlacement,
    FigureProvenance,
    FigureRef,
    ImportedFigurePlacement,
    load_figure,
    merge_figure_defs,
    place_figure,
    place_imported_figure,
)
from frameforge.sdk.flow import FlowBuilder
from frameforge.sdk.io import lower_embedded_svg, parse, serialize, svg_to_objects
from frameforge.sdk.layout import Box, BoxLike, column, grid, inset, row
from frameforge.sdk.markdown import from_markdown
from frameforge.sdk.macros import (
    array,
    cite,
    greeble,
    grid_lines,
    hatch_fill,
    lorem,
    lorem_paragraphs,
    md,
    paragraph,
    ref,
    span,
    sparkline,
    theme,
)
from frameforge.sdk.outline import Placement, place_stamp, repeat_along_path, stroke_outline
from frameforge.sdk.pathtext import offset_path, path_length, path_walker, text_on_path
from frameforge.sdk.book import BookBuilder, ChapterBuilder
from frameforge.sdk.params import eval_expr, resolve_params
from frameforge.sdk.recolor import recolor
from frameforge.sdk.solids import (extrude, loft, revolve, section_loops,
                                   section_object, sweep)
from frameforge.sdk import planar
from frameforge.sdk.planar import (chamfer_ring, extend_segment, fill_regions,
                                   fillet_ring, trim_segment)
from frameforge.sdk.metrics import (font_kern_pairs, kerned_spans,
                                    measure_text, text_height, wrap_text)
from frameforge.sdk.model import (
    HEAD_VERSION,
    Document,
    ValidationError,
    model_module,
    to_plain_dict,
    validate_document,
)
from frameforge.sdk.topology import Edge, Graph, Node
from frameforge.sdk.fields import ScalarField, VectorField
from frameforge.sdk.lattices import Lattice, lattice
from frameforge.sdk import manifold
from frameforge.sdk.manifold import (
    bezier_patch,
    bezier_patch_point,
    bspline_patch,
    bspline_patch_point,
    klein_bottle,
    mobius,
    parametric,
    saddle,
    sphere,
    torus,
    wave,
)
from frameforge.sdk.region import (
    extract_objects,
    gradient_map,
    object_bbox,
    place_region,
    region_grade,
    select_in,
)
from frameforge.sdk.paint import (
    appearance,
    blur_filter,
    conic_gradient,
    diffuse_lighting,
    displacement_map,
    dots,
    effect,
    effect_stack,
    effects,
    fill_stroke,
    filter_chain,
    filter_fn,
    grid_pattern,
    glow,
    hatch,
    linear_gradient,
    neon,
    pattern,
    radial_gradient,
    rgba,
    shadow,
    soft_shadow,
    stroke,
    style_effects,
    specular_lighting,
    text_style,
    turbulence,
)
from frameforge.sdk.validate import Issue, StaticValidationError, ValidationReport, validate_static_rules
from frameforge.sdk.widgets import (
    Panel,
    Theme,
    avatar,
    badge,
    badge_width,
    breadcrumb,
    button,
    card,
    checkbox,
    default_theme,
    divider,
    dropdown,
    field,
    image_placeholder,
    kpi,
    navbar,
    pill,
    progress,
    radio,
    register_theme,
    slider,
    sticky_note,
    table,
    tabs,
    toggle,
)

__all__ = [
    "BookBuilder",
    "Box",
    "BoxLike",
    "Camera",
    "ChapterBuilder",
    "Chart",
    "ClosedPalette",
    "CubicBezier",
    "Document",
    "DocumentBuilder",
    "Edge",
    "ExpandOptions",
    "ExpandedDocument",
    "FigureAsset",
    "FigureContent",
    "FigurePlacement",
    "FigureProvenance",
    "FigureRef",
    "FlowBuilder",
    "Frame",
    "Graph",
    "HEAD_VERSION",
    "Hand",
    "Handle",
    "ImportedFigurePlacement",
    "Issue",
    "Lattice",
    "MasterBuilder",
    "Mat3",
    "Mat4",
    "Material",
    "Node",
    "OverflowSignal",
    "PageBuilder",
    "Panel",
    "Path",
    "Placement",
    "ScalarField",
    "Scene3D",
    "StackBuilder",
    "StaticValidationError",
    "Theme",
    "ValidationError",
    "ValidationReport",
    "Vec2",
    "Vec3",
    "VectorField",
    "ViewingPipeline",
    "aabb",
    "aabb3",
    "appearance",
    "apply_humanize",
    "apply_separation",
    "array",
    "assert_golden",
    "avatar",
    "badge",
    "badge_width",
    "bezier_patch",
    "bezier_patch_point",
    "blur_filter",
    "breadcrumb",
    "bspline_patch",
    "bspline_patch_point",
    "button",
    "caps_tracking",
    "card",
    "chamfer_ring",
    "checkbox",
    "cite",
    "clip_circle",
    "clip_ellipse",
    "clip_inset",
    "clip_path",
    "clip_polygon",
    "clip_rect",
    "closed_palette",
    "color_guide",
    "column",
    "complement",
    "conic_gradient",
    "content_box",
    "contrast_of_colours",
    "contrast_of_hues",
    "contrast_of_scale",
    "contrast_ratio",
    "convex_hull",
    "convex_hull_3d",
    "default_theme",
    "diffuse_lighting",
    "displacement_map",
    "divider",
    "dominant_light",
    "dots",
    "dragon_curve",
    "dropdown",
    "effect",
    "effect_stack",
    "effects",
    "eval_expr",
    "expand",
    "extend_segment",
    "extract_objects",
    "extrude",
    "field",
    "fill_regions",
    "fill_stroke",
    "fillet_ring",
    "filter_chain",
    "filter_fn",
    "font_kern_pairs",
    "from_markdown",
    "function_plot",
    "glow",
    "gradient_map",
    "greeble",
    "grey_document",
    "grid",
    "grid_lines",
    "grid_pattern",
    "harmony_of_hues",
    "harmony_of_scale",
    "hatch",
    "hatch_fill",
    "image_placeholder",
    "inset",
    "johnston_margins",
    "kerned_spans",
    "klein_bottle",
    "koch_curve",
    "kpi",
    "lattice",
    "line_curve_intersections",
    "line_intersection",
    "linear_gradient",
    "load_figure",
    "loft",
    "lorem",
    "lorem_paragraphs",
    "lower_embedded_svg",
    "lsystem",
    "manifold",
    "mask_gradient",
    "mask_none",
    "mask_style",
    "mask_url",
    "md",
    "measure_fits",
    "measure_text",
    "merge_figure_defs",
    "mirror",
    "mobius",
    "model_module",
    "modular_scale",
    "multiview",
    "navbar",
    "neon",
    "normalize_clip",
    "normalize_mask",
    "obb",
    "object_bbox",
    "offset_path",
    "overflow_report",
    "page_hashes",
    "paragraph",
    "parametric",
    "parametric_curve",
    "parse",
    "path_length",
    "path_walker",
    "pattern",
    "pill",
    "place_figure",
    "place_imported_figure",
    "place_region",
    "place_stamp",
    "planar",
    "point_in_polygon",
    "polar_plot",
    "polygon_area",
    "polyline_length",
    "progress",
    "quarter_circle_kappa",
    "radial_gradient",
    "radio",
    "ray_plane_intersection",
    "ray_segment_intersection",
    "ray_triangle_intersection",
    "recolor",
    "ref",
    "region_grade",
    "register_theme",
    "relative_luminance",
    "render_page_svgs",
    "render_pages_with_stats",
    "repeat_along_path",
    "resolve_params",
    "revolve",
    "rgba",
    "row",
    "saddle",
    "section_loops",
    "section_object",
    "segment_curve_intersections",
    "segment_intersection",
    "segment_plane_intersection",
    "segment_polygon_intersections",
    "select_in",
    "separate_rects",
    "serialize",
    "shadow",
    "sierpinski_arrowhead",
    "slider",
    "soft_shadow",
    "span",
    "sparkline",
    "specular_lighting",
    "sphere",
    "sticky_note",
    "stroke",
    "stroke_outline",
    "style_effects",
    "surface_curvature",
    "svg_to_objects",
    "sweep",
    "table",
    "tabs",
    "text_height",
    "text_on_path",
    "text_style",
    "theme",
    "to_plain_dict",
    "toggle",
    "tone_scale",
    "torus",
    "trim_segment",
    "turbulence",
    "turtle",
    "validate_document",
    "validate_static_rules",
    "wave",
    "window_to_viewport",
    "wrap_text",
    "write_golden",
]
