"""Python SDK for authoring, validating, expanding, and serializing FrameGraph.

The SDK is a hand-written Python binding over the repository's authoritative
Pydantic model in :mod:`models.framegraph`. It deliberately does not duplicate
core schema types; builders and helpers lower into the model and validate there.
"""
from __future__ import annotations

from framegraph.sdk.author import DocumentBuilder, Handle, MasterBuilder, PageBuilder, StackBuilder
from framegraph.sdk.canon import (
    caps_tracking,
    content_box,
    johnston_margins,
    measure_fits,
    modular_scale,
)
from framegraph.sdk.chart import Chart
from framegraph.sdk.chevreul import (
    ClosedPalette,
    closed_palette,
    complement,
    contrast_of_colours,
    contrast_of_hues,
    contrast_of_scale,
    contrast_ratio,
    dominant_light,
    grey_document,
    harmony_of_hues,
    harmony_of_scale,
    relative_luminance,
    tone_scale,
)
from framegraph.sdk.clip import (
    clip_circle,
    clip_ellipse,
    clip_inset,
    clip_path,
    clip_polygon,
    clip_rect,
    normalize_clip,
)
from framegraph.sdk.conform import (
    assert_golden,
    page_hashes,
    render_page_svgs,
    render_pages_with_stats,
    write_golden,
)
from framegraph.sdk.draw import (
    Frame, Material, Scene3D, function_plot, multiview, parametric_curve, polar_plot,
)
from framegraph.sdk.expand import ExpandOptions, ExpandedDocument, expand
from framegraph.sdk.humanize import Hand, apply_humanize
from framegraph.sdk.geometry import (
    Camera,
    CubicBezier,
    Mat3,
    Mat4,
    Path,
    Vec2,
    Vec3,
    ViewingPipeline,
    aabb,
    convex_hull,
    line_intersection,
    mirror,
    point_in_polygon,
    polygon_area,
    polyline_length,
    quarter_circle_kappa,
    ray_segment_intersection,
    segment_intersection,
    segment_polygon_intersections,
    window_to_viewport,
)
from framegraph.sdk.fractal import (
    dragon_curve,
    koch_curve,
    lsystem,
    sierpinski_arrowhead,
    turtle,
)
from framegraph.sdk.figure import (
    FigureAsset,
    FigureContent,
    FigurePlacement,
    FigureProvenance,
    FigureRef,
    ImportedFigurePlacement,
    load_figure,
    merge_figure_defs,
    place_figure,
    place_imported_figure,
)
from framegraph.sdk.flow import FlowBuilder
from framegraph.sdk.io import parse, serialize, svg_to_objects
from framegraph.sdk.layout import Box, BoxLike, column, grid, inset, row
from framegraph.sdk.markdown import from_markdown
from framegraph.sdk.macros import (
    cite,
    greeble,
    grid_lines,
    hatch_fill,
    lorem,
    lorem_paragraphs,
    md,
    paragraph,
    ref,
    span,
    sparkline,
    theme,
)
from framegraph.sdk.outline import Placement, repeat_along_path, stroke_outline
from framegraph.sdk.book import BookBuilder, ChapterBuilder
from framegraph.sdk.recolor import recolor
from framegraph.sdk import planar
from framegraph.sdk.metrics import (font_kern_pairs, kerned_spans,
                                    measure_text, text_height, wrap_text)
from framegraph.sdk.model import (
    HEAD_VERSION,
    Document,
    ValidationError,
    model_module,
    to_plain_dict,
    validate_document,
)
from framegraph.sdk.topology import Edge, Graph, Node
from framegraph.sdk.fields import ScalarField, VectorField
from framegraph.sdk.lattices import Lattice, lattice
from framegraph.sdk import manifold
from framegraph.sdk.manifold import (
    klein_bottle,
    mobius,
    parametric,
    saddle,
    sphere,
    torus,
    wave,
)
from framegraph.sdk.region import (
    extract_objects,
    gradient_map,
    object_bbox,
    place_region,
    region_grade,
    select_in,
)
from framegraph.sdk.paint import (
    dots,
    effects,
    fill_stroke,
    grid_pattern,
    glow,
    hatch,
    linear_gradient,
    neon,
    pattern,
    radial_gradient,
    rgba,
    shadow,
    soft_shadow,
    stroke,
    text_style,
)
from framegraph.sdk.validate import Issue, StaticValidationError, ValidationReport, validate_static_rules
from framegraph.sdk.widgets import (
    Panel,
    Theme,
    avatar,
    badge,
    badge_width,
    breadcrumb,
    button,
    card,
    checkbox,
    default_theme,
    divider,
    dropdown,
    field,
    image_placeholder,
    kpi,
    navbar,
    pill,
    progress,
    radio,
    register_theme,
    slider,
    sticky_note,
    table,
    tabs,
    toggle,
)

__all__ = [
    "from_markdown",
    "ClosedPalette",
    "caps_tracking",
    "closed_palette",
    "complement",
    "content_box",
    "contrast_of_colours",
    "contrast_of_hues",
    "contrast_of_scale",
    "contrast_ratio",
    "dominant_light",
    "grey_document",
    "harmony_of_hues",
    "harmony_of_scale",
    "johnston_margins",
    "measure_fits",
    "modular_scale",
    "relative_luminance",
    "tone_scale",
    "Chart",
    "Panel",
    "Theme",
    "assert_golden",
    "avatar",
    "badge",
    "badge_width",
    "breadcrumb",
    "button",
    "card",
    "checkbox",
    "clip_circle",
    "clip_ellipse",
    "clip_inset",
    "clip_path",
    "clip_polygon",
    "clip_rect",
    "default_theme",
    "divider",
    "dropdown",
    "field",
    "image_placeholder",
    "kpi",
    "navbar",
    "pill",
    "progress",
    "radio",
    "register_theme",
    "slider",
    "sticky_note",
    "table",
    "tabs",
    "toggle",
    "Camera",
    "CubicBezier",
    "Document",
    "DocumentBuilder",
    "Edge",
    "ExpandOptions",
    "ExpandedDocument",
    "FlowBuilder",
    "Frame",
    "FigureAsset",
    "FigureContent",
    "FigurePlacement",
    "FigureProvenance",
    "FigureRef",
    "ImportedFigurePlacement",
    "greeble",
    "grid_lines",
    "grid_pattern",
    "Graph",
    "Hand",
    "Handle",
    "apply_humanize",
    "hatch",
    "hatch_fill",
    "Lattice",
    "Material",
    "Node",
    "ScalarField",
    "VectorField",
    "lattice",
    "load_figure",
    "manifold",
    "merge_figure_defs",
    "HEAD_VERSION",
    "Issue",
    "MasterBuilder",
    "Mat3",
    "Mat4",
    "PageBuilder",
    "Path",
    "Scene3D",
    "StackBuilder",
    "StaticValidationError",
    "ValidationReport",
    "Vec2",
    "Vec3",
    "Box",
    "BoxLike",
    "column",
    "dots",
    "effects",
    "expand",
    "extract_objects",
    "fill_stroke",
    "function_plot",
    "glow",
    "gradient_map",
    "grid",
    "inset",
    "linear_gradient",
    "lorem",
    "lorem_paragraphs",
    "cite",
    "ref",
    "md",
    "measure_text",
    "font_kern_pairs",
    "kerned_spans",
    "Placement",
    "repeat_along_path",
    "recolor",
    "BookBuilder",
    "ChapterBuilder",
    "planar",
    "stroke_outline",
    "model_module",
    "klein_bottle",
    "mobius",
    "multiview",
    "neon",
    "normalize_clip",
    "object_bbox",
    "page_hashes",
    "paragraph",
    "parametric",
    "parametric_curve",
    "pattern",
    "place_figure",
    "place_region",
    "polar_plot",
    "place_imported_figure",
    "parse",
    "region_grade",
    "select_in",
    "dragon_curve",
    "koch_curve",
    "lsystem",
    "sierpinski_arrowhead",
    "turtle",
    "aabb",
    "convex_hull",
    "line_intersection",
    "mirror",
    "point_in_polygon",
    "polygon_area",
    "polyline_length",
    "ray_segment_intersection",
    "segment_intersection",
    "segment_polygon_intersections",
    "window_to_viewport",
    "ViewingPipeline",
    "quarter_circle_kappa",
    "radial_gradient",
    "render_page_svgs",
    "render_pages_with_stats",
    "rgba",
    "row",
    "serialize",
    "shadow",
    "soft_shadow",
    "saddle",
    "span",
    "sparkline",
    "sphere",
    "stroke",
    "svg_to_objects",
    "text_height",
    "text_style",
    "theme",
    "to_plain_dict",
    "torus",
    "validate_document",
    "validate_static_rules",
    "ValidationError",
    "wrap_text",
    "wave",
    "write_golden",
]
