#!/usr/bin/env python3
"""
gen_examples_index.py — generate docs/examples.md from the tracked example scripts.

The ``examples/`` directory is the SDK cookbook (~80 runnable clients), but there
was no index: agents rediscovered authoring patterns by grepping example source.
This tool scans every *git-tracked* ``examples/*.py`` (untracked scratch scripts
are deliberately excluded), extracts the module docstring's first sentence-line
(or the leading ``#`` comment when there is no docstring), and emits a generated
cookbook page.

Same contract as ``gen_status.py``: the page is generated + committed, and
``tests/test_capability_manifest.py`` gates that the listed file set matches the
tracked examples (summaries regenerate via ``make examples-index``).

Usage:
    python tooling/gen_examples_index.py            # (re)write docs/examples.md
    python tooling/gen_examples_index.py --check    # exit 1 if the file set is stale
"""
from __future__ import annotations

import argparse
import ast
import datetime as _dt
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "docs", "examples.md")

_LIST_RE = re.compile(r"^\| \[`([^`]+)`\]", re.M)


def tracked_examples() -> list[str]:
    """Git-tracked ``examples/*.py`` paths (repo-relative, sorted)."""
    out = subprocess.run(
        ["git", "ls-files", "examples/*.py"], cwd=ROOT, capture_output=True, text=True
    ).stdout
    return sorted(p for p in out.split() if p)


def summarize(path: str) -> str:
    """One-line intent: first non-empty module-docstring line, else the first
    leading ``#`` comment line, else a stated absence."""
    with open(os.path.join(ROOT, path), encoding="utf-8") as fh:
        source = fh.read()
    try:
        doc = ast.get_docstring(ast.parse(source))
    except SyntaxError:
        doc = None
    if doc:
        for line in doc.splitlines():
            if line.strip():
                return line.strip()
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("#!") or stripped.startswith("# -*-"):
            continue
        if stripped.startswith("#"):
            text = stripped.lstrip("#").strip()
            if text:
                return text
        elif stripped:
            break
    return "(no module docstring)"


def build_index() -> list[tuple[str, str]]:
    return [(path, _cell(summarize(path))) for path in tracked_examples()]


def _cell(text: str) -> str:
    """Make a summary safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def render(*, date: str | None = None) -> str:
    date = date or _dt.date.today().isoformat()
    rows = build_index()
    lines = [
        "---",
        "disclaimer:",
        "  notice: >-",
        "    No information within this document should be taken for granted.",
        "    Any statement or premise not backed by a real logical definition",
        "    or verifiable reference may be invalid, erroneous, or a hallucination.",
        '  generated_by: "tooling/gen_examples_index.py (generator authored by Claude Fable 5 via Claude Code)"',
        f'  date: "{date}"',
        "---",
        "",
        "<!-- GENERATED by tooling/gen_examples_index.py — do not hand-edit; "
        "run `make examples-index`. -->",
        "",
        "# Examples cookbook",
        "",
        f"The {len(rows)} tracked, runnable SDK clients under `examples/`, indexed by "
        "their stated intent (the module docstring's first line). Run any of them "
        "with `uv run python examples/<name>.py`; most write their output under "
        "`out/` or `_tmp/`.",
        "",
        "| Example | Intent |",
        "|---|---|",
    ]
    for path, summary in rows:
        name = os.path.basename(path)
        lines.append(f"| [`{name}`](../examples/{name}) | {summary} |")
    lines.append("")
    return "\n".join(lines)


def listed_files(text: str) -> set[str]:
    """Basenames listed in a rendered examples index (for the sync gate)."""
    return set(_LIST_RE.findall(text))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail if docs/examples.md lists a stale example set")
    args = ap.parse_args(argv)

    if args.check:
        on_disk = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        expected = {os.path.basename(p) for p in tracked_examples()}
        if listed_files(on_disk) != expected:
            print("STALE: docs/examples.md file set differs from tracked examples/*.py. "
                  "Run `make examples-index` and commit the result.")
            return 1
        print("OK: examples index covers the tracked example set.")
        return 0

    text = render()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {os.path.relpath(OUT, ROOT)}  ({len(tracked_examples())} examples)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
