#!/usr/bin/env python3
"""
gen_status.py — generate FIXTURE-STATUS.md from the validator.

Replaces the hand-maintained CHANGELOG fixture table with a generated one, so the
"which fixtures are clean / which carry known errors" status cannot drift from
what validate.py actually reports. Same contract as build_schema.py:

    python tooling/gen_status.py            # (re)write FIXTURE-STATUS.md
    python tooling/gen_status.py --check    # exit 1 if the committed file is stale

Scope: the *delivered* tracked top-level fixtures (fixtures/*.fg.yaml +
*.frameforge.yml) — the documents meant to be conformant. The b1/ oracle is
validated separately (pre-codemod) by tests/test_head.py, so it is intentionally
excluded here. Untracked fixture experiments are ignored when git metadata is
available, matching Makefile's FIXTURES_YAML contract.
"""
import argparse
import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "tooling"))

import tracked_files  # noqa: E402
import validate as V  # noqa: E402

OUT = os.path.join(ROOT, "docs", "FIXTURE-STATUS.md")
PATTERNS = ("tests/fixtures/*.fg.yaml", "tests/fixtures/*.frameforge.yml")
HEADER = "<!-- GENERATED by tooling/gen_status.py — do not hand-edit; run `make status`. -->"
_BUILD_CACHE = {}


def is_top_level_fixture(path):
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    if not rel.startswith("tests/fixtures/") or rel.count("/") != 2:
        return False
    return rel.endswith(".fg.yaml") or rel.endswith(".frameforge.yml")


def fixture_files():
    tracked = tracked_files.tracked_paths(ROOT, *PATTERNS)
    if not tracked:
        return sorted(f for p in PATTERNS for f in glob.glob(os.path.join(ROOT, p)) if is_top_level_fixture(f))
    missing = [rel for rel in tracked if not os.path.isfile(os.path.join(ROOT, rel))]
    if missing:
        # A validator needs a real file, so a tracked-but-deleted fixture cannot be
        # graded — say so loudly rather than truncating the table without a word.
        print(
            f"gen_status: WARNING — {len(missing)} tracked fixture(s) absent from the "
            f"worktree, omitted from the table: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
    return [
        os.path.join(ROOT, rel)
        for rel in tracked
        if os.path.isfile(os.path.join(ROOT, rel))
        and is_top_level_fixture(os.path.join(ROOT, rel))
    ]


def build():
    files = sorted(fixture_files())
    signature = tuple(
        (f, os.stat(f).st_mtime_ns, os.stat(f).st_size)
        for f in files
    )
    cached = _BUILD_CACHE.get(signature)
    if cached is not None:
        return cached

    rows = []
    for f in files:
        _, findings, _ = V.validate_doc(f)
        errs = sum(1 for x in findings if x.severity == "ERROR")
        warns = sum(1 for x in findings if x.severity == "WARN")
        if errs:
            note = "; ".join(sorted({x.code for x in findings if x.severity == "ERROR"}))
        elif warns:
            note = "advisory warnings only (" + ", ".join(
                sorted({x.code for x in findings if x.severity == "WARN"})) + ")"
        else:
            note = "clean"
        rows.append((os.path.basename(f), errs, warns, note))

    clean = sum(1 for _, e, _, _ in rows if e == 0)
    lines = [
        "# Fixture status (generated)",
        "",
        HEADER,
        "",
        f"Delivered top-level fixtures validated against the HEAD core profile "
        f"(`tooling/validate.py`). **{clean}/{len(rows)}** have zero errors.",
        "",
        "| Fixture | Errors | Warnings | Notes |",
        "|---|---:|---:|---|",
    ]
    for name, e, w, note in rows:
        lines.append(f"| `{name}` | {e} | {w} | {note} |")
    lines.append("")
    text = "\n".join(lines) + "\n"
    _BUILD_CACHE.clear()
    _BUILD_CACHE[signature] = text
    return text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if FIXTURE-STATUS.md is stale")
    args = ap.parse_args(argv)

    text = build()
    if args.check:
        on_disk = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if on_disk != text:
            print("STALE: FIXTURE-STATUS.md differs from a fresh validator run. Run `make status`.")
            return 1
        print("OK: FIXTURE-STATUS.md is in sync with the validator.")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
