#!/usr/bin/env python3
"""
gen_docs.py — generate the MkDocs site content from the source of truth.

Writes the generated pages under docs/ that `mkdocs build` consumes, so the
documentation site is generated from source artifacts instead of hand-drifted,
the same way the schema and the fixture-status table are:

  docs/reference.md  ← generated from schema/frameforge-v2.schema.json ($defs)
  docs/grammar.md    ← the two grammar/*.ebnf files, embedded
  docs/fixtures.md   ← gallery: every fixture rendered to SVG (render_fixtures.py)
                       + the validator status table (gen_status.py)
  docs/sdk.md        ← practical Python SDK guide (committed generated snapshot)
  docs/sdk-api.md    ← Python SDK API reference generated from docstrings (committed)
  docs/spec.md       ← spec/frameforge-v2-spec.md (verbatim)
  docs/changelog.md  ← CHANGELOG.md (verbatim)

`docs/index.md` is hand-written. The SDK guide/API are committed generated
snapshots; the reference/spec/grammar/fixtures/changelog pages and render assets
are transient build artifacts. Run via `make docs` (which then builds the site).
Needs only stdlib + pydantic + pyyaml — no docs tooling — so it runs in a
bare/offline env; the theme is fetched at build time by `make docs`.

Usage:
    python tooling/gen_docs.py            # (re)generate the pages
    python tooling/gen_docs.py --check    # generate, then assert mkdocs.yml nav is satisfied
"""
import argparse
import importlib.util
import inspect
import os
import subprocess
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "docs")
sys.path[:0] = [DOCS, os.path.join(ROOT, "docs", "schema"), os.path.join(ROOT, "tooling")]

import build_schema as B  # noqa: E402
import gen_status as GS  # noqa: E402


# --------------------------------------------------------------------------- #
#  schema reference                                                           #
# --------------------------------------------------------------------------- #
def _anchor(name):
    return name.lower().replace("_", "-")


def _type_str(s):
    """A compact human type summary for a JSON-Schema property node."""
    if not isinstance(s, dict):
        return "any"
    if "$ref" in s:
        n = s["$ref"].split("/")[-1]
        return f"[`{n}`](#{_anchor(n)})"
    if "const" in s:
        return f"`{s['const']!r}`"
    if "enum" in s:
        vals = [f"`{v}`" for v in s["enum"]]
        return " \\| ".join(vals[:10]) + (" …" if len(vals) > 10 else "")
    if "anyOf" in s or "oneOf" in s:
        parts = [_type_str(x) for x in s.get("anyOf", s.get("oneOf", [])) if x.get("type") != "null"]
        seen = list(dict.fromkeys(parts))
        return " \\| ".join(seen) if seen else "null"
    t = s.get("type")
    if t == "array":
        return f"array&lt;{_type_str(s.get('items', {}))}&gt;"
    if isinstance(t, list):
        return " \\| ".join(t)
    if t:
        return f"{t} ({s['format']})" if s.get("format") else t
    return "object" if "properties" in s else "any"


def _model_section(name, defn):
    out = [f"## `{name}`", ""]
    if defn.get("description"):
        out += [defn["description"].strip(), ""]
    props = defn.get("properties")
    if not props:
        if "enum" in defn:
            out += ["One of: " + ", ".join(f"`{v}`" for v in defn["enum"]), ""]
        return "\n".join(out) + "\n"
    required = set(defn.get("required", []))
    out += ["| Property | Type | Required | Description |", "|---|---|:--:|---|"]
    for pname, pschema in props.items():
        req = "✓" if pname in required else ""
        desc = (pschema.get("description", "") or "").replace("\n", " ").replace("|", "\\|")
        out.append(f"| `{pname}` | {_type_str(pschema)} | {req} | {desc} |")
    out.append("")
    return "\n".join(out) + "\n"


def gen_reference():
    schema = B.build()
    defs = schema.get("$defs", {})
    lines = [
        "# Schema reference",
        "",
        "!!! info \"Generated\"",
        f"    Generated by `tooling/gen_docs.py` from `schema/frameforge-v2.schema.json` "
        f"— **{len(defs)} models** ({schema.get('title','').split('—')[0].strip()}). "
        f"Do not hand-edit. The schema itself is generated from the Pydantic models.",
        "",
    ]
    # Document is the schema root, not a $defs member. Render it first so the
    # reference covers the full public model surface, then list $defs alphabetically.
    order = ["Document"] + sorted(defs)
    lines.append("**Models:** " + " · ".join(f"[`{k}`](#{_anchor(k)})" for k in order))
    lines.append("")
    for name in order:
        lines.append(_model_section(name, schema if name == "Document" else defs[name]))
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
#  grammar / spec / changelog                                                 #
# --------------------------------------------------------------------------- #
def gen_grammar():
    parts = [
        "# Grammar",
        "",
        "!!! note \"A view, not the source\"",
        "    The EBNF is a **view** of the Pydantic models (the source of truth); the "
        "`grammar-check` gate (`tooling/check_grammar_sync.py`) fails CI on core-profile "
        "drift between the two. The models are the authority if they ever disagree. "
        "Generated by `tooling/gen_docs.py`.",
        "",
    ]
    for title, fn in [("Core grammar — `frameforge-v2.ebnf`", "frameforge-v2.ebnf"),
                      ("Style module — `frameforge-v2-style.ebnf`", "frameforge-v2-style.ebnf")]:
        body = open(os.path.join(ROOT, "docs", "grammar", fn), encoding="utf-8").read()
        parts += [f"## {title}", "", "```ebnf", body.rstrip(), "```", ""]
    return "\n".join(parts) + "\n"


def _verbatim(src_rel, banner):
    body = open(os.path.join(ROOT, src_rel), encoding="utf-8").read()
    return f"<!-- GENERATED by tooling/gen_docs.py from {src_rel} — {banner} -->\n\n" + body


def gen_fixtures():
    # render every fixture to docs/assets/render/ (idempotent; the renderer owns layout)
    out = os.path.join(DOCS, "assets", "render")
    subprocess.run([sys.executable, os.path.join(ROOT, "tooling", "render_fixtures.py"),
                    "--all", "--out", out, "-q"], check=True, cwd=ROOT)
    status = open(GS.OUT, encoding="utf-8").read() if os.path.exists(GS.OUT) else GS.build()
    # strip the status file's own H1 so it nests under our section
    status_body = "\n".join(ln for ln in status.splitlines() if not ln.startswith("# "))
    lines = [
        "# Fixture gallery",
        "",
        "!!! warning \"Sanity-check proxy\"",
        "    Rendered by the dependency-free SVG proxy (`tooling/render_fixtures.py`): "
        "geometry, positions, colours and z-order are faithful, but there is no real "
        "text shaping and fonts are the browser's generic families. Not pixel-accurate. "
        "For browser-native CSS filter/blend/backdrop/mask raster fidelity, use "
        "`tooling/render_chromium.py` after installing the optional `browser` group.",
        "",
        "## Validator status",
        status_body,
        "## Renders",
        "",
    ]
    render_root = os.path.join(DOCS, "assets", "render")
    for stem in sorted(d for d in os.listdir(render_root)
                       if os.path.isdir(os.path.join(render_root, d))):
        pages = sorted(p for p in os.listdir(os.path.join(render_root, stem)) if p.endswith(".svg"))
        if not pages:
            continue
        thumb = f"assets/render/{stem}/{pages[0]}"
        idx = f"assets/render/{stem}/index.html"
        lines += [
            f"### {stem}",
            f"[![{stem}]({thumb}){{ width=420 loading=lazy }}]({idx})",
            f"*{len(pages)} page(s) — [browse all]({idx})*",
            "",
        ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
#  Python SDK                                                                 #
# --------------------------------------------------------------------------- #
def gen_sdk_guide():
    example = """\
    from pathlib import Path

    from frameforge.sdk import (
        DocumentBuilder,
        ExpandOptions,
        expand,
        parse,
        serialize,
        validate_static_rules,
    )

    builder = DocumentBuilder(title="SDK quickstart", profile="deck")
    ink = builder.define_color("ink", "#111827")
    title = builder.define_text_style(
        "title",
        font_family="Inter",
        font_size=28,
        color=ink,
    )
    asset = builder.define_asset("logo", "assets/logo.svg", kind="image")

    page = builder.page("cover", canvas={"size": [1280, 720], "units": "px"})
    page.layer("main").text([64, 64, 720, 48], "Hello FrameForge", id="h1", style=title)
    page.image([64, 140, 96, 96], asset, alt="Project logo")

    doc = builder.build()
    report = validate_static_rules(doc)
    assert report.ok, report.issues

    expanded = expand(doc, opts=ExpandOptions(base_dir=Path(".")))
    yaml_text = serialize(expanded.document, format="yaml")
    parsed = parse(yaml_text, forgiving=False)
    """
    reuse_example = """\
    from frameforge.sdk import DocumentBuilder

    builder = DocumentBuilder()
    with builder.symbol("badge", [0, 0, 100, 32]) as badge:
        badge.rect([0, 0, 100, 32], fill="$fill", radius=8)
        badge.text([12, 6, 76, 20], "$label")

    page = builder.page("p", canvas={"size": [320, 180], "units": "px"})
    page.layer("main").use_at(
        "badge",
        24, 24, 160, 48,
        params={"fill": "#dbeafe", "label": "Generated"},
    )

    # build() expands the use into a core-model group.
    doc = builder.build()
    """
    paint_geometry_example = """\
    from frameforge.sdk import (
        DocumentBuilder,
        dots,
        grid_pattern,
        hatch,
        neon,
        stroke,
    )

    builder = DocumentBuilder()
    page = builder.page("p", canvas={"size": [420, 240], "units": "px"})
    layer = page.layer("main")

    layer.rect([24, 24, 120, 80], fill=hatch(fg="#64748b", bg="#e2e8f0", scale=8))
    layer.rect([164, 24, 80, 80], fill=dots(fg="#334155", bg="#f8fafc", scale=10))
    layer.rect([264, 24, 80, 80], fill=grid_pattern(fg="#94a3b8", scale=12))
    layer.arc([220, 64], 40, 180, 360, **stroke(4, color="#2563eb", cap="round"))
    layer.sector([88, 170], 42, -110, 30, fill="#fed7aa")
    layer.ring([210, 170], 46, 26, fill="#bfdbfe")
    layer.regular_polygon([320, 72], 38, 6, rotation=-90, fill="#ccfbf1")
    layer.star([320, 170], 42, 18, 5, fill="#fde68a", **neon("#22d3ee"))
    layer.polyline([(40, 220), (120, 190), (200, 220)], smooth=True,
                   fill="none", stroke="#7c3aed")
    """
    macros_example = """\
    from frameforge.sdk import DocumentBuilder, greeble, grid_lines, hatch_fill, sparkline

    builder = DocumentBuilder()
    layer = builder.page("p", canvas={"size": [420, 220], "units": "px"}).layer("main")

    with layer.local([24, 24, 360, 160], clip=[0, 0, 360, 160]) as panel:
        panel.extend(hatch_fill([16, 16, 120, 56], fg="#64748b", bg="#f1f5f9"))
        panel.extend(grid_lines([16, 92, 120, 48], cols=4, rows=3))
        panel.extend(greeble([168, 16, 160, 84], seed=7, density=0.7, fill="#94a3b8"))
        panel.add(sparkline([(0, 2), (1, 4), (2, 3), (3, 7)], [168, 116, 160, 32]))
    """
    stack_example = """\
    from frameforge.sdk import DocumentBuilder, badge, button

    builder = DocumentBuilder()
    layer = builder.page("p", canvas={"size": [640, 240], "units": "px"}).layer("main")

    with layer.hstack([24, 24, 520, 56], gap=12, pad=12, align="center") as row:
        row.add(button("Cancel", kind="ghost"))
        row.spacer(h=36, grow=1)
        row.add(button("Deploy", grow=1))

    with layer.wrap([24, 104, 360, 96], gap=8, pad=12) as chips:
        for label in ["api", "renderer", "schema", "layout-native", "docs"]:
            chips.add(badge(label, tone="accent"))

    doc = builder.build()
    """
    canon_example = """\
    from frameforge.sdk import DocumentBuilder, canon, chevreul

    # one decided colour system + one decided size system, before any drawing
    palette = chevreul.closed_palette(ground="#fbf8f1", ink="#1d1e22", accent="#b5402c")
    sizes = canon.modular_scale(base=11.5, ratio=1.25)   # caption ... cover

    builder = DocumentBuilder(title="Canon demo", profile="report")
    for name, value in palette.tokens().items():
        builder.define_color(name, value)

    page = builder.page("p1", canvas={"size": [794, 1123], "units": "px"},
                        coordinate_mode="absolute")
    x, y, w, h = canon.content_box(794, 1123, unit=40, side="recto")
    layer = page.layer("main")
    layer.rect([0, 0, 794, 1123], fill="ground")
    layer.text([x, y, w, 26], "KICKER IN TRACKED CAPS", style={
        "color": "accent", "font_size": sizes["caption"],
        "letter_spacing": canon.caps_tracking(sizes["caption"]),
    })
    layer.text([x, y + 40, w, sizes["h1"] * 1.4], "The letter & the hue",
               style={"color": "ink", "font_size": sizes["h1"]})

    # accents that agree: an analogous walk, or one complementary chord
    accents = chevreul.harmony_of_hues("blue", n=3)
    field, event = chevreul.contrast_of_colours("red")

    # the grey test: strip hue, re-render, check the hierarchy still reads
    grey = chevreul.grey_document(builder.build_dict())
    """
    topology_example = """\
    import math

    from frameforge.sdk import (
        Camera, DocumentBuilder, Graph, ScalarField, Vec3, lattice, manifold,
    )

    builder = DocumentBuilder(profile="diagram")
    layer = builder.page("p", canvas={"size": [960, 320], "units": "px"},
                         coordinate_mode="absolute").layer("main")

    # 1. Network topology — build a graph, lay it out, render to one group.
    g = Graph()
    for a, b in [("api", "auth"), ("api", "db"), ("auth", "cache"), ("db", "cache")]:
        g.edge(a, b)
    layer.add(g.render(g.spring_layout(), box=[20, 20, 280, 280]))

    # 2. A scalar field as a heatmap + marching-squares contours.
    sf = ScalarField(lambda x, y: math.sin(2 * x) * math.cos(2 * y),
                     domain=(-1.5, -1.5, 1.5, 1.5))
    field = sf.heatmap(box=[330, 20, 280, 280])
    field["children"] += sf.contours(box=[330, 20, 280, 280], levels=6)["children"]
    layer.add(field)

    # 3. A 3D manifold + a crystal lattice through a perspective camera.
    cam = Camera(eye=Vec3(2.6, 2.0, 3.4), target=Vec3(0, 0, 0), fov=46)
    layer.add(manifold.torus().render(box=[640, 20, 140, 280], camera=cam,
                                      fill="#f9a8d4", stroke="#9d174d"))
    layer.add(lattice("fcc", nx=2, ny=2, nz=2).render(box=[800, 20, 140, 280], camera=cam))

    doc = builder.build()
    """
    figure_example = """\
    from frameforge.sdk import DocumentBuilder, FigureRef

    def draw_plate(builder):
        plate = builder.page("plate", canvas={"size": [400, 240], "units": "px"})
        plate.layer("main").rect([0, 0, 400, 240], fill="#f8fafc")
        plate.text([32, 32, 260, 32], "Live figure")

    builder = DocumentBuilder()
    page = builder.page("p", canvas={"size": [640, 360], "units": "px"}).layer("main")
    page.figure(
        FigureRef.from_callable(draw_plate, page="plate"),
        [40, 40, 320, 180],
        fit="contain",
        align="center",
        id_prefix="fig1-",
    )
    """
    imported_figure_example = """\
    from frameforge.sdk import DocumentBuilder, FigureAsset

    figure = FigureAsset.from_pdf_image(
        "book-assets/biology-fig-1-1.jpg",
        source="openstax-biology-2e.pdf",
        page=29,
        box=[108, 157, 826, 443],
        number="1.1",
        caption="This NASA image is a composite of satellite-based views of Earth.",
        alt="Earth from space",
        license="CC-BY-4.0",
        attribution="Biology 2e, OpenStax, Rice University, CC BY 4.0",
        confidence=0.91,
    )

    builder = DocumentBuilder()
    page = builder.page("p", canvas={"size": [640, 480], "units": "px"}).layer("main")
    page.imported_figure(figure, [48, 48, 420, 300], caption_position="below")
    """
    validate_example = """\
    from frameforge.sdk import validate_static_rules

    report = validate_static_rules(document, targets=["print"])
    for issue in report.issues:
        print(issue.severity, issue.rule_id, issue.path, issue.message)
    """
    lines = [
        "# Python SDK",
        "",
        "!!! info \"Generated\"",
        "    Generated by `tooling/gen_docs.py` from examples in the docs pipeline and checked by `docs-check`. "
        "Do not hand-edit.",
        "",
        "The Python SDK lives under `frameforge.sdk`. It is a hand-written binding over the repository's "
        "authoritative Pydantic model, so document-producing APIs validate through `frameforge.model.Document` "
        "instead of redeclaring core schema types.",
        "",
        "## Install and import",
        "",
        "Use it from the repository checkout with the project environment:",
        "",
        "```bash",
        "uv run python -c \"from frameforge.sdk import DocumentBuilder; print(DocumentBuilder)\"",
        "```",
        "",
        "Most public helpers are re-exported from `frameforge.sdk`: builders, parse/serialize, validation, "
        "expansion, geometry, draw helpers, and macros. See [Python SDK API](sdk-api.md) for signatures.",
        "",
        "## Quickstart",
        "",
        "```python",
        textwrap.dedent(example).rstrip(),
        "```",
        "",
        "## Authoring model",
        "",
        "- `DocumentBuilder` defines tokens, assets, masters, symbols, and components.",
        "- `PageBuilder` adds layers and visual objects.",
        "- Definition helpers return nominal `Handle` values. The Python SDK rejects wrong-kind handles at runtime "
        "and keeps plain string references for compatibility.",
        "- `build()` returns the current core model. Grammar-level authoring forms such as `use` and simple "
        "`component` are lowered before validation.",
        "",
        "## Reuse",
        "",
        "```python",
        textwrap.dedent(reuse_example).rstrip(),
        "```",
        "",
        "`builder.symbol()` is the author-once path for reusable motifs; `page.use_at()` places instances from "
        "scalar coordinates. `page.local()` and its `page.panel()` alias collect children in local coordinates "
        "under a box-anchored group.",
        "",
        "## Layout-Native Stacks",
        "",
        "`PageBuilder.hstack()`, `vstack()`, `wrap()`, and `grid_stack()` collect local children and emit real "
        "`group.layout` containers. Widget atoms such as `button(\"Save\")` and `badge(\"api\")` can now create "
        "intrinsic local boxes for stack use, and `StackBuilder.spacer()` emits a grow/fill spacer.",
        "",
        "```python",
        textwrap.dedent(stack_example).rstrip(),
        "```",
        "",
        "## Paint and Geometry",
        "",
        "Paint helpers return model-native paint dictionaries. Geometry helpers on `PageBuilder` solve author-time "
        "math and lower to existing `path` or canonical closed `polyline` objects.",
        "Translucency (`opacity` / `rgba()`), blend modes and CSS filters are already model-native style fields; "
        "`Material` groups those fields for SDK-authored geometry, and `Scene3D.render(shading=\"lambert\"|\"gouraud\")` "
        "bakes a pure-Python light pass into ordinary face fills.",
        "",
        "```python",
        textwrap.dedent(paint_geometry_example).rstrip(),
        "```",
        "",
        "## Procedural Texture Macros",
        "",
        "Macros under `frameforge.sdk.macros` return ordinary objects/lists that can be added directly or passed "
        "to `PageBuilder.extend()`.",
        "",
        "```python",
        textwrap.dedent(macros_example).rstrip(),
        "```",
        "",
        "## Design Canon — colour & typography",
        "",
        "Two canon modules codify working design rules so authors (human or agent) start from *decided* "
        "systems instead of ad-hoc picks. `frameforge.sdk.chevreul` (after M. E. Chevreul, 1839): the "
        "12-station painter's wheel with `complement`, tone scales, the **six harmonies** "
        "(`harmony_of_scale`/`harmony_of_hues`/`dominant_light` and the three contrasts), WCAG 2.1 "
        "`relative_luminance`/`contrast_ratio`, the `grey_document` tone audit, and `closed_palette` — "
        "duties (ground/ink/accent + quiet steps) with the 62/30/8 `AREA_GUIDE`, emitting a ready "
        "`defs.tokens.colors` fragment. `frameforge.sdk.canon` (after Edward Johnston, 1906): "
        "`modular_scale`, the inner-1½/top-2/outer-3/foot-4 margin canon (`johnston_margins`/"
        "`content_box`), the 45–75 characters-per-line measure band, and `caps_tracking`. "
        "Pure helpers only — nothing new enters the schema.",
        "",
        "```python",
        textwrap.dedent(canon_example).rstrip(),
        "```",
        "",
        "## Topology, perspective & math surfaces",
        "",
        "Four solver modules turn data and parametric math into FrameForge art, each lowering to a single "
        "`group` (so the geometric audit, which does not recurse into groups, stays quiet):",
        "",
        "- **Topology** (`frameforge.sdk.topology`): `Graph` builds a node-link network and lays it out with "
        "deterministic algorithms — `circular_layout`, `radial_layout`, `layered_layout` (DAG), `grid_layout`, "
        "and a seeded `spring_layout` (Fruchterman–Reingold). `Graph.render()` draws edges, arrowheads and "
        "fitted labels.",
        "- **Perspective** (`frameforge.sdk.geometry.Camera`): a `look_at` + field-of-view camera composes a "
        "view/projection `Mat4`. Pass a `Camera` to `Scene3D.render()`, `Graph.render()`, a `Lattice`, or any "
        "manifold to project 3D positions; `Camera.orbit()` sweeps the eye for frame-by-frame motion.",
        "- **Fields** (`frameforge.sdk.fields`): `VectorField` samples `(x, y) -> (u, v)` into a grid of arrows; "
        "`ScalarField` renders `(x, y) -> value` as a `heatmap` and/or marching-squares `contours`.",
        "- **Lattices & manifolds** (`frameforge.sdk.lattices`, `frameforge.sdk.manifold`): `lattice(kind, ...)` "
        "builds 2D (square/triangular/honeycomb) and 3D (cubic/bcc/fcc) crystals with nearest-neighbour bonds, "
        "rendered through the same `Graph` engine; `manifold.{sphere,torus,mobius,klein_bottle,saddle,wave}` "
        "build perspective-ready parametric `Scene3D` surfaces — `wave` is the interference heightfield.",
        "",
        "See the `topology-perspective` and `fields-lattices-manifolds` entries in the "
        "[Fixture gallery](fixtures.md) for full pages built from these helpers.",
        "",
        "```python",
        textwrap.dedent(topology_example).rstrip(),
        "```",
        "",
        "## Live Figure Imports",
        "",
        "`FigureRef` and `PageBuilder.figure()` import another FrameForge page as live object children. "
        "The source may be a callable plate function, builder/document/dict, or `.fg.yaml`/`.fg.json` path; "
        "placement controls page/layer selection, fit mode, alignment, crop/viewbox, ID prefixing, clipping, "
        "and whether the imported figure is treated as decorative.",
        "",
        "```python",
        textwrap.dedent(figure_example).rstrip(),
        "```",
        "",
        "## Imported Book Figures",
        "",
        "`FigureAsset` and `PageBuilder.imported_figure()` model figures extracted from PDF, EPUB, or image "
        "sources. Unlike `FigureRef`, this API is designed for book-import pipelines: it keeps source "
        "provenance, page/spine locator, source bounding box, caption fields, alt text, attribution, and "
        "confidence attached to the lowered image/caption group.",
        "",
        "```python",
        textwrap.dedent(imported_figure_example).rstrip(),
        "```",
        "",
        "## Validation",
        "",
        "`validate_static_rules()` runs Pydantic structure validation, the repository static validator, and SDK "
        "checks for references, requested targets, target hide IDs, master-region chains, and path data.",
        "",
        "```python",
        textwrap.dedent(validate_example).rstrip(),
        "```",
        "",
        "## Expansion",
        "",
        "`expand()` is the reproducibility boundary for SDK-resolvable output. It hash-pins local assets/fonts, "
        "lowers `use` and simple `component` authoring forms, and validates the expanded result. Draw helpers such "
        "as `Frame`, `Path`, and `Scene3D.render()` solve geometry before the model sees the document.",
        "",
        "## Serialization",
        "",
        "`serialize()` writes canonical JSON/YAML. `parse()` is forgiving by default: current documents return a "
        "validated model, while syntactically valid newer documents outside the current SDK model return raw data. "
        "Use `parse(text, forgiving=False)` to require current-schema validation.",
        "",
    ]
    return "\n".join(lines) + "\n"


def gen_sdk_api():
    _ensure_sdk_importable()
    import frameforge.sdk as sdk

    modules = [
        "frameforge.sdk.author",
        "frameforge.sdk.canon",
        "frameforge.sdk.chart",
        "frameforge.sdk.chevreul",
        "frameforge.sdk.clip",
        "frameforge.sdk.conform",
        "frameforge.sdk.draw",
        "frameforge.sdk.expand",
        "frameforge.sdk.fields",
        "frameforge.sdk.figure",
        "frameforge.sdk.fractal",
        "frameforge.sdk.geometry",
        "frameforge.sdk.io",
        "frameforge.sdk.lattices",
        "frameforge.sdk.layout",
        "frameforge.sdk.macros",
        "frameforge.sdk.manifold",
        "frameforge.sdk.markdown",
        "frameforge.sdk.model",
        "frameforge.sdk.paint",
        "frameforge.sdk.region",
        "frameforge.sdk.topology",
        "frameforge.sdk.validate",
        "frameforge.sdk.widgets",
    ]
    lines = [
        "# Python SDK API",
        "",
        "!!! info \"Generated\"",
        "    Generated by `tooling/gen_docs.py` from `frameforge.sdk` public exports, docstrings, and signatures. "
        "Do not hand-edit.",
        "",
        "## Public exports",
        "",
        ", ".join(f"`{name}`" for name in sdk.__all__),
        "",
    ]
    for module_name in modules:
        if importlib.util.find_spec(module_name) is None:
            continue
        module = __import__(module_name, fromlist=["*"])
        exports = list(getattr(module, "__all__", []))
        if not exports:
            continue
        lines += [f"## `{module_name}`", ""]
        for name in exports:
            lines.extend(_api_object_block(name, getattr(module, name)))
    return "\n".join(lines) + "\n"


def _ensure_sdk_importable():
    # Put the repo roots first so reflection sees THIS tree's package. (The
    # historical eviction of a model-module shadow is gone: since 2.5.0 the
    # model lives inside the package and nothing else can own the name.)
    if ROOT in sys.path:
        sys.path.remove(ROOT)
    sys.path[:0] = [ROOT, os.path.join(ROOT, "src")]


def _api_object_block(name, obj):
    if not (inspect.isclass(obj) or inspect.isfunction(obj)):
        return [f"### `{name}`", "", f"`{type(obj).__name__}` value: `{obj!r}`", ""]
    qualified = f"{obj.__module__}.{getattr(obj, '__qualname__', name)}"
    lines = [f"### `{name}`", "", f"`{qualified}`", ""]
    doc = inspect.getdoc(obj)
    if doc:
        lines += [doc.splitlines()[0], ""]
    if inspect.isclass(obj):
        lines.extend(_signature_block(name, obj))
        methods = [
            (method_name, member)
            for method_name, member in inspect.getmembers(obj, predicate=inspect.isfunction)
            if not method_name.startswith("_")
        ]
        if methods:
            lines += ["| Method | Signature | Summary |", "|---|---|---|"]
            for method_name, member in methods:
                method_doc = inspect.getdoc(member)
                summary = method_doc.splitlines()[0] if method_doc else ""
                lines.append(
                    f"| `{method_name}` | `{_md_cell(_safe_signature(member))}` | {_md_cell(summary)} |"
                )
            lines.append("")
    elif inspect.isfunction(obj):
        lines.extend(_signature_block(name, obj))
    return lines


def _signature_block(name, obj):
    signature = _safe_signature(obj)
    if signature == "()":
        return []
    return ["```python", f"{name}{signature}", "```", ""]


def _safe_signature(obj):
    try:
        # Normalize the typing repr across Python versions: `str(inspect.signature)`
        # renders typing generics as `typing.Annotated[...]` on some interpreters
        # and the bare `Annotated[...]` on others. Strip the module prefix so the
        # generated signature — and therefore the committed sdk-api.md snapshot —
        # is deterministic regardless of the local Python (keeps docs-check from
        # drifting between a contributor's machine and CI).
        return str(inspect.signature(obj)).replace("typing.", "")
    except (TypeError, ValueError):
        return "()"


def _md_cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


# --------------------------------------------------------------------------- #
def _write(rel, text):
    path = os.path.join(DOCS, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return rel


def generate():
    os.makedirs(DOCS, exist_ok=True)
    written = [
        _write("reference.md", gen_reference()),
        _write("grammar.md", gen_grammar()),
        _write("spec.md", _verbatim("docs/spec/frameforge-v2-spec.md", "the normative reference")),
        _write("sdk.md", gen_sdk_guide()),
        _write("sdk-api.md", gen_sdk_api()),
        _write("changelog.md", _verbatim("CHANGELOG.md", "version history")),
        _write("fixtures.md", gen_fixtures()),
    ]
    return written


# Generated pages that are *committed* (not gitignored): the SDK guide/API are
# checked-in snapshots, so `--check` must fail if the committed copy drifts from a
# fresh build — the same "generate + --check, never hand-drift" contract that
# build_schema.py --check gives the schema. The transient pages are gitignored and
# need no such gate.
_TRACKED_GENERATED = {"sdk.md": gen_sdk_guide, "sdk-api.md": gen_sdk_api}


def stale_tracked_pages():
    """Committed generated pages whose on-disk content differs from a fresh build.
    Read this BEFORE generate() runs, since generate() overwrites them in place."""
    stale = []
    for rel, builder in _TRACKED_GENERATED.items():
        path = os.path.join(DOCS, rel)
        on_disk = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if on_disk != builder():
            stale.append(rel)
    return stale


def write_tracked():
    """Regenerate only the *committed* snapshots (``sdk.md``/``sdk-api.md``).

    The cheap fix when ``--check`` reports SDK-snapshot drift: it skips the
    fixture-gallery render the full :func:`generate` does (41 docs → SVG), so
    refreshing the snapshot after an SDK change costs a fraction of `make docs`."""
    return [_write(rel, builder()) for rel, builder in _TRACKED_GENERATED.items()]


def _nav_targets():
    import yaml
    cfg = yaml.safe_load(open(os.path.join(ROOT, "mkdocs.yml"), encoding="utf-8"))
    return list(_nav_entry_targets(cfg.get("nav", [])))


def _nav_entry_targets(entries):
    for entry in entries:
        if isinstance(entry, str):
            yield entry
        elif isinstance(entry, dict):
            for value in entry.values():
                if isinstance(value, str):
                    yield value
                elif isinstance(value, list):
                    yield from _nav_entry_targets(value)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="generate, then assert committed generated pages are fresh "
                         "and every mkdocs.yml nav page exists")
    ap.add_argument("--sdk", action="store_true",
                    help="regenerate ONLY the committed SDK snapshots (sdk.md, "
                         "sdk-api.md) — fast; the cheap fix when --check reports drift")
    args = ap.parse_args(argv)

    if args.sdk:
        written = write_tracked()
        print(f"Wrote {len(written)} SDK snapshot(s) to docs/: {', '.join(written)}")
        return 0

    # Capture drift in the committed snapshots BEFORE generate() overwrites them.
    stale = stale_tracked_pages() if args.check else []

    written = generate()
    print(f"Wrote {len(written)} page(s) to docs/: {', '.join(written)}")

    if args.check:
        if stale:
            print(f"STALE: committed generated docs differ from a fresh build: {stale}. "
                  f"Run `make docs-sdk` (fast) and commit the result.")
            return 1
        missing = [t for t in _nav_targets() if not os.path.exists(os.path.join(DOCS, t))]
        if missing:
            print(f"NAV BROKEN: mkdocs.yml references missing pages: {missing}")
            return 1
        print("OK: committed generated docs are fresh and every mkdocs.yml nav page exists.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
