#!/usr/bin/env python3
"""
gen_docs.py — generate the MkDocs site content from the source of truth.

Writes the git-ignored pages under docs/ that `mkdocs build` consumes, so the
documentation site is generated (never hand-drifted), the same way the schema and
the fixture-status table are:

  docs/reference.md  ← generated from schema/framegraph-v2.schema.json ($defs)
  docs/grammar.md    ← the two grammar/*.ebnf files, embedded
  docs/fixtures.md   ← gallery: every fixture rendered to SVG (render_fixtures.py)
                       + the validator status table (gen_status.py)
  docs/sdk.md        ← practical Python SDK guide
  docs/sdk-api.md    ← Python SDK API reference generated from docstrings
  docs/spec.md       ← spec/framegraph-v2-spec.md (verbatim)
  docs/changelog.md  ← CHANGELOG.md (verbatim)

Only docs/index.md is hand-written/committed. Run via `make docs` (which then
builds the site). Needs only stdlib + pydantic + pyyaml — no docs tooling — so it
runs in a bare/offline env; the theme is fetched at build time by `make docs`.

Usage:
    python tooling/gen_docs.py            # (re)generate the pages
    python tooling/gen_docs.py --check    # generate, then assert mkdocs.yml nav is satisfied
"""
import argparse
import importlib.util
import inspect
import os
import subprocess
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "docs")
sys.path[:0] = [os.path.join(ROOT, "models"), os.path.join(ROOT, "schema"), os.path.join(ROOT, "tooling")]

import build_schema as B  # noqa: E402
import gen_status as GS  # noqa: E402


# --------------------------------------------------------------------------- #
#  schema reference                                                           #
# --------------------------------------------------------------------------- #
def _anchor(name):
    return name.lower().replace("_", "-")


def _type_str(s):
    """A compact human type summary for a JSON-Schema property node."""
    if not isinstance(s, dict):
        return "any"
    if "$ref" in s:
        n = s["$ref"].split("/")[-1]
        return f"[`{n}`](#{_anchor(n)})"
    if "const" in s:
        return f"`{s['const']!r}`"
    if "enum" in s:
        vals = [f"`{v}`" for v in s["enum"]]
        return " \\| ".join(vals[:10]) + (" …" if len(vals) > 10 else "")
    if "anyOf" in s or "oneOf" in s:
        parts = [_type_str(x) for x in s.get("anyOf", s.get("oneOf", [])) if x.get("type") != "null"]
        seen = list(dict.fromkeys(parts))
        return " \\| ".join(seen) if seen else "null"
    t = s.get("type")
    if t == "array":
        return f"array&lt;{_type_str(s.get('items', {}))}&gt;"
    if isinstance(t, list):
        return " \\| ".join(t)
    if t:
        return f"{t} ({s['format']})" if s.get("format") else t
    return "object" if "properties" in s else "any"


def _model_section(name, defn):
    out = [f"## `{name}`", ""]
    if defn.get("description"):
        out += [defn["description"].strip(), ""]
    props = defn.get("properties")
    if not props:
        if "enum" in defn:
            out += ["One of: " + ", ".join(f"`{v}`" for v in defn["enum"]), ""]
        return "\n".join(out) + "\n"
    required = set(defn.get("required", []))
    out += ["| Property | Type | Required | Description |", "|---|---|:--:|---|"]
    for pname, pschema in props.items():
        req = "✓" if pname in required else ""
        desc = (pschema.get("description", "") or "").replace("\n", " ").replace("|", "\\|")
        out.append(f"| `{pname}` | {_type_str(pschema)} | {req} | {desc} |")
    out.append("")
    return "\n".join(out) + "\n"


def gen_reference():
    schema = B.build()
    defs = schema.get("$defs", {})
    lines = [
        "# Schema reference",
        "",
        "!!! info \"Generated\"",
        f"    Generated by `tooling/gen_docs.py` from `schema/framegraph-v2.schema.json` "
        f"— **{len(defs)} models** ({schema.get('title','').split('—')[0].strip()}). "
        f"Do not hand-edit. The schema itself is generated from the Pydantic models.",
        "",
    ]
    # Document is the schema root, not a $defs member. Render it first so the
    # reference covers the full public model surface, then list $defs alphabetically.
    order = ["Document"] + sorted(defs)
    lines.append("**Models:** " + " · ".join(f"[`{k}`](#{_anchor(k)})" for k in order))
    lines.append("")
    for name in order:
        lines.append(_model_section(name, schema if name == "Document" else defs[name]))
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
#  grammar / spec / changelog                                                 #
# --------------------------------------------------------------------------- #
def gen_grammar():
    parts = [
        "# Grammar",
        "",
        "!!! note \"A view, not the source\"",
        "    The EBNF is a **view** of the Pydantic models (the source of truth); the "
        "`grammar-check` gate (`tooling/check_grammar_sync.py`) fails CI on core-profile "
        "drift between the two. The models are the authority if they ever disagree. "
        "Generated by `tooling/gen_docs.py`.",
        "",
    ]
    for title, fn in [("Core grammar — `framegraph-v2.ebnf`", "framegraph-v2.ebnf"),
                      ("Style module — `framegraph-v2-style.ebnf`", "framegraph-v2-style.ebnf")]:
        body = open(os.path.join(ROOT, "grammar", fn), encoding="utf-8").read()
        parts += [f"## {title}", "", "```ebnf", body.rstrip(), "```", ""]
    return "\n".join(parts) + "\n"


def _verbatim(src_rel, banner):
    body = open(os.path.join(ROOT, src_rel), encoding="utf-8").read()
    return f"<!-- GENERATED by tooling/gen_docs.py from {src_rel} — {banner} -->\n\n" + body


def gen_fixtures():
    # render every fixture to docs/assets/render/ (idempotent; the renderer owns layout)
    out = os.path.join(DOCS, "assets", "render")
    subprocess.run([sys.executable, os.path.join(ROOT, "tooling", "render_fixtures.py"),
                    "--all", "--out", out, "-q"], check=True, cwd=ROOT)
    status = open(GS.OUT, encoding="utf-8").read() if os.path.exists(GS.OUT) else GS.build()
    # strip the status file's own H1 so it nests under our section
    status_body = "\n".join(ln for ln in status.splitlines() if not ln.startswith("# "))
    lines = [
        "# Fixture gallery",
        "",
        "!!! warning \"Sanity-check proxy\"",
        "    Rendered by the dependency-free SVG proxy (`tooling/render_fixtures.py`): "
        "geometry, positions, colours and z-order are faithful, but there is no real "
        "text shaping and fonts are the browser's generic families. Not pixel-accurate.",
        "",
        "## Validator status",
        status_body,
        "## Renders",
        "",
    ]
    render_root = os.path.join(DOCS, "assets", "render")
    for stem in sorted(d for d in os.listdir(render_root)
                       if os.path.isdir(os.path.join(render_root, d))):
        pages = sorted(p for p in os.listdir(os.path.join(render_root, stem)) if p.endswith(".svg"))
        if not pages:
            continue
        thumb = f"assets/render/{stem}/{pages[0]}"
        idx = f"assets/render/{stem}/index.html"
        lines += [
            f"### {stem}",
            f"[![{stem}]({thumb}){{ width=420 loading=lazy }}]({idx})",
            f"*{len(pages)} page(s) — [browse all]({idx})*",
            "",
        ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
#  Python SDK                                                                 #
# --------------------------------------------------------------------------- #
def gen_sdk_guide():
    example = """\
    from pathlib import Path

    from framegraph.sdk import (
        DocumentBuilder,
        ExpandOptions,
        expand,
        parse,
        serialize,
        validate_static_rules,
    )

    builder = DocumentBuilder(title="SDK quickstart", profile="deck")
    ink = builder.define_color("ink", "#111827")
    title = builder.define_text_style(
        "title",
        font_family="Inter",
        font_size=28,
        color=ink,
    )
    asset = builder.define_asset("logo", "assets/logo.svg", kind="image")

    page = builder.page("cover", canvas={"size": [1280, 720], "units": "px"})
    page.layer("main").text([64, 64, 720, 48], "Hello FrameGraph", id="h1", style=title)
    page.image([64, 140, 96, 96], asset, alt="Project logo")

    doc = builder.build()
    report = validate_static_rules(doc)
    assert report.ok, report.issues

    expanded = expand(doc, opts=ExpandOptions(base_dir=Path(".")))
    yaml_text = serialize(expanded.document, format="yaml")
    parsed = parse(yaml_text, forgiving=False)
    """
    reuse_example = """\
    from framegraph.sdk import DocumentBuilder

    builder = DocumentBuilder()
    badge = builder.define_symbol(
        "badge",
        box=[0, 0, 100, 32],
        objects=[
            {"type": "rect", "box": [0, 0, 100, 32], "fill": "$fill", "radius": 8},
            {"type": "text", "box": [12, 6, 76, 20], "text": "$label"},
        ],
    )

    page = builder.page("p", canvas={"size": [320, 180], "units": "px"})
    page.layer("main").use(
        badge,
        [24, 24, 160, 48],
        params={"fill": "#dbeafe", "label": "Generated"},
    )

    # build() expands the use into a core-model group.
    doc = builder.build()
    """
    validate_example = """\
    from framegraph.sdk import validate_static_rules

    report = validate_static_rules(document, targets=["print"])
    for issue in report.issues:
        print(issue.severity, issue.rule_id, issue.path, issue.message)
    """
    lines = [
        "# Python SDK",
        "",
        "!!! info \"Generated\"",
        "    Generated by `tooling/gen_docs.py` from examples in the docs pipeline and checked by `docs-check`. "
        "Do not hand-edit.",
        "",
        "The Python SDK lives under `framegraph.sdk`. It is a hand-written binding over the repository's "
        "authoritative Pydantic model, so document-producing APIs validate through `models.framegraph.Document` "
        "instead of redeclaring core schema types.",
        "",
        "## Install and import",
        "",
        "Use it from the repository checkout with the project environment:",
        "",
        "```bash",
        "uv run python -c \"from framegraph.sdk import DocumentBuilder; print(DocumentBuilder)\"",
        "```",
        "",
        "Most public helpers are re-exported from `framegraph.sdk`: builders, parse/serialize, validation, "
        "expansion, geometry, draw helpers, and macros. See [Python SDK API](sdk-api.md) for signatures.",
        "",
        "## Quickstart",
        "",
        "```python",
        textwrap.dedent(example).rstrip(),
        "```",
        "",
        "## Authoring model",
        "",
        "- `DocumentBuilder` defines tokens, assets, masters, symbols, and components.",
        "- `PageBuilder` adds layers and visual objects.",
        "- Definition helpers return nominal `Handle` values. The Python SDK rejects wrong-kind handles at runtime "
        "and keeps plain string references for compatibility.",
        "- `build()` returns the current core model. Grammar-level authoring forms such as `use` and simple "
        "`component` are lowered before validation.",
        "",
        "## Reuse",
        "",
        "```python",
        textwrap.dedent(reuse_example).rstrip(),
        "```",
        "",
        "## Validation",
        "",
        "`validate_static_rules()` runs Pydantic structure validation, the repository static validator, and SDK "
        "checks for references, requested targets, target hide IDs, master-region chains, and path data.",
        "",
        "```python",
        textwrap.dedent(validate_example).rstrip(),
        "```",
        "",
        "## Expansion",
        "",
        "`expand()` is the reproducibility boundary for SDK-resolvable output. It hash-pins local assets/fonts, "
        "lowers `use` and simple `component` authoring forms, and validates the expanded result. Draw helpers such "
        "as `Frame`, `Path`, and `Scene3D.render()` solve geometry before the model sees the document.",
        "",
        "## Serialization",
        "",
        "`serialize()` writes canonical JSON/YAML. `parse()` is forgiving by default: current documents return a "
        "validated model, while syntactically valid newer documents outside the current SDK model return raw data. "
        "Use `parse(text, forgiving=False)` to require current-schema validation.",
        "",
    ]
    return "\n".join(lines) + "\n"


def gen_sdk_api():
    _ensure_sdk_importable()
    import framegraph.sdk as sdk

    modules = [
        "framegraph.sdk.author",
        "framegraph.sdk.chart",
        "framegraph.sdk.draw",
        "framegraph.sdk.expand",
        "framegraph.sdk.geometry",
        "framegraph.sdk.io",
        "framegraph.sdk.layout",
        "framegraph.sdk.macros",
        "framegraph.sdk.model",
        "framegraph.sdk.paint",
        "framegraph.sdk.validate",
    ]
    lines = [
        "# Python SDK API",
        "",
        "!!! info \"Generated\"",
        "    Generated by `tooling/gen_docs.py` from `framegraph.sdk` public exports, docstrings, and signatures. "
        "Do not hand-edit.",
        "",
        "## Public exports",
        "",
        ", ".join(f"`{name}`" for name in sdk.__all__),
        "",
    ]
    for module_name in modules:
        if importlib.util.find_spec(module_name) is None:
            continue
        module = __import__(module_name, fromlist=["*"])
        exports = list(getattr(module, "__all__", []))
        if not exports:
            continue
        lines += [f"## `{module_name}`", ""]
        for name in exports:
            lines.extend(_api_object_block(name, getattr(module, name)))
    return "\n".join(lines) + "\n"


def _ensure_sdk_importable():
    existing = sys.modules.get("framegraph")
    if existing is not None and not hasattr(existing, "__path__"):
        sys.modules.pop("framegraph", None)
    if ROOT not in sys.path:
        sys.path.insert(0, ROOT)


def _api_object_block(name, obj):
    if not (inspect.isclass(obj) or inspect.isfunction(obj)):
        return [f"### `{name}`", "", f"`{type(obj).__name__}` value: `{obj!r}`", ""]
    qualified = f"{obj.__module__}.{getattr(obj, '__qualname__', name)}"
    lines = [f"### `{name}`", "", f"`{qualified}`", ""]
    doc = inspect.getdoc(obj)
    if doc:
        lines += [doc.splitlines()[0], ""]
    if inspect.isclass(obj):
        lines.extend(_signature_block(name, obj))
        methods = [
            (method_name, member)
            for method_name, member in inspect.getmembers(obj, predicate=inspect.isfunction)
            if not method_name.startswith("_")
        ]
        if methods:
            lines += ["| Method | Signature | Summary |", "|---|---|---|"]
            for method_name, member in methods:
                method_doc = inspect.getdoc(member)
                summary = method_doc.splitlines()[0] if method_doc else ""
                lines.append(
                    f"| `{method_name}` | `{_md_cell(_safe_signature(member))}` | {_md_cell(summary)} |"
                )
            lines.append("")
    elif inspect.isfunction(obj):
        lines.extend(_signature_block(name, obj))
    return lines


def _signature_block(name, obj):
    signature = _safe_signature(obj)
    if signature == "()":
        return []
    return ["```python", f"{name}{signature}", "```", ""]


def _safe_signature(obj):
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "()"


def _md_cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


# --------------------------------------------------------------------------- #
def _write(rel, text):
    path = os.path.join(DOCS, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return rel


def generate():
    os.makedirs(DOCS, exist_ok=True)
    written = [
        _write("reference.md", gen_reference()),
        _write("grammar.md", gen_grammar()),
        _write("spec.md", _verbatim("spec/framegraph-v2-spec.md", "the normative reference")),
        _write("sdk.md", gen_sdk_guide()),
        _write("sdk-api.md", gen_sdk_api()),
        _write("changelog.md", _verbatim("CHANGELOG.md", "version history")),
        _write("fixtures.md", gen_fixtures()),
    ]
    return written


def _nav_targets():
    import yaml
    cfg = yaml.safe_load(open(os.path.join(ROOT, "mkdocs.yml"), encoding="utf-8"))
    return list(_nav_entry_targets(cfg.get("nav", [])))


def _nav_entry_targets(entries):
    for entry in entries:
        if isinstance(entry, str):
            yield entry
        elif isinstance(entry, dict):
            for value in entry.values():
                if isinstance(value, str):
                    yield value
                elif isinstance(value, list):
                    yield from _nav_entry_targets(value)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="generate, then assert every mkdocs.yml nav page exists")
    args = ap.parse_args(argv)

    written = generate()
    print(f"Wrote {len(written)} page(s) to docs/: {', '.join(written)}")

    if args.check:
        missing = [t for t in _nav_targets() if not os.path.exists(os.path.join(DOCS, t))]
        if missing:
            print(f"NAV BROKEN: mkdocs.yml references missing pages: {missing}")
            return 1
        print("OK: every mkdocs.yml nav page exists.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
