#!/usr/bin/env python3
"""
gen_docs.py — generate the MkDocs site content from the source of truth.

Writes the git-ignored pages under docs/ that `mkdocs build` consumes, so the
documentation site is generated (never hand-drifted), the same way the schema and
the fixture-status table are:

  docs/reference.md  ← generated from schema/framegraph-v2.schema.json ($defs)
  docs/grammar.md    ← the two grammar/*.ebnf files, embedded
  docs/fixtures.md   ← gallery: every fixture rendered to SVG (render_fixtures.py)
                       + the validator status table (gen_status.py)
  docs/spec.md       ← spec/framegraph-v2-spec.md (verbatim)
  docs/changelog.md  ← CHANGELOG.md (verbatim)

Only docs/index.md is hand-written/committed. Run via `make docs` (which then
builds the site). Needs only stdlib + pydantic + pyyaml — no docs tooling — so it
runs in a bare/offline env; the theme is fetched at build time by `make docs`.

Usage:
    python tooling/gen_docs.py            # (re)generate the pages
    python tooling/gen_docs.py --check    # generate, then assert mkdocs.yml nav is satisfied
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "docs")
sys.path[:0] = [os.path.join(ROOT, "models"), os.path.join(ROOT, "schema"), os.path.join(ROOT, "tooling")]

import build_schema as B  # noqa: E402
import gen_status as GS  # noqa: E402


# --------------------------------------------------------------------------- #
#  schema reference                                                           #
# --------------------------------------------------------------------------- #
def _anchor(name):
    return name.lower().replace("_", "-")


def _type_str(s):
    """A compact human type summary for a JSON-Schema property node."""
    if not isinstance(s, dict):
        return "any"
    if "$ref" in s:
        n = s["$ref"].split("/")[-1]
        return f"[`{n}`](#{_anchor(n)})"
    if "const" in s:
        return f"`{s['const']!r}`"
    if "enum" in s:
        vals = [f"`{v}`" for v in s["enum"]]
        return " \\| ".join(vals[:10]) + (" …" if len(vals) > 10 else "")
    if "anyOf" in s or "oneOf" in s:
        parts = [_type_str(x) for x in s.get("anyOf", s.get("oneOf", [])) if x.get("type") != "null"]
        seen = list(dict.fromkeys(parts))
        return " \\| ".join(seen) if seen else "null"
    t = s.get("type")
    if t == "array":
        return f"array&lt;{_type_str(s.get('items', {}))}&gt;"
    if isinstance(t, list):
        return " \\| ".join(t)
    if t:
        return f"{t} ({s['format']})" if s.get("format") else t
    return "object" if "properties" in s else "any"


def _model_section(name, defn):
    out = [f"## `{name}`", ""]
    if defn.get("description"):
        out += [defn["description"].strip(), ""]
    props = defn.get("properties")
    if not props:
        if "enum" in defn:
            out += ["One of: " + ", ".join(f"`{v}`" for v in defn["enum"]), ""]
        return "\n".join(out) + "\n"
    required = set(defn.get("required", []))
    out += ["| Property | Type | Required | Description |", "|---|---|:--:|---|"]
    for pname, pschema in props.items():
        req = "✓" if pname in required else ""
        desc = (pschema.get("description", "") or "").replace("\n", " ").replace("|", "\\|")
        out.append(f"| `{pname}` | {_type_str(pschema)} | {req} | {desc} |")
    out.append("")
    return "\n".join(out) + "\n"


def gen_reference():
    schema = B.build()
    defs = schema.get("$defs", {})
    lines = [
        "# Schema reference",
        "",
        "!!! info \"Generated\"",
        f"    Generated by `tooling/gen_docs.py` from `schema/framegraph-v2.schema.json` "
        f"— **{len(defs)} models** ({schema.get('title','').split('—')[0].strip()}). "
        f"Do not hand-edit. The schema itself is generated from the Pydantic models.",
        "",
    ]
    # Document is the schema root, not a $defs member. Render it first so the
    # reference covers the full public model surface, then list $defs alphabetically.
    order = ["Document"] + sorted(defs)
    lines.append("**Models:** " + " · ".join(f"[`{k}`](#{_anchor(k)})" for k in order))
    lines.append("")
    for name in order:
        lines.append(_model_section(name, schema if name == "Document" else defs[name]))
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
#  grammar / spec / changelog                                                 #
# --------------------------------------------------------------------------- #
def gen_grammar():
    parts = [
        "# Grammar",
        "",
        "!!! note \"A view, not the source\"",
        "    The EBNF is kept consistent **by hand**; the Pydantic models are the "
        "authority if the two ever disagree. Generated by `tooling/gen_docs.py`.",
        "",
    ]
    for title, fn in [("Core grammar — `framegraph-v2.ebnf`", "framegraph-v2.ebnf"),
                      ("Style module — `framegraph-v2-style.ebnf`", "framegraph-v2-style.ebnf")]:
        body = open(os.path.join(ROOT, "grammar", fn), encoding="utf-8").read()
        parts += [f"## {title}", "", "```ebnf", body.rstrip(), "```", ""]
    return "\n".join(parts) + "\n"


def _verbatim(src_rel, banner):
    body = open(os.path.join(ROOT, src_rel), encoding="utf-8").read()
    return f"<!-- GENERATED by tooling/gen_docs.py from {src_rel} — {banner} -->\n\n" + body


def gen_fixtures():
    # render every fixture to docs/assets/render/ (idempotent; the renderer owns layout)
    out = os.path.join(DOCS, "assets", "render")
    subprocess.run([sys.executable, os.path.join(ROOT, "tooling", "render_fixtures.py"),
                    "--all", "--out", out, "-q"], check=True, cwd=ROOT)
    status = open(GS.OUT, encoding="utf-8").read() if os.path.exists(GS.OUT) else GS.build()
    # strip the status file's own H1 so it nests under our section
    status_body = "\n".join(ln for ln in status.splitlines() if not ln.startswith("# "))
    lines = [
        "# Fixture gallery",
        "",
        "!!! warning \"Sanity-check proxy\"",
        "    Rendered by the dependency-free SVG proxy (`tooling/render_fixtures.py`): "
        "geometry, positions, colours and z-order are faithful, but there is no real "
        "text shaping and fonts are the browser's generic families. Not pixel-accurate.",
        "",
        "## Validator status",
        status_body,
        "## Renders",
        "",
    ]
    render_root = os.path.join(DOCS, "assets", "render")
    for stem in sorted(d for d in os.listdir(render_root)
                       if os.path.isdir(os.path.join(render_root, d))):
        pages = sorted(p for p in os.listdir(os.path.join(render_root, stem)) if p.endswith(".svg"))
        if not pages:
            continue
        thumb = f"assets/render/{stem}/{pages[0]}"
        idx = f"assets/render/{stem}/index.html"
        lines += [
            f"### {stem}",
            f"[![{stem}]({thumb}){{ width=420 loading=lazy }}]({idx})",
            f"*{len(pages)} page(s) — [browse all]({idx})*",
            "",
        ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
def _write(rel, text):
    path = os.path.join(DOCS, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return rel


def generate():
    os.makedirs(DOCS, exist_ok=True)
    written = [
        _write("reference.md", gen_reference()),
        _write("grammar.md", gen_grammar()),
        _write("spec.md", _verbatim("spec/framegraph-v2-spec.md", "the normative reference")),
        _write("changelog.md", _verbatim("CHANGELOG.md", "version history")),
        _write("fixtures.md", gen_fixtures()),
    ]
    return written


def _nav_targets():
    import yaml
    cfg = yaml.safe_load(open(os.path.join(ROOT, "mkdocs.yml"), encoding="utf-8"))
    targets = []
    for entry in cfg.get("nav", []):
        targets += [v for v in (entry.values() if isinstance(entry, dict) else [entry])]
    return targets


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="generate, then assert every mkdocs.yml nav page exists")
    args = ap.parse_args(argv)

    written = generate()
    print(f"Wrote {len(written)} page(s) to docs/: {', '.join(written)}")

    if args.check:
        missing = [t for t in _nav_targets() if not os.path.exists(os.path.join(DOCS, t))]
        if missing:
            print(f"NAV BROKEN: mkdocs.yml references missing pages: {missing}")
            return 1
        print("OK: every mkdocs.yml nav page exists.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
